# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CraftBar.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_B_CraftBar(object):
    def setupUi(self, B_CraftBar):
        B_CraftBar.setObjectName(_fromUtf8("B_CraftBar"))
        B_CraftBar.resize(587, 512)
        self.layoutWidget = QtGui.QWidget(B_CraftBar)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 494))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.TextLabel1 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel1.sizePolicy().hasHeightForWidth())
        self.TextLabel1.setSizePolicy(sizePolicy)
        self.TextLabel1.setObjectName(_fromUtf8("TextLabel1"))
        self.hboxlayout.addWidget(self.TextLabel1)
        self.DaocPath = QtGui.QLineEdit(self.layoutWidget)
        self.DaocPath.setObjectName(_fromUtf8("DaocPath"))
        self.hboxlayout.addWidget(self.DaocPath)
        self.PathSelectButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PathSelectButton.sizePolicy().hasHeightForWidth())
        self.PathSelectButton.setSizePolicy(sizePolicy)
        self.PathSelectButton.setMinimumSize(QtCore.QSize(28, 28))
        self.PathSelectButton.setMaximumSize(QtCore.QSize(28, 28))
        self.PathSelectButton.setBaseSize(QtCore.QSize(28, 28))
        self.PathSelectButton.setObjectName(_fromUtf8("PathSelectButton"))
        self.hboxlayout.addWidget(self.PathSelectButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.vboxlayout1.addLayout(self.hboxlayout)
        self.TextLabel2 = QtGui.QLabel(self.layoutWidget)
        self.TextLabel2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.TextLabel2.setObjectName(_fromUtf8("TextLabel2"))
        self.vboxlayout1.addWidget(self.TextLabel2)
        self.vboxlayout.addLayout(self.vboxlayout1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.GroupBox20 = QtGui.QGroupBox(self.layoutWidget)
        self.GroupBox20.setObjectName(_fromUtf8("GroupBox20"))
        self.vboxlayout3 = QtGui.QVBoxLayout(self.GroupBox20)
        self.vboxlayout3.setMargin(6)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.vboxlayout4 = QtGui.QVBoxLayout()
        self.vboxlayout4.setMargin(0)
        self.vboxlayout4.setSpacing(6)
        self.vboxlayout4.setObjectName(_fromUtf8("vboxlayout4"))
        self.CharList = QtGui.QTableView(self.GroupBox20)
        self.CharList.setShowGrid(False)
        self.CharList.setGridStyle(QtCore.Qt.NoPen)
        self.CharList.setObjectName(_fromUtf8("CharList"))
        self.vboxlayout4.addWidget(self.CharList)
        self.vboxlayout3.addLayout(self.vboxlayout4)
        self.vboxlayout2.addWidget(self.GroupBox20)
        self.TextLabel14 = QtGui.QLabel(self.layoutWidget)
        self.TextLabel14.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.TextLabel14.setWordWrap(True)
        self.TextLabel14.setObjectName(_fromUtf8("TextLabel14"))
        self.vboxlayout2.addWidget(self.TextLabel14)
        self.hboxlayout1.addLayout(self.vboxlayout2)
        self.vboxlayout5 = QtGui.QVBoxLayout()
        self.vboxlayout5.setMargin(0)
        self.vboxlayout5.setSpacing(6)
        self.vboxlayout5.setObjectName(_fromUtf8("vboxlayout5"))
        self.GroupBox19 = QtGui.QGroupBox(self.layoutWidget)
        self.GroupBox19.setObjectName(_fromUtf8("GroupBox19"))
        self.vboxlayout6 = QtGui.QVBoxLayout(self.GroupBox19)
        self.vboxlayout6.setMargin(6)
        self.vboxlayout6.setSpacing(6)
        self.vboxlayout6.setObjectName(_fromUtf8("vboxlayout6"))
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.RangedSelect = QtGui.QCheckBox(self.GroupBox19)
        self.RangedSelect.setObjectName(_fromUtf8("RangedSelect"))
        self.gridlayout.addWidget(self.RangedSelect, 3, 2, 1, 1)
        self.LegsSelect = QtGui.QCheckBox(self.GroupBox19)
        self.LegsSelect.setObjectName(_fromUtf8("LegsSelect"))
        self.gridlayout.addWidget(self.LegsSelect, 0, 1, 1, 1)
        self.FeetSelect = QtGui.QCheckBox(self.GroupBox19)
        self.FeetSelect.setObjectName(_fromUtf8("FeetSelect"))
        self.gridlayout.addWidget(self.FeetSelect, 2, 1, 1, 1)
        self.LHSelect = QtGui.QCheckBox(self.GroupBox19)
        self.LHSelect.setObjectName(_fromUtf8("LHSelect"))
        self.gridlayout.addWidget(self.LHSelect, 1, 2, 1, 1)
        self.HeadSelect = QtGui.QCheckBox(self.GroupBox19)
        self.HeadSelect.setObjectName(_fromUtf8("HeadSelect"))
        self.gridlayout.addWidget(self.HeadSelect, 2, 0, 1, 1)
        self.ArmsSelect = QtGui.QCheckBox(self.GroupBox19)
        self.ArmsSelect.setObjectName(_fromUtf8("ArmsSelect"))
        self.gridlayout.addWidget(self.ArmsSelect, 1, 0, 1, 1)
        self.THSelect = QtGui.QCheckBox(self.GroupBox19)
        self.THSelect.setObjectName(_fromUtf8("THSelect"))
        self.gridlayout.addWidget(self.THSelect, 2, 2, 1, 1)
        self.ChestSelect = QtGui.QCheckBox(self.GroupBox19)
        self.ChestSelect.setObjectName(_fromUtf8("ChestSelect"))
        self.gridlayout.addWidget(self.ChestSelect, 0, 0, 1, 1)
        self.HandsSelect = QtGui.QCheckBox(self.GroupBox19)
        self.HandsSelect.setObjectName(_fromUtf8("HandsSelect"))
        self.gridlayout.addWidget(self.HandsSelect, 1, 1, 1, 1)
        self.RHSelect = QtGui.QCheckBox(self.GroupBox19)
        self.RHSelect.setObjectName(_fromUtf8("RHSelect"))
        self.gridlayout.addWidget(self.RHSelect, 0, 2, 1, 1)
        self.SpareSelect = QtGui.QCheckBox(self.GroupBox19)
        self.SpareSelect.setObjectName(_fromUtf8("SpareSelect"))
        self.gridlayout.addWidget(self.SpareSelect, 3, 1, 1, 1)
        self.vboxlayout6.addLayout(self.gridlayout)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.TextLabel7 = QtGui.QLabel(self.GroupBox19)
        self.TextLabel7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel7.setObjectName(_fromUtf8("TextLabel7"))
        self.hboxlayout2.addWidget(self.TextLabel7)
        self.HotbarNum = QtGui.QSpinBox(self.GroupBox19)
        self.HotbarNum.setMinimum(1)
        self.HotbarNum.setMaximum(3)
        self.HotbarNum.setObjectName(_fromUtf8("HotbarNum"))
        self.hboxlayout2.addWidget(self.HotbarNum)
        self.TextLabel7_2 = QtGui.QLabel(self.GroupBox19)
        self.TextLabel7_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel7_2.setObjectName(_fromUtf8("TextLabel7_2"))
        self.hboxlayout2.addWidget(self.TextLabel7_2)
        self.HotbarRow = QtGui.QSpinBox(self.GroupBox19)
        self.HotbarRow.setMinimum(1)
        self.HotbarRow.setMaximum(10)
        self.HotbarRow.setObjectName(_fromUtf8("HotbarRow"))
        self.hboxlayout2.addWidget(self.HotbarRow)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem2)
        self.vboxlayout6.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setMargin(0)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.TextLabel8 = QtGui.QLabel(self.GroupBox19)
        self.TextLabel8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel8.setObjectName(_fromUtf8("TextLabel8"))
        self.hboxlayout3.addWidget(self.TextLabel8)
        self.HotbarPos = QtGui.QSpinBox(self.GroupBox19)
        self.HotbarPos.setMinimum(1)
        self.HotbarPos.setMaximum(10)
        self.HotbarPos.setObjectName(_fromUtf8("HotbarPos"))
        self.hboxlayout3.addWidget(self.HotbarPos)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem3)
        self.vboxlayout6.addLayout(self.hboxlayout3)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setMargin(0)
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        self.TextLabel10 = QtGui.QLabel(self.GroupBox19)
        self.TextLabel10.setObjectName(_fromUtf8("TextLabel10"))
        self.hboxlayout4.addWidget(self.TextLabel10)
        self.EndBar = QtGui.QLabel(self.GroupBox19)
        self.EndBar.setObjectName(_fromUtf8("EndBar"))
        self.hboxlayout4.addWidget(self.EndBar)
        self.TextLabel10_2 = QtGui.QLabel(self.GroupBox19)
        self.TextLabel10_2.setObjectName(_fromUtf8("TextLabel10_2"))
        self.hboxlayout4.addWidget(self.TextLabel10_2)
        self.EndRow = QtGui.QLabel(self.GroupBox19)
        self.EndRow.setObjectName(_fromUtf8("EndRow"))
        self.hboxlayout4.addWidget(self.EndRow)
        self.TextLabel11 = QtGui.QLabel(self.GroupBox19)
        self.TextLabel11.setObjectName(_fromUtf8("TextLabel11"))
        self.hboxlayout4.addWidget(self.TextLabel11)
        self.EndPos = QtGui.QLabel(self.GroupBox19)
        self.EndPos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.EndPos.setObjectName(_fromUtf8("EndPos"))
        self.hboxlayout4.addWidget(self.EndPos)
        self.vboxlayout6.addLayout(self.hboxlayout4)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setMargin(0)
        self.hboxlayout5.setSpacing(6)
        self.hboxlayout5.setObjectName(_fromUtf8("hboxlayout5"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem4)
        self.LabelNumGems = QtGui.QLabel(self.GroupBox19)
        self.LabelNumGems.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LabelNumGems.setObjectName(_fromUtf8("LabelNumGems"))
        self.hboxlayout5.addWidget(self.LabelNumGems)
        self.NumGems = QtGui.QLabel(self.GroupBox19)
        self.NumGems.setObjectName(_fromUtf8("NumGems"))
        self.hboxlayout5.addWidget(self.NumGems)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem5)
        self.vboxlayout6.addLayout(self.hboxlayout5)
        self.vboxlayout5.addWidget(self.GroupBox19)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setMargin(0)
        self.hboxlayout6.setSpacing(11)
        self.hboxlayout6.setObjectName(_fromUtf8("hboxlayout6"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem6)
        self.LoadGemsButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadGemsButton.sizePolicy().hasHeightForWidth())
        self.LoadGemsButton.setSizePolicy(sizePolicy)
        self.LoadGemsButton.setMinimumSize(QtCore.QSize(110, 0))
        self.LoadGemsButton.setObjectName(_fromUtf8("LoadGemsButton"))
        self.hboxlayout6.addWidget(self.LoadGemsButton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem7)
        self.vboxlayout5.addLayout(self.hboxlayout6)
        self.hboxlayout1.addLayout(self.vboxlayout5)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.GroupBox21 = QtGui.QGroupBox(self.layoutWidget)
        self.GroupBox21.setTitle(_fromUtf8(""))
        self.GroupBox21.setObjectName(_fromUtf8("GroupBox21"))
        self.hboxlayout7 = QtGui.QHBoxLayout(self.GroupBox21)
        self.hboxlayout7.setMargin(9)
        self.hboxlayout7.setSpacing(6)
        self.hboxlayout7.setObjectName(_fromUtf8("hboxlayout7"))
        self.TextLabel9 = QtGui.QLabel(self.GroupBox21)
        self.TextLabel9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TextLabel9.setWordWrap(True)
        self.TextLabel9.setObjectName(_fromUtf8("TextLabel9"))
        self.hboxlayout7.addWidget(self.TextLabel9)
        self.vboxlayout.addWidget(self.GroupBox21)
        self.hboxlayout8 = QtGui.QHBoxLayout()
        self.hboxlayout8.setMargin(0)
        self.hboxlayout8.setSpacing(6)
        self.hboxlayout8.setObjectName(_fromUtf8("hboxlayout8"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout8.addItem(spacerItem8)
        self.PushButton19 = QtGui.QPushButton(self.layoutWidget)
        self.PushButton19.setObjectName(_fromUtf8("PushButton19"))
        self.hboxlayout8.addWidget(self.PushButton19)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout8.addItem(spacerItem9)
        self.vboxlayout.addLayout(self.hboxlayout8)

        self.retranslateUi(B_CraftBar)
        self.PushButton19.clicked.connect(B_CraftBar.accept)
        QtCore.QMetaObject.connectSlotsByName(B_CraftBar)
        B_CraftBar.setTabOrder(self.DaocPath, self.PathSelectButton)
        B_CraftBar.setTabOrder(self.PathSelectButton, self.CharList)
        B_CraftBar.setTabOrder(self.CharList, self.ChestSelect)
        B_CraftBar.setTabOrder(self.ChestSelect, self.ArmsSelect)
        B_CraftBar.setTabOrder(self.ArmsSelect, self.HeadSelect)
        B_CraftBar.setTabOrder(self.HeadSelect, self.LegsSelect)
        B_CraftBar.setTabOrder(self.LegsSelect, self.HandsSelect)
        B_CraftBar.setTabOrder(self.HandsSelect, self.FeetSelect)
        B_CraftBar.setTabOrder(self.FeetSelect, self.SpareSelect)
        B_CraftBar.setTabOrder(self.SpareSelect, self.RHSelect)
        B_CraftBar.setTabOrder(self.RHSelect, self.LHSelect)
        B_CraftBar.setTabOrder(self.LHSelect, self.THSelect)
        B_CraftBar.setTabOrder(self.THSelect, self.RangedSelect)
        B_CraftBar.setTabOrder(self.RangedSelect, self.HotbarNum)
        B_CraftBar.setTabOrder(self.HotbarNum, self.HotbarRow)
        B_CraftBar.setTabOrder(self.HotbarRow, self.HotbarPos)
        B_CraftBar.setTabOrder(self.HotbarPos, self.LoadGemsButton)
        B_CraftBar.setTabOrder(self.LoadGemsButton, self.PushButton19)

    def retranslateUi(self, B_CraftBar):
        B_CraftBar.setWindowTitle(_translate("B_CraftBar", "Craft Bar Setup", None))
        self.TextLabel1.setText(_translate("B_CraftBar", "Path to DAoC Folder:", None))
        self.PathSelectButton.setText(_translate("B_CraftBar", "...", None))
        self.TextLabel2.setText(_translate("B_CraftBar", "(i.e. C:\\Mythic\\[Atlantis, Camelot, Isles])", None))
        self.GroupBox20.setTitle(_translate("B_CraftBar", "Crafter to Load", None))
        self.TextLabel14.setText(_translate("B_CraftBar", "You must be logged out of the selected \n"
            "character for the changes to take effect.", None))
        self.GroupBox19.setTitle(_translate("B_CraftBar", "Gems To Load", None))
        self.RangedSelect.setText(_translate("B_CraftBar", "Ranged", None))
        self.LegsSelect.setText(_translate("B_CraftBar", "Legs", None))
        self.FeetSelect.setText(_translate("B_CraftBar", "Feet", None))
        self.LHSelect.setText(_translate("B_CraftBar", "Left Hand", None))
        self.HeadSelect.setText(_translate("B_CraftBar", "Head", None))
        self.ArmsSelect.setText(_translate("B_CraftBar", "Arms", None))
        self.THSelect.setText(_translate("B_CraftBar", "2 Handed", None))
        self.ChestSelect.setText(_translate("B_CraftBar", "Chest", None))
        self.HandsSelect.setText(_translate("B_CraftBar", "Hands", None))
        self.RHSelect.setText(_translate("B_CraftBar", "Right Hand", None))
        self.SpareSelect.setText(_translate("B_CraftBar", "Spare", None))
        self.TextLabel7.setText(_translate("B_CraftBar", "Hotbar to Start At:", None))
        self.TextLabel7_2.setText(_translate("B_CraftBar", " Row:", None))
        self.TextLabel8.setText(_translate("B_CraftBar", "Hotbar Position to Start At:", None))
        self.TextLabel10.setText(_translate("B_CraftBar", "Ending Bar:", None))
        self.EndBar.setText(_translate("B_CraftBar", "0", None))
        self.TextLabel10_2.setText(_translate("B_CraftBar", "Row:", None))
        self.EndRow.setText(_translate("B_CraftBar", "0", None))
        self.TextLabel11.setText(_translate("B_CraftBar", "Position:", None))
        self.EndPos.setText(_translate("B_CraftBar", "0", None))
        self.LabelNumGems.setText(_translate("B_CraftBar", "Total Number of Gems to Load:", None))
        self.NumGems.setText(_translate("B_CraftBar", "0", None))
        self.LoadGemsButton.setText(_translate("B_CraftBar", "Load Gems", None))
        self.TextLabel9.setText(_translate("B_CraftBar", "This dialog lets you automatically set up hotbars for crafting gems. It takes all \"non-finished\" gems and places them in order on your hotbars starting at the bar and position you specify. It will place all the gems consecutively, so make sure you do not have anything on your bars in that range. If you do not leave enough space, it will error w/o changing your bars. A backup copy of your character will be saved as [charname]-[server].ini.bak in your DAoC folder.  Replacing the file with the .bak copy will restore your settings.", None))
        self.PushButton19.setText(_translate("B_CraftBar", "Close", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    B_CraftBar = QtGui.QDialog()
    ui = Ui_B_CraftBar()
    ui.setupUi(B_CraftBar)
    B_CraftBar.show()
    sys.exit(app.exec_())

