# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CraftWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_B_CraftWindow(object):
    def setupUi(self, B_CraftWindow):
        B_CraftWindow.setObjectName(_fromUtf8("B_CraftWindow"))
        B_CraftWindow.resize(525, 509)
        self.hboxlayout = QtGui.QHBoxLayout(B_CraftWindow)
        self.hboxlayout.setMargin(9)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.GroupBox1 = QtGui.QGroupBox(B_CraftWindow)
        self.GroupBox1.setObjectName(_fromUtf8("GroupBox1"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.GroupBox1)
        self.vboxlayout1.setMargin(9)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(3)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.GemNameLabel = QtGui.QLabel(self.GroupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GemNameLabel.sizePolicy().hasHeightForWidth())
        self.GemNameLabel.setSizePolicy(sizePolicy)
        self.GemNameLabel.setObjectName(_fromUtf8("GemNameLabel"))
        self.gridlayout.addWidget(self.GemNameLabel, 0, 0, 1, 1)
        self.GemMakesLabel = QtGui.QLabel(self.GroupBox1)
        self.GemMakesLabel.setObjectName(_fromUtf8("GemMakesLabel"))
        self.gridlayout.addWidget(self.GemMakesLabel, 0, 1, 1, 1)
        self.GemCostLabel = QtGui.QLabel(self.GroupBox1)
        self.GemCostLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.GemCostLabel.setObjectName(_fromUtf8("GemCostLabel"))
        self.gridlayout.addWidget(self.GemCostLabel, 0, 2, 1, 1)
        self.Gem1Name = QtGui.QLabel(self.GroupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gem1Name.sizePolicy().hasHeightForWidth())
        self.Gem1Name.setSizePolicy(sizePolicy)
        self.Gem1Name.setObjectName(_fromUtf8("Gem1Name"))
        self.gridlayout.addWidget(self.Gem1Name, 1, 0, 1, 1)
        self.Gem1Makes = QtGui.QSpinBox(self.GroupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gem1Makes.sizePolicy().hasHeightForWidth())
        self.Gem1Makes.setSizePolicy(sizePolicy)
        self.Gem1Makes.setObjectName(_fromUtf8("Gem1Makes"))
        self.gridlayout.addWidget(self.Gem1Makes, 1, 1, 1, 1)
        self.Gem1Cost = QtGui.QLabel(self.GroupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gem1Cost.sizePolicy().hasHeightForWidth())
        self.Gem1Cost.setSizePolicy(sizePolicy)
        self.Gem1Cost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Gem1Cost.setObjectName(_fromUtf8("Gem1Cost"))
        self.gridlayout.addWidget(self.Gem1Cost, 1, 2, 1, 1)
        self.Gem2Name = QtGui.QLabel(self.GroupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gem2Name.sizePolicy().hasHeightForWidth())
        self.Gem2Name.setSizePolicy(sizePolicy)
        self.Gem2Name.setObjectName(_fromUtf8("Gem2Name"))
        self.gridlayout.addWidget(self.Gem2Name, 2, 0, 1, 1)
        self.Gem2Makes = QtGui.QSpinBox(self.GroupBox1)
        self.Gem2Makes.setObjectName(_fromUtf8("Gem2Makes"))
        self.gridlayout.addWidget(self.Gem2Makes, 2, 1, 1, 1)
        self.Gem2Cost = QtGui.QLabel(self.GroupBox1)
        self.Gem2Cost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Gem2Cost.setObjectName(_fromUtf8("Gem2Cost"))
        self.gridlayout.addWidget(self.Gem2Cost, 2, 2, 1, 1)
        self.Gem3Name = QtGui.QLabel(self.GroupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gem3Name.sizePolicy().hasHeightForWidth())
        self.Gem3Name.setSizePolicy(sizePolicy)
        self.Gem3Name.setObjectName(_fromUtf8("Gem3Name"))
        self.gridlayout.addWidget(self.Gem3Name, 3, 0, 1, 1)
        self.Gem3Makes = QtGui.QSpinBox(self.GroupBox1)
        self.Gem3Makes.setObjectName(_fromUtf8("Gem3Makes"))
        self.gridlayout.addWidget(self.Gem3Makes, 3, 1, 1, 1)
        self.Gem3Cost = QtGui.QLabel(self.GroupBox1)
        self.Gem3Cost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Gem3Cost.setObjectName(_fromUtf8("Gem3Cost"))
        self.gridlayout.addWidget(self.Gem3Cost, 3, 2, 1, 1)
        self.Gem4Name = QtGui.QLabel(self.GroupBox1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gem4Name.sizePolicy().hasHeightForWidth())
        self.Gem4Name.setSizePolicy(sizePolicy)
        self.Gem4Name.setObjectName(_fromUtf8("Gem4Name"))
        self.gridlayout.addWidget(self.Gem4Name, 4, 0, 1, 1)
        self.Gem4Makes = QtGui.QSpinBox(self.GroupBox1)
        self.Gem4Makes.setObjectName(_fromUtf8("Gem4Makes"))
        self.gridlayout.addWidget(self.Gem4Makes, 4, 1, 1, 1)
        self.Gem4Cost = QtGui.QLabel(self.GroupBox1)
        self.Gem4Cost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Gem4Cost.setObjectName(_fromUtf8("Gem4Cost"))
        self.gridlayout.addWidget(self.Gem4Cost, 4, 2, 1, 1)
        self.vboxlayout2.addLayout(self.gridlayout)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.GroupBox2_2 = QtGui.QGroupBox(self.GroupBox1)
        self.GroupBox2_2.setObjectName(_fromUtf8("GroupBox2_2"))
        self.vboxlayout3 = QtGui.QVBoxLayout(self.GroupBox2_2)
        self.vboxlayout3.setMargin(9)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.MatsUsed = QtGui.QTextEdit(self.GroupBox2_2)
        self.MatsUsed.setObjectName(_fromUtf8("MatsUsed"))
        self.vboxlayout3.addWidget(self.MatsUsed)
        self.hboxlayout1.addWidget(self.GroupBox2_2)
        self.GroupBox2_2_2 = QtGui.QGroupBox(self.GroupBox1)
        self.GroupBox2_2_2.setObjectName(_fromUtf8("GroupBox2_2_2"))
        self.vboxlayout4 = QtGui.QVBoxLayout(self.GroupBox2_2_2)
        self.vboxlayout4.setMargin(9)
        self.vboxlayout4.setSpacing(6)
        self.vboxlayout4.setObjectName(_fromUtf8("vboxlayout4"))
        self.MatsExpected = QtGui.QTextEdit(self.GroupBox2_2_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MatsExpected.sizePolicy().hasHeightForWidth())
        self.MatsExpected.setSizePolicy(sizePolicy)
        self.MatsExpected.setObjectName(_fromUtf8("MatsExpected"))
        self.vboxlayout4.addWidget(self.MatsExpected)
        self.hboxlayout1.addWidget(self.GroupBox2_2_2)
        self.vboxlayout2.addLayout(self.hboxlayout1)
        self.vboxlayout1.addLayout(self.vboxlayout2)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setMargin(0)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.TextLabel8 = QtGui.QLabel(self.GroupBox1)
        self.TextLabel8.setObjectName(_fromUtf8("TextLabel8"))
        self.hboxlayout3.addWidget(self.TextLabel8)
        self.TotalCost = QtGui.QLabel(self.GroupBox1)
        self.TotalCost.setObjectName(_fromUtf8("TotalCost"))
        self.hboxlayout3.addWidget(self.TotalCost)
        self.hboxlayout2.addLayout(self.hboxlayout3)
        self.vboxlayout1.addLayout(self.hboxlayout2)
        self.vboxlayout.addWidget(self.GroupBox1)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setMargin(0)
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        spacerItem = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem)
        self.Close = QtGui.QPushButton(B_CraftWindow)
        self.Close.setObjectName(_fromUtf8("Close"))
        self.hboxlayout4.addWidget(self.Close)
        spacerItem1 = QtGui.QSpacerItem(102, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem1)
        self.vboxlayout.addLayout(self.hboxlayout4)
        self.hboxlayout.addLayout(self.vboxlayout)

        self.retranslateUi(B_CraftWindow)
        QtCore.QMetaObject.connectSlotsByName(B_CraftWindow)

    def retranslateUi(self, B_CraftWindow):
        B_CraftWindow.setWindowTitle(_translate("B_CraftWindow", "Working Item Detail", None))
        self.GroupBox1.setTitle(_translate("B_CraftWindow", "Gems", None))
        self.GemNameLabel.setText(_translate("B_CraftWindow", "Name:", None))
        self.GemMakesLabel.setText(_translate("B_CraftWindow", "Makes:", None))
        self.GemCostLabel.setText(_translate("B_CraftWindow", "Cost:", None))
        self.Gem1Name.setText(_translate("B_CraftWindow", "None", None))
        self.Gem1Cost.setText(_translate("B_CraftWindow", "0c", None))
        self.Gem2Name.setText(_translate("B_CraftWindow", "None", None))
        self.Gem2Cost.setText(_translate("B_CraftWindow", "0c", None))
        self.Gem3Name.setText(_translate("B_CraftWindow", "None", None))
        self.Gem3Cost.setText(_translate("B_CraftWindow", "0c", None))
        self.Gem4Name.setText(_translate("B_CraftWindow", "None", None))
        self.Gem4Cost.setText(_translate("B_CraftWindow", "0c", None))
        self.GroupBox2_2.setTitle(_translate("B_CraftWindow", "Materials (used)", None))
        self.GroupBox2_2_2.setTitle(_translate("B_CraftWindow", "Materials (one make)", None))
        self.TextLabel8.setText(_translate("B_CraftWindow", "Total Cost:", None))
        self.TotalCost.setText(_translate("B_CraftWindow", "0c", None))
        self.Close.setText(_translate("B_CraftWindow", "Close", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    B_CraftWindow = QtGui.QDialog()
    ui = Ui_B_CraftWindow()
    ui.setupUi(B_CraftWindow)
    B_CraftWindow.show()
    sys.exit(app.exec_())

