# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CraftWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_B_CraftWindow(object):
    def setupUi(self, B_CraftWindow):
        B_CraftWindow.setObjectName("B_CraftWindow")
        B_CraftWindow.resize(525, 509)
        self.hboxlayout = QtWidgets.QHBoxLayout(B_CraftWindow)
        self.hboxlayout.setContentsMargins(9, 9, 9, 9)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.GroupBox1 = QtWidgets.QGroupBox(B_CraftWindow)
        self.GroupBox1.setObjectName("GroupBox1")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.GroupBox1)
        self.vboxlayout1.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.vboxlayout2 = QtWidgets.QVBoxLayout()
        self.vboxlayout2.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setContentsMargins(0, 0, 0, 0)
        self.gridlayout.setSpacing(3)
        self.gridlayout.setObjectName("gridlayout")
        self.GemNameLabel = QtWidgets.QLabel(self.GroupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GemNameLabel.sizePolicy().hasHeightForWidth())
        self.GemNameLabel.setSizePolicy(sizePolicy)
        self.GemNameLabel.setObjectName("GemNameLabel")
        self.gridlayout.addWidget(self.GemNameLabel, 0, 0, 1, 1)
        self.GemMakesLabel = QtWidgets.QLabel(self.GroupBox1)
        self.GemMakesLabel.setObjectName("GemMakesLabel")
        self.gridlayout.addWidget(self.GemMakesLabel, 0, 1, 1, 1)
        self.GemCostLabel = QtWidgets.QLabel(self.GroupBox1)
        self.GemCostLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.GemCostLabel.setObjectName("GemCostLabel")
        self.gridlayout.addWidget(self.GemCostLabel, 0, 2, 1, 1)
        self.Gem1Name = QtWidgets.QLabel(self.GroupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gem1Name.sizePolicy().hasHeightForWidth())
        self.Gem1Name.setSizePolicy(sizePolicy)
        self.Gem1Name.setObjectName("Gem1Name")
        self.gridlayout.addWidget(self.Gem1Name, 1, 0, 1, 1)
        self.Gem1Makes = QtWidgets.QSpinBox(self.GroupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gem1Makes.sizePolicy().hasHeightForWidth())
        self.Gem1Makes.setSizePolicy(sizePolicy)
        self.Gem1Makes.setObjectName("Gem1Makes")
        self.gridlayout.addWidget(self.Gem1Makes, 1, 1, 1, 1)
        self.Gem1Cost = QtWidgets.QLabel(self.GroupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gem1Cost.sizePolicy().hasHeightForWidth())
        self.Gem1Cost.setSizePolicy(sizePolicy)
        self.Gem1Cost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Gem1Cost.setObjectName("Gem1Cost")
        self.gridlayout.addWidget(self.Gem1Cost, 1, 2, 1, 1)
        self.Gem2Name = QtWidgets.QLabel(self.GroupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gem2Name.sizePolicy().hasHeightForWidth())
        self.Gem2Name.setSizePolicy(sizePolicy)
        self.Gem2Name.setObjectName("Gem2Name")
        self.gridlayout.addWidget(self.Gem2Name, 2, 0, 1, 1)
        self.Gem2Makes = QtWidgets.QSpinBox(self.GroupBox1)
        self.Gem2Makes.setObjectName("Gem2Makes")
        self.gridlayout.addWidget(self.Gem2Makes, 2, 1, 1, 1)
        self.Gem2Cost = QtWidgets.QLabel(self.GroupBox1)
        self.Gem2Cost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Gem2Cost.setObjectName("Gem2Cost")
        self.gridlayout.addWidget(self.Gem2Cost, 2, 2, 1, 1)
        self.Gem3Name = QtWidgets.QLabel(self.GroupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gem3Name.sizePolicy().hasHeightForWidth())
        self.Gem3Name.setSizePolicy(sizePolicy)
        self.Gem3Name.setObjectName("Gem3Name")
        self.gridlayout.addWidget(self.Gem3Name, 3, 0, 1, 1)
        self.Gem3Makes = QtWidgets.QSpinBox(self.GroupBox1)
        self.Gem3Makes.setObjectName("Gem3Makes")
        self.gridlayout.addWidget(self.Gem3Makes, 3, 1, 1, 1)
        self.Gem3Cost = QtWidgets.QLabel(self.GroupBox1)
        self.Gem3Cost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Gem3Cost.setObjectName("Gem3Cost")
        self.gridlayout.addWidget(self.Gem3Cost, 3, 2, 1, 1)
        self.Gem4Name = QtWidgets.QLabel(self.GroupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gem4Name.sizePolicy().hasHeightForWidth())
        self.Gem4Name.setSizePolicy(sizePolicy)
        self.Gem4Name.setObjectName("Gem4Name")
        self.gridlayout.addWidget(self.Gem4Name, 4, 0, 1, 1)
        self.Gem4Makes = QtWidgets.QSpinBox(self.GroupBox1)
        self.Gem4Makes.setObjectName("Gem4Makes")
        self.gridlayout.addWidget(self.Gem4Makes, 4, 1, 1, 1)
        self.Gem4Cost = QtWidgets.QLabel(self.GroupBox1)
        self.Gem4Cost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Gem4Cost.setObjectName("Gem4Cost")
        self.gridlayout.addWidget(self.Gem4Cost, 4, 2, 1, 1)
        self.vboxlayout2.addLayout(self.gridlayout)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.GroupBox2_2 = QtWidgets.QGroupBox(self.GroupBox1)
        self.GroupBox2_2.setObjectName("GroupBox2_2")
        self.vboxlayout3 = QtWidgets.QVBoxLayout(self.GroupBox2_2)
        self.vboxlayout3.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.MatsUsed = QtWidgets.QTextEdit(self.GroupBox2_2)
        self.MatsUsed.setObjectName("MatsUsed")
        self.vboxlayout3.addWidget(self.MatsUsed)
        self.hboxlayout1.addWidget(self.GroupBox2_2)
        self.GroupBox2_2_2 = QtWidgets.QGroupBox(self.GroupBox1)
        self.GroupBox2_2_2.setObjectName("GroupBox2_2_2")
        self.vboxlayout4 = QtWidgets.QVBoxLayout(self.GroupBox2_2_2)
        self.vboxlayout4.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout4.setSpacing(6)
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.MatsExpected = QtWidgets.QTextEdit(self.GroupBox2_2_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MatsExpected.sizePolicy().hasHeightForWidth())
        self.MatsExpected.setSizePolicy(sizePolicy)
        self.MatsExpected.setObjectName("MatsExpected")
        self.vboxlayout4.addWidget(self.MatsExpected)
        self.hboxlayout1.addWidget(self.GroupBox2_2_2)
        self.vboxlayout2.addLayout(self.hboxlayout1)
        self.vboxlayout1.addLayout(self.vboxlayout2)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.hboxlayout3 = QtWidgets.QHBoxLayout()
        self.hboxlayout3.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.TextLabel8 = QtWidgets.QLabel(self.GroupBox1)
        self.TextLabel8.setObjectName("TextLabel8")
        self.hboxlayout3.addWidget(self.TextLabel8)
        self.TotalCost = QtWidgets.QLabel(self.GroupBox1)
        self.TotalCost.setObjectName("TotalCost")
        self.hboxlayout3.addWidget(self.TotalCost)
        self.hboxlayout2.addLayout(self.hboxlayout3)
        self.vboxlayout1.addLayout(self.hboxlayout2)
        self.vboxlayout.addWidget(self.GroupBox1)
        self.hboxlayout4 = QtWidgets.QHBoxLayout()
        self.hboxlayout4.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setObjectName("hboxlayout4")
        spacerItem = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem)
        self.Close = QtWidgets.QPushButton(B_CraftWindow)
        self.Close.setObjectName("Close")
        self.hboxlayout4.addWidget(self.Close)
        spacerItem1 = QtWidgets.QSpacerItem(102, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem1)
        self.vboxlayout.addLayout(self.hboxlayout4)
        self.hboxlayout.addLayout(self.vboxlayout)

        self.retranslateUi(B_CraftWindow)
        QtCore.QMetaObject.connectSlotsByName(B_CraftWindow)

    def retranslateUi(self, B_CraftWindow):
        _translate = QtCore.QCoreApplication.translate
        B_CraftWindow.setWindowTitle(_translate("B_CraftWindow", "Working Item Detail"))
        self.GroupBox1.setTitle(_translate("B_CraftWindow", "Gems"))
        self.GemNameLabel.setText(_translate("B_CraftWindow", "Name:"))
        self.GemMakesLabel.setText(_translate("B_CraftWindow", "Makes:"))
        self.GemCostLabel.setText(_translate("B_CraftWindow", "Cost:"))
        self.Gem1Name.setText(_translate("B_CraftWindow", "None"))
        self.Gem1Cost.setText(_translate("B_CraftWindow", "0c"))
        self.Gem2Name.setText(_translate("B_CraftWindow", "None"))
        self.Gem2Cost.setText(_translate("B_CraftWindow", "0c"))
        self.Gem3Name.setText(_translate("B_CraftWindow", "None"))
        self.Gem3Cost.setText(_translate("B_CraftWindow", "0c"))
        self.Gem4Name.setText(_translate("B_CraftWindow", "None"))
        self.Gem4Cost.setText(_translate("B_CraftWindow", "0c"))
        self.GroupBox2_2.setTitle(_translate("B_CraftWindow", "Materials (used)"))
        self.GroupBox2_2_2.setTitle(_translate("B_CraftWindow", "Materials (one make)"))
        self.TextLabel8.setText(_translate("B_CraftWindow", "Total Cost:"))
        self.TotalCost.setText(_translate("B_CraftWindow", "0c"))
        self.Close.setText(_translate("B_CraftWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    B_CraftWindow = QtWidgets.QDialog()
    ui = Ui_B_CraftWindow()
    ui.setupUi(B_CraftWindow)
    B_CraftWindow.show()
    sys.exit(app.exec_())

