# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Options.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_B_Options(object):
    def setupUi(self, B_Options):
        B_Options.setObjectName("B_Options")
        B_Options.resize(627, 530)
        self.vboxlayout = QtWidgets.QVBoxLayout(B_Options)
        self.vboxlayout.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.vboxlayout1 = QtWidgets.QVBoxLayout()
        self.vboxlayout1.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.Tab = QtWidgets.QTabWidget(B_Options)
        self.Tab.setEnabled(True)
        self.Tab.setObjectName("Tab")
        self.General = QtWidgets.QWidget()
        self.General.setObjectName("General")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.General)
        self.vboxlayout2.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.vboxlayout3 = QtWidgets.QVBoxLayout()
        self.vboxlayout3.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.TextLabel1 = QtWidgets.QLabel(self.General)
        self.TextLabel1.setObjectName("TextLabel1")
        self.hboxlayout.addWidget(self.TextLabel1)
        self.Skill = QtWidgets.QComboBox(self.General)
        self.Skill.setObjectName("Skill")
        self.hboxlayout.addWidget(self.Skill)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.vboxlayout3.addLayout(self.hboxlayout)
        self.CapDistance = QtWidgets.QCheckBox(self.General)
        self.CapDistance.setObjectName("CapDistance")
        self.vboxlayout3.addWidget(self.CapDistance)
        self.ShowDoneGems = QtWidgets.QCheckBox(self.General)
        self.ShowDoneGems.setObjectName("ShowDoneGems")
        self.vboxlayout3.addWidget(self.ShowDoneGems)
        self.ShowScrollingSlots = QtWidgets.QCheckBox(self.General)
        self.ShowScrollingSlots.setObjectName("ShowScrollingSlots")
        self.vboxlayout3.addWidget(self.ShowScrollingSlots)
        self.EuroServers = QtWidgets.QCheckBox(self.General)
        self.EuroServers.setChecked(True)
        self.EuroServers.setObjectName("EuroServers")
        self.vboxlayout3.addWidget(self.EuroServers)
        self.IncludeRR = QtWidgets.QCheckBox(self.General)
        self.IncludeRR.setChecked(True)
        self.IncludeRR.setObjectName("IncludeRR")
        self.vboxlayout3.addWidget(self.IncludeRR)
        self.HideNonClassSkills = QtWidgets.QCheckBox(self.General)
        self.HideNonClassSkills.setChecked(True)
        self.HideNonClassSkills.setObjectName("HideNonClassSkills")
        self.vboxlayout3.addWidget(self.HideNonClassSkills)
        self.Coop = QtWidgets.QCheckBox(self.General)
        self.Coop.setObjectName("Coop")
        self.vboxlayout3.addWidget(self.Coop)
        self.TextLabel2_5 = QtWidgets.QLabel(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel2_5.sizePolicy().hasHeightForWidth())
        self.TextLabel2_5.setSizePolicy(sizePolicy)
        self.TextLabel2_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TextLabel2_5.setObjectName("TextLabel2_5")
        self.vboxlayout3.addWidget(self.TextLabel2_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem1)
        self.vboxlayout2.addLayout(self.vboxlayout3)
        self.Tab.addTab(self.General, "")
        self.Price = QtWidgets.QWidget()
        self.Price.setObjectName("Price")
        self.vboxlayout4 = QtWidgets.QVBoxLayout(self.Price)
        self.vboxlayout4.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout4.setSpacing(6)
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.vboxlayout5 = QtWidgets.QVBoxLayout()
        self.vboxlayout5.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout5.setSpacing(6)
        self.vboxlayout5.setObjectName("vboxlayout5")
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vboxlayout6 = QtWidgets.QVBoxLayout()
        self.vboxlayout6.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout6.setSpacing(6)
        self.vboxlayout6.setObjectName("vboxlayout6")
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.GroupBox1 = QtWidgets.QGroupBox(self.Price)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox1.sizePolicy().hasHeightForWidth())
        self.GroupBox1.setSizePolicy(sizePolicy)
        self.GroupBox1.setObjectName("GroupBox1")
        self.hboxlayout3 = QtWidgets.QHBoxLayout(self.GroupBox1)
        self.hboxlayout3.setContentsMargins(9, 9, 9, 9)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.vboxlayout7 = QtWidgets.QVBoxLayout()
        self.vboxlayout7.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout7.setSpacing(6)
        self.vboxlayout7.setObjectName("vboxlayout7")
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setContentsMargins(0, 0, 0, 0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.PPGem = QtWidgets.QLineEdit(self.GroupBox1)
        self.PPGem.setObjectName("PPGem")
        self.gridlayout.addWidget(self.PPGem, 0, 1, 1, 1)
        self.TextLabel1_2 = QtWidgets.QLabel(self.GroupBox1)
        self.TextLabel1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel1_2.setObjectName("TextLabel1_2")
        self.gridlayout.addWidget(self.TextLabel1_2, 0, 0, 1, 1)
        self.PPOrder = QtWidgets.QLineEdit(self.GroupBox1)
        self.PPOrder.setObjectName("PPOrder")
        self.gridlayout.addWidget(self.PPOrder, 2, 1, 1, 1)
        self.TextLabel1_2_2 = QtWidgets.QLabel(self.GroupBox1)
        self.TextLabel1_2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel1_2_2.setObjectName("TextLabel1_2_2")
        self.gridlayout.addWidget(self.TextLabel1_2_2, 1, 0, 1, 1)
        self.TextLabel1_2_3 = QtWidgets.QLabel(self.GroupBox1)
        self.TextLabel1_2_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel1_2_3.setObjectName("TextLabel1_2_3")
        self.gridlayout.addWidget(self.TextLabel1_2_3, 2, 0, 1, 1)
        self.PPItem = QtWidgets.QLineEdit(self.GroupBox1)
        self.PPItem.setObjectName("PPItem")
        self.gridlayout.addWidget(self.PPItem, 1, 1, 1, 1)
        self.vboxlayout7.addLayout(self.gridlayout)
        self.TextLabel2_3 = QtWidgets.QLabel(self.GroupBox1)
        self.TextLabel2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.TextLabel2_3.setObjectName("TextLabel2_3")
        self.vboxlayout7.addWidget(self.TextLabel2_3)
        self.hboxlayout3.addLayout(self.vboxlayout7)
        self.hboxlayout2.addWidget(self.GroupBox1)
        self.vboxlayout8 = QtWidgets.QVBoxLayout()
        self.vboxlayout8.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout8.setSpacing(6)
        self.vboxlayout8.setObjectName("vboxlayout8")
        self.GroupBox6 = QtWidgets.QGroupBox(self.Price)
        self.GroupBox6.setObjectName("GroupBox6")
        self.vboxlayout9 = QtWidgets.QVBoxLayout(self.GroupBox6)
        self.vboxlayout9.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout9.setSpacing(6)
        self.vboxlayout9.setObjectName("vboxlayout9")
        self.vboxlayout10 = QtWidgets.QVBoxLayout()
        self.vboxlayout10.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout10.setSpacing(6)
        self.vboxlayout10.setObjectName("vboxlayout10")
        self.HourPrice = QtWidgets.QLineEdit(self.GroupBox6)
        self.HourPrice.setObjectName("HourPrice")
        self.vboxlayout10.addWidget(self.HourPrice)
        self.HourInclude = QtWidgets.QCheckBox(self.GroupBox6)
        self.HourInclude.setObjectName("HourInclude")
        self.vboxlayout10.addWidget(self.HourInclude)
        self.vboxlayout9.addLayout(self.vboxlayout10)
        self.vboxlayout8.addWidget(self.GroupBox6)
        self.GroupBox4 = QtWidgets.QGroupBox(self.Price)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox4.sizePolicy().hasHeightForWidth())
        self.GroupBox4.setSizePolicy(sizePolicy)
        self.GroupBox4.setObjectName("GroupBox4")
        self.vboxlayout11 = QtWidgets.QVBoxLayout(self.GroupBox4)
        self.vboxlayout11.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout11.setSpacing(6)
        self.vboxlayout11.setObjectName("vboxlayout11")
        self.vboxlayout12 = QtWidgets.QVBoxLayout()
        self.vboxlayout12.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout12.setSpacing(6)
        self.vboxlayout12.setObjectName("vboxlayout12")
        self.hboxlayout4 = QtWidgets.QHBoxLayout()
        self.hboxlayout4.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.GenMarkup = QtWidgets.QLineEdit(self.GroupBox4)
        self.GenMarkup.setObjectName("GenMarkup")
        self.hboxlayout4.addWidget(self.GenMarkup)
        self.TextLabel11 = QtWidgets.QLabel(self.GroupBox4)
        self.TextLabel11.setObjectName("TextLabel11")
        self.hboxlayout4.addWidget(self.TextLabel11)
        self.vboxlayout12.addLayout(self.hboxlayout4)
        self.TextLabel12 = QtWidgets.QLabel(self.GroupBox4)
        self.TextLabel12.setObjectName("TextLabel12")
        self.vboxlayout12.addWidget(self.TextLabel12)
        self.vboxlayout11.addLayout(self.vboxlayout12)
        self.vboxlayout8.addWidget(self.GroupBox4)
        self.hboxlayout2.addLayout(self.vboxlayout8)
        self.vboxlayout6.addLayout(self.hboxlayout2)
        self.GroupBox3 = QtWidgets.QGroupBox(self.Price)
        self.GroupBox3.setObjectName("GroupBox3")
        self.vboxlayout13 = QtWidgets.QVBoxLayout(self.GroupBox3)
        self.vboxlayout13.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout13.setSpacing(6)
        self.vboxlayout13.setObjectName("vboxlayout13")
        self.gridlayout1 = QtWidgets.QGridLayout()
        self.gridlayout1.setContentsMargins(0, 0, 0, 0)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.PPInclude = QtWidgets.QCheckBox(self.GroupBox3)
        self.PPInclude.setObjectName("PPInclude")
        self.gridlayout1.addWidget(self.PPInclude, 3, 0, 1, 1)
        self.PPImbue = QtWidgets.QLineEdit(self.GroupBox3)
        self.PPImbue.setObjectName("PPImbue")
        self.gridlayout1.addWidget(self.PPImbue, 1, 0, 1, 2)
        self.TextLabel9 = QtWidgets.QLabel(self.GroupBox3)
        self.TextLabel9.setObjectName("TextLabel9")
        self.gridlayout1.addWidget(self.TextLabel9, 2, 3, 1, 2)
        self.PPOC = QtWidgets.QLineEdit(self.GroupBox3)
        self.PPOC.setObjectName("PPOC")
        self.gridlayout1.addWidget(self.PPOC, 2, 0, 1, 3)
        self.TextLabel8 = QtWidgets.QLabel(self.GroupBox3)
        self.TextLabel8.setObjectName("TextLabel8")
        self.gridlayout1.addWidget(self.TextLabel8, 1, 2, 1, 3)
        self.PPLevel = QtWidgets.QLineEdit(self.GroupBox3)
        self.PPLevel.setObjectName("PPLevel")
        self.gridlayout1.addWidget(self.PPLevel, 0, 0, 1, 4)
        self.TextLabel7 = QtWidgets.QLabel(self.GroupBox3)
        self.TextLabel7.setObjectName("TextLabel7")
        self.gridlayout1.addWidget(self.TextLabel7, 0, 4, 1, 1)
        self.TextLabel10 = QtWidgets.QLabel(self.GroupBox3)
        self.TextLabel10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel10.setObjectName("TextLabel10")
        self.gridlayout1.addWidget(self.TextLabel10, 3, 2, 1, 3)
        self.vboxlayout13.addLayout(self.gridlayout1)
        self.vboxlayout6.addWidget(self.GroupBox3)
        self.hboxlayout1.addLayout(self.vboxlayout6)
        self.GroupBox5 = QtWidgets.QGroupBox(self.Price)
        self.GroupBox5.setObjectName("GroupBox5")
        self.vboxlayout14 = QtWidgets.QVBoxLayout(self.GroupBox5)
        self.vboxlayout14.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout14.setSpacing(6)
        self.vboxlayout14.setObjectName("vboxlayout14")
        self.vboxlayout15 = QtWidgets.QVBoxLayout()
        self.vboxlayout15.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout15.setSpacing(6)
        self.vboxlayout15.setObjectName("vboxlayout15")
        self.TierPriceTable = QtWidgets.QTableWidget(self.GroupBox5)
        self.TierPriceTable.setRowCount(10)
        self.TierPriceTable.setColumnCount(2)
        self.TierPriceTable.setObjectName("TierPriceTable")
        self.vboxlayout15.addWidget(self.TierPriceTable)
        self.hboxlayout5 = QtWidgets.QHBoxLayout()
        self.hboxlayout5.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout5.setSpacing(6)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.TierInclude = QtWidgets.QCheckBox(self.GroupBox5)
        self.TierInclude.setObjectName("TierInclude")
        self.hboxlayout5.addWidget(self.TierInclude)
        self.TextLabel15 = QtWidgets.QLabel(self.GroupBox5)
        self.TextLabel15.setObjectName("TextLabel15")
        self.hboxlayout5.addWidget(self.TextLabel15)
        self.vboxlayout15.addLayout(self.hboxlayout5)
        self.vboxlayout14.addLayout(self.vboxlayout15)
        self.hboxlayout1.addWidget(self.GroupBox5)
        self.vboxlayout5.addLayout(self.hboxlayout1)
        self.hboxlayout6 = QtWidgets.QHBoxLayout()
        self.hboxlayout6.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout6.setSpacing(6)
        self.hboxlayout6.setObjectName("hboxlayout6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem2)
        self.CostInPrice = QtWidgets.QCheckBox(self.Price)
        self.CostInPrice.setChecked(True)
        self.CostInPrice.setObjectName("CostInPrice")
        self.hboxlayout6.addWidget(self.CostInPrice)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem3)
        self.vboxlayout5.addLayout(self.hboxlayout6)
        self.hboxlayout7 = QtWidgets.QHBoxLayout()
        self.hboxlayout7.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout7.setSpacing(6)
        self.hboxlayout7.setObjectName("hboxlayout7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout7.addItem(spacerItem4)
        self.TextLabel2_4 = QtWidgets.QLabel(self.Price)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel2_4.sizePolicy().hasHeightForWidth())
        self.TextLabel2_4.setSizePolicy(sizePolicy)
        self.TextLabel2_4.setObjectName("TextLabel2_4")
        self.hboxlayout7.addWidget(self.TextLabel2_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout7.addItem(spacerItem5)
        self.vboxlayout5.addLayout(self.hboxlayout7)
        self.vboxlayout4.addLayout(self.vboxlayout5)
        self.Tab.addTab(self.Price, "")
        self.vboxlayout1.addWidget(self.Tab)
        self.hboxlayout8 = QtWidgets.QHBoxLayout()
        self.hboxlayout8.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout8.setSpacing(25)
        self.hboxlayout8.setObjectName("hboxlayout8")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout8.addItem(spacerItem6)
        self.OK = QtWidgets.QPushButton(B_Options)
        self.OK.setObjectName("OK")
        self.hboxlayout8.addWidget(self.OK)
        self.Cancel = QtWidgets.QPushButton(B_Options)
        self.Cancel.setObjectName("Cancel")
        self.hboxlayout8.addWidget(self.Cancel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout8.addItem(spacerItem7)
        self.vboxlayout1.addLayout(self.hboxlayout8)
        self.vboxlayout.addLayout(self.vboxlayout1)

        self.retranslateUi(B_Options)
        self.Tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(B_Options)
        B_Options.setTabOrder(self.PPGem, self.PPItem)
        B_Options.setTabOrder(self.PPItem, self.PPOrder)
        B_Options.setTabOrder(self.PPOrder, self.PPLevel)
        B_Options.setTabOrder(self.PPLevel, self.PPImbue)
        B_Options.setTabOrder(self.PPImbue, self.PPOC)
        B_Options.setTabOrder(self.PPOC, self.PPInclude)
        B_Options.setTabOrder(self.PPInclude, self.GenMarkup)
        B_Options.setTabOrder(self.GenMarkup, self.TierInclude)
        B_Options.setTabOrder(self.TierInclude, self.HourPrice)
        B_Options.setTabOrder(self.HourPrice, self.HourInclude)
        B_Options.setTabOrder(self.HourInclude, self.CostInPrice)
        B_Options.setTabOrder(self.CostInPrice, self.OK)
        B_Options.setTabOrder(self.OK, self.Cancel)
        B_Options.setTabOrder(self.Cancel, self.Skill)
        B_Options.setTabOrder(self.Skill, self.CapDistance)
        B_Options.setTabOrder(self.CapDistance, self.ShowDoneGems)
        B_Options.setTabOrder(self.ShowDoneGems, self.IncludeRR)
        B_Options.setTabOrder(self.IncludeRR, self.HideNonClassSkills)
        B_Options.setTabOrder(self.HideNonClassSkills, self.Coop)
        B_Options.setTabOrder(self.Coop, self.Tab)

    def retranslateUi(self, B_Options):
        _translate = QtCore.QCoreApplication.translate
        B_Options.setWindowTitle(_translate("B_Options", "Options"))
        self.TextLabel1.setText(_translate("B_Options", "Crafter Skill:"))
        self.CapDistance.setText(_translate("B_Options", "Show Distance To Cap (instead of total)"))
        self.ShowDoneGems.setText(_translate("B_Options", "Hide \"Made\" Gems from Materials List and Exported Gems"))
        self.ShowScrollingSlots.setText(_translate("B_Options", "Scrollable Slots (allows your window to be shorter)"))
        self.EuroServers.setText(_translate("B_Options", "Export Gems to European/GOA Servers"))
        self.IncludeRR.setText(_translate("B_Options", "Include Racial Resists in Totals"))
        self.HideNonClassSkills.setText(_translate("B_Options", "Hide Skills not usable by this Class"))
        self.Coop.setText(_translate("B_Options", "Co-op / PvP Server"))
        self.TextLabel2_5.setText(_translate("B_Options", "        (Lets you access items from all realms)"))
        self.Tab.setTabText(self.Tab.indexOf(self.General), _translate("B_Options", "General"))
        self.GroupBox1.setTitle(_translate("B_Options", "Price per"))
        self.PPGem.setText(_translate("B_Options", "0"))
        self.TextLabel1_2.setText(_translate("B_Options", "Gem:"))
        self.PPOrder.setText(_translate("B_Options", "0"))
        self.TextLabel1_2_2.setText(_translate("B_Options", "Item:"))
        self.TextLabel1_2_3.setText(_translate("B_Options", "Order:"))
        self.PPItem.setText(_translate("B_Options", "0"))
        self.TextLabel2_3.setText(_translate("B_Options", "(cost+ X)"))
        self.GroupBox6.setTitle(_translate("B_Options", "Per hour"))
        self.HourPrice.setText(_translate("B_Options", "0"))
        self.HourInclude.setText(_translate("B_Options", "Include"))
        self.GroupBox4.setTitle(_translate("B_Options", "General Markup"))
        self.GenMarkup.setText(_translate("B_Options", "50"))
        self.TextLabel11.setText(_translate("B_Options", "%"))
        self.TextLabel12.setText(_translate("B_Options", "(cost + (cost * X%))"))
        self.GroupBox3.setTitle(_translate("B_Options", "Price per lvl/point"))
        self.PPInclude.setText(_translate("B_Options", "Include"))
        self.PPImbue.setText(_translate("B_Options", "0"))
        self.TextLabel9.setText(_translate("B_Options", "per O/C pt."))
        self.PPOC.setText(_translate("B_Options", "0"))
        self.TextLabel8.setText(_translate("B_Options", "per imbue pt."))
        self.PPLevel.setText(_translate("B_Options", "0"))
        self.TextLabel7.setText(_translate("B_Options", "per level"))
        self.TextLabel10.setText(_translate("B_Options", "(cost + X)"))
        self.GroupBox5.setTitle(_translate("B_Options", "Price by Gem Tier"))
        self.TierInclude.setText(_translate("B_Options", "Include"))
        self.TextLabel15.setText(_translate("B_Options", "(cost + X)"))
        self.CostInPrice.setText(_translate("B_Options", "Include cost in price"))
        self.TextLabel2_4.setText(_translate("B_Options", "All numbers (except percentages) are in amounts of Gold."))
        self.Tab.setTabText(self.Tab.indexOf(self.Price), _translate("B_Options", "Price"))
        self.OK.setText(_translate("B_Options", "OK"))
        self.Cancel.setText(_translate("B_Options", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    B_Options = QtWidgets.QDialog()
    ui = Ui_B_Options()
    ui.setupUi(B_Options)
    B_Options.show()
    sys.exit(app.exec_())

