# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Options.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_B_Options(object):
    def setupUi(self, B_Options):
        B_Options.setObjectName(_fromUtf8("B_Options"))
        B_Options.resize(627, 530)
        self.vboxlayout = QtGui.QVBoxLayout(B_Options)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.Tab = QtGui.QTabWidget(B_Options)
        self.Tab.setEnabled(True)
        self.Tab.setObjectName(_fromUtf8("Tab"))
        self.General = QtGui.QWidget()
        self.General.setObjectName(_fromUtf8("General"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.General)
        self.vboxlayout2.setMargin(9)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setMargin(0)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.TextLabel1 = QtGui.QLabel(self.General)
        self.TextLabel1.setObjectName(_fromUtf8("TextLabel1"))
        self.hboxlayout.addWidget(self.TextLabel1)
        self.Skill = QtGui.QComboBox(self.General)
        self.Skill.setObjectName(_fromUtf8("Skill"))
        self.hboxlayout.addWidget(self.Skill)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.vboxlayout3.addLayout(self.hboxlayout)
        self.CapDistance = QtGui.QCheckBox(self.General)
        self.CapDistance.setObjectName(_fromUtf8("CapDistance"))
        self.vboxlayout3.addWidget(self.CapDistance)
        self.ShowDoneGems = QtGui.QCheckBox(self.General)
        self.ShowDoneGems.setObjectName(_fromUtf8("ShowDoneGems"))
        self.vboxlayout3.addWidget(self.ShowDoneGems)
        self.ShowScrollingSlots = QtGui.QCheckBox(self.General)
        self.ShowScrollingSlots.setObjectName(_fromUtf8("ShowScrollingSlots"))
        self.vboxlayout3.addWidget(self.ShowScrollingSlots)
        self.EuroServers = QtGui.QCheckBox(self.General)
        self.EuroServers.setChecked(True)
        self.EuroServers.setObjectName(_fromUtf8("EuroServers"))
        self.vboxlayout3.addWidget(self.EuroServers)
        self.IncludeRR = QtGui.QCheckBox(self.General)
        self.IncludeRR.setChecked(True)
        self.IncludeRR.setObjectName(_fromUtf8("IncludeRR"))
        self.vboxlayout3.addWidget(self.IncludeRR)
        self.HideNonClassSkills = QtGui.QCheckBox(self.General)
        self.HideNonClassSkills.setChecked(True)
        self.HideNonClassSkills.setObjectName(_fromUtf8("HideNonClassSkills"))
        self.vboxlayout3.addWidget(self.HideNonClassSkills)
        self.Coop = QtGui.QCheckBox(self.General)
        self.Coop.setObjectName(_fromUtf8("Coop"))
        self.vboxlayout3.addWidget(self.Coop)
        self.TextLabel2_5 = QtGui.QLabel(self.General)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel2_5.sizePolicy().hasHeightForWidth())
        self.TextLabel2_5.setSizePolicy(sizePolicy)
        self.TextLabel2_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TextLabel2_5.setObjectName(_fromUtf8("TextLabel2_5"))
        self.vboxlayout3.addWidget(self.TextLabel2_5)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem1)
        self.vboxlayout2.addLayout(self.vboxlayout3)
        self.Tab.addTab(self.General, _fromUtf8(""))
        self.Price = QtGui.QWidget()
        self.Price.setObjectName(_fromUtf8("Price"))
        self.vboxlayout4 = QtGui.QVBoxLayout(self.Price)
        self.vboxlayout4.setMargin(9)
        self.vboxlayout4.setSpacing(6)
        self.vboxlayout4.setObjectName(_fromUtf8("vboxlayout4"))
        self.vboxlayout5 = QtGui.QVBoxLayout()
        self.vboxlayout5.setMargin(0)
        self.vboxlayout5.setSpacing(6)
        self.vboxlayout5.setObjectName(_fromUtf8("vboxlayout5"))
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.vboxlayout6 = QtGui.QVBoxLayout()
        self.vboxlayout6.setMargin(0)
        self.vboxlayout6.setSpacing(6)
        self.vboxlayout6.setObjectName(_fromUtf8("vboxlayout6"))
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.GroupBox1 = QtGui.QGroupBox(self.Price)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox1.sizePolicy().hasHeightForWidth())
        self.GroupBox1.setSizePolicy(sizePolicy)
        self.GroupBox1.setObjectName(_fromUtf8("GroupBox1"))
        self.hboxlayout3 = QtGui.QHBoxLayout(self.GroupBox1)
        self.hboxlayout3.setMargin(9)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.vboxlayout7 = QtGui.QVBoxLayout()
        self.vboxlayout7.setMargin(0)
        self.vboxlayout7.setSpacing(6)
        self.vboxlayout7.setObjectName(_fromUtf8("vboxlayout7"))
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.PPGem = QtGui.QLineEdit(self.GroupBox1)
        self.PPGem.setObjectName(_fromUtf8("PPGem"))
        self.gridlayout.addWidget(self.PPGem, 0, 1, 1, 1)
        self.TextLabel1_2 = QtGui.QLabel(self.GroupBox1)
        self.TextLabel1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel1_2.setObjectName(_fromUtf8("TextLabel1_2"))
        self.gridlayout.addWidget(self.TextLabel1_2, 0, 0, 1, 1)
        self.PPOrder = QtGui.QLineEdit(self.GroupBox1)
        self.PPOrder.setObjectName(_fromUtf8("PPOrder"))
        self.gridlayout.addWidget(self.PPOrder, 2, 1, 1, 1)
        self.TextLabel1_2_2 = QtGui.QLabel(self.GroupBox1)
        self.TextLabel1_2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel1_2_2.setObjectName(_fromUtf8("TextLabel1_2_2"))
        self.gridlayout.addWidget(self.TextLabel1_2_2, 1, 0, 1, 1)
        self.TextLabel1_2_3 = QtGui.QLabel(self.GroupBox1)
        self.TextLabel1_2_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel1_2_3.setObjectName(_fromUtf8("TextLabel1_2_3"))
        self.gridlayout.addWidget(self.TextLabel1_2_3, 2, 0, 1, 1)
        self.PPItem = QtGui.QLineEdit(self.GroupBox1)
        self.PPItem.setObjectName(_fromUtf8("PPItem"))
        self.gridlayout.addWidget(self.PPItem, 1, 1, 1, 1)
        self.vboxlayout7.addLayout(self.gridlayout)
        self.TextLabel2_3 = QtGui.QLabel(self.GroupBox1)
        self.TextLabel2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.TextLabel2_3.setObjectName(_fromUtf8("TextLabel2_3"))
        self.vboxlayout7.addWidget(self.TextLabel2_3)
        self.hboxlayout3.addLayout(self.vboxlayout7)
        self.hboxlayout2.addWidget(self.GroupBox1)
        self.vboxlayout8 = QtGui.QVBoxLayout()
        self.vboxlayout8.setMargin(0)
        self.vboxlayout8.setSpacing(6)
        self.vboxlayout8.setObjectName(_fromUtf8("vboxlayout8"))
        self.GroupBox6 = QtGui.QGroupBox(self.Price)
        self.GroupBox6.setObjectName(_fromUtf8("GroupBox6"))
        self.vboxlayout9 = QtGui.QVBoxLayout(self.GroupBox6)
        self.vboxlayout9.setMargin(9)
        self.vboxlayout9.setSpacing(6)
        self.vboxlayout9.setObjectName(_fromUtf8("vboxlayout9"))
        self.vboxlayout10 = QtGui.QVBoxLayout()
        self.vboxlayout10.setMargin(0)
        self.vboxlayout10.setSpacing(6)
        self.vboxlayout10.setObjectName(_fromUtf8("vboxlayout10"))
        self.HourPrice = QtGui.QLineEdit(self.GroupBox6)
        self.HourPrice.setObjectName(_fromUtf8("HourPrice"))
        self.vboxlayout10.addWidget(self.HourPrice)
        self.HourInclude = QtGui.QCheckBox(self.GroupBox6)
        self.HourInclude.setObjectName(_fromUtf8("HourInclude"))
        self.vboxlayout10.addWidget(self.HourInclude)
        self.vboxlayout9.addLayout(self.vboxlayout10)
        self.vboxlayout8.addWidget(self.GroupBox6)
        self.GroupBox4 = QtGui.QGroupBox(self.Price)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox4.sizePolicy().hasHeightForWidth())
        self.GroupBox4.setSizePolicy(sizePolicy)
        self.GroupBox4.setObjectName(_fromUtf8("GroupBox4"))
        self.vboxlayout11 = QtGui.QVBoxLayout(self.GroupBox4)
        self.vboxlayout11.setMargin(9)
        self.vboxlayout11.setSpacing(6)
        self.vboxlayout11.setObjectName(_fromUtf8("vboxlayout11"))
        self.vboxlayout12 = QtGui.QVBoxLayout()
        self.vboxlayout12.setMargin(0)
        self.vboxlayout12.setSpacing(6)
        self.vboxlayout12.setObjectName(_fromUtf8("vboxlayout12"))
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setMargin(0)
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        self.GenMarkup = QtGui.QLineEdit(self.GroupBox4)
        self.GenMarkup.setObjectName(_fromUtf8("GenMarkup"))
        self.hboxlayout4.addWidget(self.GenMarkup)
        self.TextLabel11 = QtGui.QLabel(self.GroupBox4)
        self.TextLabel11.setObjectName(_fromUtf8("TextLabel11"))
        self.hboxlayout4.addWidget(self.TextLabel11)
        self.vboxlayout12.addLayout(self.hboxlayout4)
        self.TextLabel12 = QtGui.QLabel(self.GroupBox4)
        self.TextLabel12.setObjectName(_fromUtf8("TextLabel12"))
        self.vboxlayout12.addWidget(self.TextLabel12)
        self.vboxlayout11.addLayout(self.vboxlayout12)
        self.vboxlayout8.addWidget(self.GroupBox4)
        self.hboxlayout2.addLayout(self.vboxlayout8)
        self.vboxlayout6.addLayout(self.hboxlayout2)
        self.GroupBox3 = QtGui.QGroupBox(self.Price)
        self.GroupBox3.setObjectName(_fromUtf8("GroupBox3"))
        self.vboxlayout13 = QtGui.QVBoxLayout(self.GroupBox3)
        self.vboxlayout13.setMargin(9)
        self.vboxlayout13.setSpacing(6)
        self.vboxlayout13.setObjectName(_fromUtf8("vboxlayout13"))
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.PPInclude = QtGui.QCheckBox(self.GroupBox3)
        self.PPInclude.setObjectName(_fromUtf8("PPInclude"))
        self.gridlayout1.addWidget(self.PPInclude, 3, 0, 1, 1)
        self.PPImbue = QtGui.QLineEdit(self.GroupBox3)
        self.PPImbue.setObjectName(_fromUtf8("PPImbue"))
        self.gridlayout1.addWidget(self.PPImbue, 1, 0, 1, 2)
        self.TextLabel9 = QtGui.QLabel(self.GroupBox3)
        self.TextLabel9.setObjectName(_fromUtf8("TextLabel9"))
        self.gridlayout1.addWidget(self.TextLabel9, 2, 3, 1, 2)
        self.PPOC = QtGui.QLineEdit(self.GroupBox3)
        self.PPOC.setObjectName(_fromUtf8("PPOC"))
        self.gridlayout1.addWidget(self.PPOC, 2, 0, 1, 3)
        self.TextLabel8 = QtGui.QLabel(self.GroupBox3)
        self.TextLabel8.setObjectName(_fromUtf8("TextLabel8"))
        self.gridlayout1.addWidget(self.TextLabel8, 1, 2, 1, 3)
        self.PPLevel = QtGui.QLineEdit(self.GroupBox3)
        self.PPLevel.setObjectName(_fromUtf8("PPLevel"))
        self.gridlayout1.addWidget(self.PPLevel, 0, 0, 1, 4)
        self.TextLabel7 = QtGui.QLabel(self.GroupBox3)
        self.TextLabel7.setObjectName(_fromUtf8("TextLabel7"))
        self.gridlayout1.addWidget(self.TextLabel7, 0, 4, 1, 1)
        self.TextLabel10 = QtGui.QLabel(self.GroupBox3)
        self.TextLabel10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextLabel10.setObjectName(_fromUtf8("TextLabel10"))
        self.gridlayout1.addWidget(self.TextLabel10, 3, 2, 1, 3)
        self.vboxlayout13.addLayout(self.gridlayout1)
        self.vboxlayout6.addWidget(self.GroupBox3)
        self.hboxlayout1.addLayout(self.vboxlayout6)
        self.GroupBox5 = QtGui.QGroupBox(self.Price)
        self.GroupBox5.setObjectName(_fromUtf8("GroupBox5"))
        self.vboxlayout14 = QtGui.QVBoxLayout(self.GroupBox5)
        self.vboxlayout14.setMargin(9)
        self.vboxlayout14.setSpacing(6)
        self.vboxlayout14.setObjectName(_fromUtf8("vboxlayout14"))
        self.vboxlayout15 = QtGui.QVBoxLayout()
        self.vboxlayout15.setMargin(0)
        self.vboxlayout15.setSpacing(6)
        self.vboxlayout15.setObjectName(_fromUtf8("vboxlayout15"))
        self.TierPriceTable = QtGui.QTableWidget(self.GroupBox5)
        self.TierPriceTable.setRowCount(10)
        self.TierPriceTable.setColumnCount(2)
        self.TierPriceTable.setObjectName(_fromUtf8("TierPriceTable"))
        self.vboxlayout15.addWidget(self.TierPriceTable)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setMargin(0)
        self.hboxlayout5.setSpacing(6)
        self.hboxlayout5.setObjectName(_fromUtf8("hboxlayout5"))
        self.TierInclude = QtGui.QCheckBox(self.GroupBox5)
        self.TierInclude.setObjectName(_fromUtf8("TierInclude"))
        self.hboxlayout5.addWidget(self.TierInclude)
        self.TextLabel15 = QtGui.QLabel(self.GroupBox5)
        self.TextLabel15.setObjectName(_fromUtf8("TextLabel15"))
        self.hboxlayout5.addWidget(self.TextLabel15)
        self.vboxlayout15.addLayout(self.hboxlayout5)
        self.vboxlayout14.addLayout(self.vboxlayout15)
        self.hboxlayout1.addWidget(self.GroupBox5)
        self.vboxlayout5.addLayout(self.hboxlayout1)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setMargin(0)
        self.hboxlayout6.setSpacing(6)
        self.hboxlayout6.setObjectName(_fromUtf8("hboxlayout6"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem2)
        self.CostInPrice = QtGui.QCheckBox(self.Price)
        self.CostInPrice.setChecked(True)
        self.CostInPrice.setObjectName(_fromUtf8("CostInPrice"))
        self.hboxlayout6.addWidget(self.CostInPrice)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem3)
        self.vboxlayout5.addLayout(self.hboxlayout6)
        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.hboxlayout7.setMargin(0)
        self.hboxlayout7.setSpacing(6)
        self.hboxlayout7.setObjectName(_fromUtf8("hboxlayout7"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout7.addItem(spacerItem4)
        self.TextLabel2_4 = QtGui.QLabel(self.Price)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TextLabel2_4.sizePolicy().hasHeightForWidth())
        self.TextLabel2_4.setSizePolicy(sizePolicy)
        self.TextLabel2_4.setObjectName(_fromUtf8("TextLabel2_4"))
        self.hboxlayout7.addWidget(self.TextLabel2_4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout7.addItem(spacerItem5)
        self.vboxlayout5.addLayout(self.hboxlayout7)
        self.vboxlayout4.addLayout(self.vboxlayout5)
        self.Tab.addTab(self.Price, _fromUtf8(""))
        self.vboxlayout1.addWidget(self.Tab)
        self.hboxlayout8 = QtGui.QHBoxLayout()
        self.hboxlayout8.setMargin(0)
        self.hboxlayout8.setSpacing(25)
        self.hboxlayout8.setObjectName(_fromUtf8("hboxlayout8"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout8.addItem(spacerItem6)
        self.OK = QtGui.QPushButton(B_Options)
        self.OK.setObjectName(_fromUtf8("OK"))
        self.hboxlayout8.addWidget(self.OK)
        self.Cancel = QtGui.QPushButton(B_Options)
        self.Cancel.setObjectName(_fromUtf8("Cancel"))
        self.hboxlayout8.addWidget(self.Cancel)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout8.addItem(spacerItem7)
        self.vboxlayout1.addLayout(self.hboxlayout8)
        self.vboxlayout.addLayout(self.vboxlayout1)

        self.retranslateUi(B_Options)
        self.Tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(B_Options)
        B_Options.setTabOrder(self.PPGem, self.PPItem)
        B_Options.setTabOrder(self.PPItem, self.PPOrder)
        B_Options.setTabOrder(self.PPOrder, self.PPLevel)
        B_Options.setTabOrder(self.PPLevel, self.PPImbue)
        B_Options.setTabOrder(self.PPImbue, self.PPOC)
        B_Options.setTabOrder(self.PPOC, self.PPInclude)
        B_Options.setTabOrder(self.PPInclude, self.GenMarkup)
        B_Options.setTabOrder(self.GenMarkup, self.TierInclude)
        B_Options.setTabOrder(self.TierInclude, self.HourPrice)
        B_Options.setTabOrder(self.HourPrice, self.HourInclude)
        B_Options.setTabOrder(self.HourInclude, self.CostInPrice)
        B_Options.setTabOrder(self.CostInPrice, self.OK)
        B_Options.setTabOrder(self.OK, self.Cancel)
        B_Options.setTabOrder(self.Cancel, self.Skill)
        B_Options.setTabOrder(self.Skill, self.CapDistance)
        B_Options.setTabOrder(self.CapDistance, self.ShowDoneGems)
        B_Options.setTabOrder(self.ShowDoneGems, self.IncludeRR)
        B_Options.setTabOrder(self.IncludeRR, self.HideNonClassSkills)
        B_Options.setTabOrder(self.HideNonClassSkills, self.Coop)
        B_Options.setTabOrder(self.Coop, self.Tab)

    def retranslateUi(self, B_Options):
        B_Options.setWindowTitle(_translate("B_Options", "Options", None))
        self.TextLabel1.setText(_translate("B_Options", "Crafter Skill:", None))
        self.CapDistance.setText(_translate("B_Options", "Show Distance To Cap (instead of total)", None))
        self.ShowDoneGems.setText(_translate("B_Options", "Hide \"Made\" Gems from Materials List and Exported Gems", None))
        self.ShowScrollingSlots.setText(_translate("B_Options", "Scrollable Slots (allows your window to be shorter)", None))
        self.EuroServers.setText(_translate("B_Options", "Export Gems to European/GOA Servers", None))
        self.IncludeRR.setText(_translate("B_Options", "Include Racial Resists in Totals", None))
        self.HideNonClassSkills.setText(_translate("B_Options", "Hide Skills not usable by this Class", None))
        self.Coop.setText(_translate("B_Options", "Co-op / PvP Server", None))
        self.TextLabel2_5.setText(_translate("B_Options", "        (Lets you access items from all realms)", None))
        self.Tab.setTabText(self.Tab.indexOf(self.General), _translate("B_Options", "General", None))
        self.GroupBox1.setTitle(_translate("B_Options", "Price per", None))
        self.PPGem.setText(_translate("B_Options", "0", None))
        self.TextLabel1_2.setText(_translate("B_Options", "Gem:", None))
        self.PPOrder.setText(_translate("B_Options", "0", None))
        self.TextLabel1_2_2.setText(_translate("B_Options", "Item:", None))
        self.TextLabel1_2_3.setText(_translate("B_Options", "Order:", None))
        self.PPItem.setText(_translate("B_Options", "0", None))
        self.TextLabel2_3.setText(_translate("B_Options", "(cost+ X)", None))
        self.GroupBox6.setTitle(_translate("B_Options", "Per hour", None))
        self.HourPrice.setText(_translate("B_Options", "0", None))
        self.HourInclude.setText(_translate("B_Options", "Include", None))
        self.GroupBox4.setTitle(_translate("B_Options", "General Markup", None))
        self.GenMarkup.setText(_translate("B_Options", "50", None))
        self.TextLabel11.setText(_translate("B_Options", "%", None))
        self.TextLabel12.setText(_translate("B_Options", "(cost + (cost * X%))", None))
        self.GroupBox3.setTitle(_translate("B_Options", "Price per lvl/point", None))
        self.PPInclude.setText(_translate("B_Options", "Include", None))
        self.PPImbue.setText(_translate("B_Options", "0", None))
        self.TextLabel9.setText(_translate("B_Options", "per O/C pt.", None))
        self.PPOC.setText(_translate("B_Options", "0", None))
        self.TextLabel8.setText(_translate("B_Options", "per imbue pt.", None))
        self.PPLevel.setText(_translate("B_Options", "0", None))
        self.TextLabel7.setText(_translate("B_Options", "per level", None))
        self.TextLabel10.setText(_translate("B_Options", "(cost + X)", None))
        self.GroupBox5.setTitle(_translate("B_Options", "Price by Gem Tier", None))
        self.TierInclude.setText(_translate("B_Options", "Include", None))
        self.TextLabel15.setText(_translate("B_Options", "(cost + X)", None))
        self.CostInPrice.setText(_translate("B_Options", "Include cost in price", None))
        self.TextLabel2_4.setText(_translate("B_Options", "All numbers (except percentages) are in amounts of Gold.", None))
        self.Tab.setTabText(self.Tab.indexOf(self.Price), _translate("B_Options", "Price", None))
        self.OK.setText(_translate("B_Options", "OK", None))
        self.Cancel.setText(_translate("B_Options", "Cancel", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    B_Options = QtGui.QDialog()
    ui = Ui_B_Options()
    ui.setupUi(B_Options)
    B_Options.show()
    sys.exit(app.exec_())

