# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScWindow.ui'
#
# Created: Sat Jun 09 02:58:32 2007
#      by: PyQt4 UI code generator 4.1
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt4 import QtCore, QtGui

class Ui_B_SC(object):
    def setupUi(self, B_SC):
        B_SC.setObjectName("B_SC")
        B_SC.resize(QtCore.QSize(QtCore.QRect(0,0,761,510).size()).expandedTo(B_SC.minimumSizeHint()))

        self.ScWinFrame = QtGui.QWidget(B_SC)
        self.ScWinFrame.setObjectName("ScWinFrame")

        self.gridlayout = QtGui.QGridLayout(self.ScWinFrame)
        self.gridlayout.setMargin(3)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName("gridlayout")

        self.GroupCharInfo = GroupFrame(self.ScWinFrame)
        self.GroupCharInfo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.GroupCharInfo.setLineWidth(1)
        self.GroupCharInfo.setObjectName("GroupCharInfo")

        self.gridlayout1 = QtGui.QGridLayout(self.GroupCharInfo)
        self.gridlayout1.setMargin(4)
        self.gridlayout1.setSpacing(0)
        self.gridlayout1.setObjectName("gridlayout1")

        self.LabelCharName = QtGui.QLabel(self.GroupCharInfo)
        self.LabelCharName.setTextFormat(QtCore.Qt.PlainText)
        self.LabelCharName.setObjectName("LabelCharName")
        self.gridlayout1.addWidget(self.LabelCharName,0,0,1,1)

        self.CharName = QtGui.QLineEdit(self.GroupCharInfo)
        self.CharName.setObjectName("CharName")
        self.gridlayout1.addWidget(self.CharName,0,1,1,3)

        self.LabelRealm = QtGui.QLabel(self.GroupCharInfo)
        self.LabelRealm.setTextFormat(QtCore.Qt.PlainText)
        self.LabelRealm.setObjectName("LabelRealm")
        self.gridlayout1.addWidget(self.LabelRealm,1,0,1,1)

        self.Realm = SearchingCombo(self.GroupCharInfo)
        self.Realm.setObjectName("Realm")
        self.gridlayout1.addWidget(self.Realm,1,1,1,3)

        self.LabelCharClass = QtGui.QLabel(self.GroupCharInfo)
        self.LabelCharClass.setTextFormat(QtCore.Qt.PlainText)
        self.LabelCharClass.setObjectName("LabelCharClass")
        self.gridlayout1.addWidget(self.LabelCharClass,2,0,1,1)

        self.CharClass = SearchingCombo(self.GroupCharInfo)
        self.CharClass.setObjectName("CharClass")
        self.gridlayout1.addWidget(self.CharClass,2,1,1,3)

        self.LabelCharRace = QtGui.QLabel(self.GroupCharInfo)
        self.LabelCharRace.setTextFormat(QtCore.Qt.PlainText)
        self.LabelCharRace.setObjectName("LabelCharRace")
        self.gridlayout1.addWidget(self.LabelCharRace,3,0,1,1)

        self.CharRace = SearchingCombo(self.GroupCharInfo)
        self.CharRace.setObjectName("CharRace")
        self.gridlayout1.addWidget(self.CharRace,3,1,1,3)

        self.LabelCharLevel = QtGui.QLabel(self.GroupCharInfo)
        self.LabelCharLevel.setTextFormat(QtCore.Qt.PlainText)
        self.LabelCharLevel.setObjectName("LabelCharLevel")
        self.gridlayout1.addWidget(self.LabelCharLevel,4,0,1,1)

        self.CharLevel = QtGui.QLineEdit(self.GroupCharInfo)
        self.CharLevel.setObjectName("CharLevel")
        self.gridlayout1.addWidget(self.CharLevel,4,1,1,1)

        self.LabelRealmRank = QtGui.QLabel(self.GroupCharInfo)
        self.LabelRealmRank.setTextFormat(QtCore.Qt.PlainText)
        self.LabelRealmRank.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelRealmRank.setObjectName("LabelRealmRank")
        self.gridlayout1.addWidget(self.LabelRealmRank,4,2,1,1)

        self.RealmRank = QtGui.QLineEdit(self.GroupCharInfo)
        self.RealmRank.setObjectName("RealmRank")
        self.gridlayout1.addWidget(self.RealmRank,4,3,1,1)

        self.LabelCraftTime = QtGui.QLabel(self.GroupCharInfo)
        self.LabelCraftTime.setTextFormat(QtCore.Qt.PlainText)
        self.LabelCraftTime.setObjectName("LabelCraftTime")
        self.gridlayout1.addWidget(self.LabelCraftTime,5,0,1,1)

        self.CraftTime = QtGui.QLineEdit(self.GroupCharInfo)
        self.CraftTime.setObjectName("CraftTime")
        self.gridlayout1.addWidget(self.CraftTime,5,1,1,1)

        self.LabelChampionLevel = QtGui.QLabel(self.GroupCharInfo)
        self.LabelChampionLevel.setTextFormat(QtCore.Qt.PlainText)
        self.LabelChampionLevel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelChampionLevel.setObjectName("LabelChampionLevel")
        self.gridlayout1.addWidget(self.LabelChampionLevel,5,2,1,1)

        self.ChampionLevel = QtGui.QLineEdit(self.GroupCharInfo)
        self.ChampionLevel.setObjectName("ChampionLevel")
        self.gridlayout1.addWidget(self.ChampionLevel,5,3,1,1)

        self.LabelOutfitName = QtGui.QLabel(self.GroupCharInfo)
        self.LabelOutfitName.setTextFormat(QtCore.Qt.PlainText)
        self.LabelOutfitName.setObjectName("LabelOutfitName")
        self.gridlayout1.addWidget(self.LabelOutfitName,6,0,1,1)

        self.OutfitName = SearchingCombo(self.GroupCharInfo)
        self.OutfitName.setEditable(True)
        self.OutfitName.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.OutfitName.setDuplicatesEnabled(True)
        self.OutfitName.setObjectName("OutfitName")
        self.gridlayout1.addWidget(self.OutfitName,6,1,1,3)

        spacerItem = QtGui.QSpacerItem(1,3,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Fixed)
        self.gridlayout1.addItem(spacerItem,7,0,1,4)

        self.LabelTotalCost = QtGui.QLabel(self.GroupCharInfo)
        self.LabelTotalCost.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LabelTotalCost.setObjectName("LabelTotalCost")
        self.gridlayout1.addWidget(self.LabelTotalCost,8,0,1,1)

        self.TotalCost = QtGui.QLabel(self.GroupCharInfo)
        self.TotalCost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TotalCost.setObjectName("TotalCost")
        self.gridlayout1.addWidget(self.TotalCost,8,1,1,3)

        self.LabelTotalPrice = QtGui.QLabel(self.GroupCharInfo)
        self.LabelTotalPrice.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LabelTotalPrice.setObjectName("LabelTotalPrice")
        self.gridlayout1.addWidget(self.LabelTotalPrice,9,0,1,1)

        self.TotalPrice = QtGui.QLabel(self.GroupCharInfo)
        self.TotalPrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TotalPrice.setObjectName("TotalPrice")
        self.gridlayout1.addWidget(self.TotalPrice,9,1,1,3)

        spacerItem1 = QtGui.QSpacerItem(1,0,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.MinimumExpanding)
        self.gridlayout1.addItem(spacerItem1,10,0,1,4)
        self.gridlayout.addWidget(self.GroupCharInfo,0,0,1,1)

        self.GroupStats = GroupFrame(self.ScWinFrame)
        self.GroupStats.setFrameShape(QtGui.QFrame.StyledPanel)
        self.GroupStats.setLineWidth(1)
        self.GroupStats.setObjectName("GroupStats")

        self.gridlayout2 = QtGui.QGridLayout(self.GroupStats)
        self.gridlayout2.setMargin(4)
        self.gridlayout2.setSpacing(0)
        self.gridlayout2.setObjectName("gridlayout2")

        self.StrengthLabel = QtGui.QLabel(self.GroupStats)
        self.StrengthLabel.setObjectName("StrengthLabel")
        self.gridlayout2.addWidget(self.StrengthLabel,0,0,1,1)

        self.Strength = QtGui.QLabel(self.GroupStats)
        self.Strength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Strength.setObjectName("Strength")
        self.gridlayout2.addWidget(self.Strength,0,1,1,1)

        self.StrengthCap = QtGui.QLabel(self.GroupStats)
        self.StrengthCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StrengthCap.setObjectName("StrengthCap")
        self.gridlayout2.addWidget(self.StrengthCap,0,2,1,1)

        self.ConstitutionLabel = QtGui.QLabel(self.GroupStats)
        self.ConstitutionLabel.setObjectName("ConstitutionLabel")
        self.gridlayout2.addWidget(self.ConstitutionLabel,1,0,1,1)

        self.Constitution = QtGui.QLabel(self.GroupStats)
        self.Constitution.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Constitution.setObjectName("Constitution")
        self.gridlayout2.addWidget(self.Constitution,1,1,1,1)

        self.ConstitutionCap = QtGui.QLabel(self.GroupStats)
        self.ConstitutionCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ConstitutionCap.setObjectName("ConstitutionCap")
        self.gridlayout2.addWidget(self.ConstitutionCap,1,2,1,1)

        self.DexterityLabel = QtGui.QLabel(self.GroupStats)
        self.DexterityLabel.setObjectName("DexterityLabel")
        self.gridlayout2.addWidget(self.DexterityLabel,2,0,1,1)

        self.Dexterity = QtGui.QLabel(self.GroupStats)
        self.Dexterity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Dexterity.setObjectName("Dexterity")
        self.gridlayout2.addWidget(self.Dexterity,2,1,1,1)

        self.DexterityCap = QtGui.QLabel(self.GroupStats)
        self.DexterityCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DexterityCap.setObjectName("DexterityCap")
        self.gridlayout2.addWidget(self.DexterityCap,2,2,1,1)

        self.QuicknessLabel = QtGui.QLabel(self.GroupStats)
        self.QuicknessLabel.setObjectName("QuicknessLabel")
        self.gridlayout2.addWidget(self.QuicknessLabel,3,0,1,1)

        self.Quickness = QtGui.QLabel(self.GroupStats)
        self.Quickness.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Quickness.setObjectName("Quickness")
        self.gridlayout2.addWidget(self.Quickness,3,1,1,1)

        self.QuicknessCap = QtGui.QLabel(self.GroupStats)
        self.QuicknessCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.QuicknessCap.setObjectName("QuicknessCap")
        self.gridlayout2.addWidget(self.QuicknessCap,3,2,1,1)

        self.IntelligenceLabel = QtGui.QLabel(self.GroupStats)
        self.IntelligenceLabel.setObjectName("IntelligenceLabel")
        self.gridlayout2.addWidget(self.IntelligenceLabel,4,0,1,1)

        self.Intelligence = QtGui.QLabel(self.GroupStats)
        self.Intelligence.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Intelligence.setObjectName("Intelligence")
        self.gridlayout2.addWidget(self.Intelligence,4,1,1,1)

        self.IntelligenceCap = QtGui.QLabel(self.GroupStats)
        self.IntelligenceCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IntelligenceCap.setObjectName("IntelligenceCap")
        self.gridlayout2.addWidget(self.IntelligenceCap,4,2,1,1)

        self.PietyLabel = QtGui.QLabel(self.GroupStats)
        self.PietyLabel.setObjectName("PietyLabel")
        self.gridlayout2.addWidget(self.PietyLabel,5,0,1,1)

        self.Piety = QtGui.QLabel(self.GroupStats)
        self.Piety.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Piety.setObjectName("Piety")
        self.gridlayout2.addWidget(self.Piety,5,1,1,1)

        self.PietyCap = QtGui.QLabel(self.GroupStats)
        self.PietyCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PietyCap.setObjectName("PietyCap")
        self.gridlayout2.addWidget(self.PietyCap,5,2,1,1)

        self.CharismaLabel = QtGui.QLabel(self.GroupStats)
        self.CharismaLabel.setObjectName("CharismaLabel")
        self.gridlayout2.addWidget(self.CharismaLabel,6,0,1,1)

        self.Charisma = QtGui.QLabel(self.GroupStats)
        self.Charisma.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Charisma.setObjectName("Charisma")
        self.gridlayout2.addWidget(self.Charisma,6,1,1,1)

        self.CharismaCap = QtGui.QLabel(self.GroupStats)
        self.CharismaCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CharismaCap.setObjectName("CharismaCap")
        self.gridlayout2.addWidget(self.CharismaCap,6,2,1,1)

        self.EmpathyLabel = QtGui.QLabel(self.GroupStats)
        self.EmpathyLabel.setObjectName("EmpathyLabel")
        self.gridlayout2.addWidget(self.EmpathyLabel,7,0,1,1)

        self.Empathy = QtGui.QLabel(self.GroupStats)
        self.Empathy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Empathy.setObjectName("Empathy")
        self.gridlayout2.addWidget(self.Empathy,7,1,1,1)

        self.EmpathyCap = QtGui.QLabel(self.GroupStats)
        self.EmpathyCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EmpathyCap.setObjectName("EmpathyCap")
        self.gridlayout2.addWidget(self.EmpathyCap,7,2,1,1)

        self.AcuityLabel = QtGui.QLabel(self.GroupStats)
        self.AcuityLabel.setObjectName("AcuityLabel")
        self.gridlayout2.addWidget(self.AcuityLabel,8,0,1,1)

        self.Acuity = QtGui.QLabel(self.GroupStats)
        self.Acuity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Acuity.setObjectName("Acuity")
        self.gridlayout2.addWidget(self.Acuity,8,1,1,1)

        self.AcuityCap = QtGui.QLabel(self.GroupStats)
        self.AcuityCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AcuityCap.setObjectName("AcuityCap")
        self.gridlayout2.addWidget(self.AcuityCap,8,2,1,1)

        self.PowerLabel = QtGui.QLabel(self.GroupStats)
        self.PowerLabel.setObjectName("PowerLabel")
        self.gridlayout2.addWidget(self.PowerLabel,9,0,1,1)

        self.Power = QtGui.QLabel(self.GroupStats)
        self.Power.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Power.setObjectName("Power")
        self.gridlayout2.addWidget(self.Power,9,1,1,1)

        self.PowerCap = QtGui.QLabel(self.GroupStats)
        self.PowerCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PowerCap.setObjectName("PowerCap")
        self.gridlayout2.addWidget(self.PowerCap,9,2,1,1)

        self.PowerPoolLabel = QtGui.QLabel(self.GroupStats)
        self.PowerPoolLabel.setObjectName("PowerPoolLabel")
        self.gridlayout2.addWidget(self.PowerPoolLabel,10,0,1,1)

        self.PowerPool = QtGui.QLabel(self.GroupStats)
        self.PowerPool.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PowerPool.setObjectName("PowerPool")
        self.gridlayout2.addWidget(self.PowerPool,10,1,1,1)

        self.PowerPoolCap = QtGui.QLabel(self.GroupStats)
        self.PowerPoolCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PowerPoolCap.setObjectName("PowerPoolCap")
        self.gridlayout2.addWidget(self.PowerPoolCap,10,2,1,1)

        self.FatigueLabel = QtGui.QLabel(self.GroupStats)
        self.FatigueLabel.setObjectName("FatigueLabel")
        self.gridlayout2.addWidget(self.FatigueLabel,11,0,1,1)

        self.Fatigue = QtGui.QLabel(self.GroupStats)
        self.Fatigue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Fatigue.setObjectName("Fatigue")
        self.gridlayout2.addWidget(self.Fatigue,11,1,1,1)

        self.FatigueCap = QtGui.QLabel(self.GroupStats)
        self.FatigueCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FatigueCap.setObjectName("FatigueCap")
        self.gridlayout2.addWidget(self.FatigueCap,11,2,1,1)

        self.AFLabel = QtGui.QLabel(self.GroupStats)
        self.AFLabel.setObjectName("AFLabel")
        self.gridlayout2.addWidget(self.AFLabel,12,0,1,1)

        self.AF = QtGui.QLabel(self.GroupStats)
        self.AF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AF.setObjectName("AF")
        self.gridlayout2.addWidget(self.AF,12,1,1,1)

        self.AFCap = QtGui.QLabel(self.GroupStats)
        self.AFCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AFCap.setObjectName("AFCap")
        self.gridlayout2.addWidget(self.AFCap,12,2,1,1)

        self.HitsLabel = QtGui.QLabel(self.GroupStats)
        self.HitsLabel.setObjectName("HitsLabel")
        self.gridlayout2.addWidget(self.HitsLabel,13,0,1,1)

        self.Hits = QtGui.QLabel(self.GroupStats)
        self.Hits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Hits.setObjectName("Hits")
        self.gridlayout2.addWidget(self.Hits,13,1,1,1)

        self.HitsCap = QtGui.QLabel(self.GroupStats)
        self.HitsCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HitsCap.setObjectName("HitsCap")
        self.gridlayout2.addWidget(self.HitsCap,13,2,1,1)

        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(5)
        self.hboxlayout.setObjectName("hboxlayout")

        self.LabelTotalUtility = QtGui.QLabel(self.GroupStats)
        self.LabelTotalUtility.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelTotalUtility.setObjectName("LabelTotalUtility")
        self.hboxlayout.addWidget(self.LabelTotalUtility)

        self.TotalUtility = QtGui.QLabel(self.GroupStats)
        self.TotalUtility.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TotalUtility.setObjectName("TotalUtility")
        self.hboxlayout.addWidget(self.TotalUtility)
        self.gridlayout2.addLayout(self.hboxlayout,14,0,1,3)

        spacerItem2 = QtGui.QSpacerItem(1,0,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.MinimumExpanding)
        self.gridlayout2.addItem(spacerItem2,15,0,1,3)
        self.gridlayout.addWidget(self.GroupStats,0,1,1,1)

        self.GroupResists = GroupFrame(self.ScWinFrame)
        self.GroupResists.setFrameShape(QtGui.QFrame.StyledPanel)
        self.GroupResists.setLineWidth(1)
        self.GroupResists.setObjectName("GroupResists")

        self.gridlayout3 = QtGui.QGridLayout(self.GroupResists)
        self.gridlayout3.setMargin(4)
        self.gridlayout3.setSpacing(0)
        self.gridlayout3.setObjectName("gridlayout3")

        self.BodyLabel = QtGui.QLabel(self.GroupResists)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridlayout3.addWidget(self.BodyLabel,0,0,1,1)

        self.Body = QtGui.QLabel(self.GroupResists)
        self.Body.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Body.setObjectName("Body")
        self.gridlayout3.addWidget(self.Body,0,1,1,1)

        self.BodyCap = QtGui.QLabel(self.GroupResists)
        self.BodyCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.BodyCap.setObjectName("BodyCap")
        self.gridlayout3.addWidget(self.BodyCap,0,2,1,1)

        self.ColdLabel = QtGui.QLabel(self.GroupResists)
        self.ColdLabel.setObjectName("ColdLabel")
        self.gridlayout3.addWidget(self.ColdLabel,1,0,1,1)

        self.Cold = QtGui.QLabel(self.GroupResists)
        self.Cold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Cold.setObjectName("Cold")
        self.gridlayout3.addWidget(self.Cold,1,1,1,1)

        self.ColdCap = QtGui.QLabel(self.GroupResists)
        self.ColdCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ColdCap.setObjectName("ColdCap")
        self.gridlayout3.addWidget(self.ColdCap,1,2,1,1)

        self.HeatLabel = QtGui.QLabel(self.GroupResists)
        self.HeatLabel.setObjectName("HeatLabel")
        self.gridlayout3.addWidget(self.HeatLabel,2,0,1,1)

        self.Heat = QtGui.QLabel(self.GroupResists)
        self.Heat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Heat.setObjectName("Heat")
        self.gridlayout3.addWidget(self.Heat,2,1,1,1)

        self.HeatCap = QtGui.QLabel(self.GroupResists)
        self.HeatCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HeatCap.setObjectName("HeatCap")
        self.gridlayout3.addWidget(self.HeatCap,2,2,1,1)

        self.EnergyLabel = QtGui.QLabel(self.GroupResists)
        self.EnergyLabel.setObjectName("EnergyLabel")
        self.gridlayout3.addWidget(self.EnergyLabel,3,0,1,1)

        self.Energy = QtGui.QLabel(self.GroupResists)
        self.Energy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Energy.setObjectName("Energy")
        self.gridlayout3.addWidget(self.Energy,3,1,1,1)

        self.EnergyCap = QtGui.QLabel(self.GroupResists)
        self.EnergyCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EnergyCap.setObjectName("EnergyCap")
        self.gridlayout3.addWidget(self.EnergyCap,3,2,1,1)

        self.MatterLabel = QtGui.QLabel(self.GroupResists)
        self.MatterLabel.setObjectName("MatterLabel")
        self.gridlayout3.addWidget(self.MatterLabel,4,0,1,1)

        self.Matter = QtGui.QLabel(self.GroupResists)
        self.Matter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Matter.setObjectName("Matter")
        self.gridlayout3.addWidget(self.Matter,4,1,1,1)

        self.MatterCap = QtGui.QLabel(self.GroupResists)
        self.MatterCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MatterCap.setObjectName("MatterCap")
        self.gridlayout3.addWidget(self.MatterCap,4,2,1,1)

        self.SpiritLabel = QtGui.QLabel(self.GroupResists)
        self.SpiritLabel.setObjectName("SpiritLabel")
        self.gridlayout3.addWidget(self.SpiritLabel,5,0,1,1)

        self.Spirit = QtGui.QLabel(self.GroupResists)
        self.Spirit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Spirit.setObjectName("Spirit")
        self.gridlayout3.addWidget(self.Spirit,5,1,1,1)

        self.SpiritCap = QtGui.QLabel(self.GroupResists)
        self.SpiritCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SpiritCap.setObjectName("SpiritCap")
        self.gridlayout3.addWidget(self.SpiritCap,5,2,1,1)

        self.CrushLabel = QtGui.QLabel(self.GroupResists)
        self.CrushLabel.setObjectName("CrushLabel")
        self.gridlayout3.addWidget(self.CrushLabel,6,0,1,1)

        self.Crush = QtGui.QLabel(self.GroupResists)
        self.Crush.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Crush.setObjectName("Crush")
        self.gridlayout3.addWidget(self.Crush,6,1,1,1)

        self.CrushCap = QtGui.QLabel(self.GroupResists)
        self.CrushCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CrushCap.setObjectName("CrushCap")
        self.gridlayout3.addWidget(self.CrushCap,6,2,1,1)

        self.ThrustLabel = QtGui.QLabel(self.GroupResists)
        self.ThrustLabel.setObjectName("ThrustLabel")
        self.gridlayout3.addWidget(self.ThrustLabel,7,0,1,1)

        self.Thrust = QtGui.QLabel(self.GroupResists)
        self.Thrust.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Thrust.setObjectName("Thrust")
        self.gridlayout3.addWidget(self.Thrust,7,1,1,1)

        self.ThrustCap = QtGui.QLabel(self.GroupResists)
        self.ThrustCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ThrustCap.setObjectName("ThrustCap")
        self.gridlayout3.addWidget(self.ThrustCap,7,2,1,1)

        self.SlashLabel = QtGui.QLabel(self.GroupResists)
        self.SlashLabel.setObjectName("SlashLabel")
        self.gridlayout3.addWidget(self.SlashLabel,8,0,1,1)

        self.Slash = QtGui.QLabel(self.GroupResists)
        self.Slash.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Slash.setObjectName("Slash")
        self.gridlayout3.addWidget(self.Slash,8,1,1,1)

        self.SlashCap = QtGui.QLabel(self.GroupResists)
        self.SlashCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SlashCap.setObjectName("SlashCap")
        self.gridlayout3.addWidget(self.SlashCap,8,2,1,1)

        self.EssenceLabel = QtGui.QLabel(self.GroupResists)
        self.EssenceLabel.setObjectName("EssenceLabel")
        self.gridlayout3.addWidget(self.EssenceLabel,9,0,1,1)

        self.Essence = QtGui.QLabel(self.GroupResists)
        self.Essence.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Essence.setObjectName("Essence")
        self.gridlayout3.addWidget(self.Essence,9,1,1,1)

        self.EssenceCap = QtGui.QLabel(self.GroupResists)
        self.EssenceCap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EssenceCap.setObjectName("EssenceCap")
        self.gridlayout3.addWidget(self.EssenceCap,9,2,1,1)

        spacerItem3 = QtGui.QSpacerItem(1,1,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.MinimumExpanding)
        self.gridlayout3.addItem(spacerItem3,10,0,1,3)
        self.gridlayout.addWidget(self.GroupResists,0,2,1,1)

        self.GroupSkillsList = GroupFrame(self.ScWinFrame)
        self.GroupSkillsList.setFrameShape(QtGui.QFrame.StyledPanel)
        self.GroupSkillsList.setLineWidth(1)
        self.GroupSkillsList.setObjectName("GroupSkillsList")

        self.gridlayout4 = QtGui.QGridLayout(self.GroupSkillsList)
        self.gridlayout4.setMargin(4)
        self.gridlayout4.setSpacing(0)
        self.gridlayout4.setObjectName("gridlayout4")

        self.SkillsList = SkillsView(self.GroupSkillsList)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(7))
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SkillsList.sizePolicy().hasHeightForWidth())
        self.SkillsList.setSizePolicy(sizePolicy)
        self.SkillsList.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.SkillsList.setFrameShape(QtGui.QFrame.NoFrame)
        self.SkillsList.setFrameShadow(QtGui.QFrame.Plain)
        self.SkillsList.setLineWidth(0)
        self.SkillsList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SkillsList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SkillsList.setAutoScroll(True)
        self.SkillsList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.SkillsList.setWrapping(True)
        self.SkillsList.setResizeMode(QtGui.QListView.Adjust)
        self.SkillsList.setObjectName("SkillsList")
        self.gridlayout4.addWidget(self.SkillsList,0,0,1,1)
        self.gridlayout.addWidget(self.GroupSkillsList,0,3,1,1)

        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName("vboxlayout")

        self.PieceTab = MultiTabBar(self.ScWinFrame)
        self.PieceTab.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PieceTab.setObjectName("PieceTab")
        self.vboxlayout.addWidget(self.PieceTab)

        spacerItem4 = QtGui.QSpacerItem(1,1,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Fixed)
        self.vboxlayout.addItem(spacerItem4)

        self.GroupItemFrame = MultiTabFrame(self.ScWinFrame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GroupItemFrame.sizePolicy().hasHeightForWidth())
        self.GroupItemFrame.setSizePolicy(sizePolicy)
        self.GroupItemFrame.setObjectName("GroupItemFrame")

        self.vboxlayout1 = QtGui.QVBoxLayout(self.GroupItemFrame)
        self.vboxlayout1.setMargin(6)
        self.vboxlayout1.setSpacing(0)
        self.vboxlayout1.setObjectName("vboxlayout1")

        spacerItem5 = QtGui.QSpacerItem(1,2,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Fixed)
        self.vboxlayout1.addItem(spacerItem5)

        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(0)
        self.hboxlayout1.setObjectName("hboxlayout1")

        self.ItemLevelLabel = QtGui.QLabel(self.GroupItemFrame)
        self.ItemLevelLabel.setTextFormat(QtCore.Qt.PlainText)
        self.ItemLevelLabel.setObjectName("ItemLevelLabel")
        self.hboxlayout1.addWidget(self.ItemLevelLabel)

        self.ItemLevel = QtGui.QLineEdit(self.GroupItemFrame)
        self.ItemLevel.setObjectName("ItemLevel")
        self.hboxlayout1.addWidget(self.ItemLevel)

        self.ItemLevelButton = QtGui.QPushButton(self.GroupItemFrame)
        self.ItemLevelButton.setMaximumSize(QtCore.QSize(21,21))
        self.ItemLevelButton.setObjectName("ItemLevelButton")
        self.hboxlayout1.addWidget(self.ItemLevelButton)

        self.ItemQualityLabel = QtGui.QLabel(self.GroupItemFrame)
        self.ItemQualityLabel.setTextFormat(QtCore.Qt.PlainText)
        self.ItemQualityLabel.setObjectName("ItemQualityLabel")
        self.hboxlayout1.addWidget(self.ItemQualityLabel)

        self.QualDrop = SearchingCombo(self.GroupItemFrame)
        self.QualDrop.setObjectName("QualDrop")
        self.hboxlayout1.addWidget(self.QualDrop)

        self.QualEdit = QtGui.QLineEdit(self.GroupItemFrame)
        self.QualEdit.setObjectName("QualEdit")
        self.hboxlayout1.addWidget(self.QualEdit)

        self.ItemNameLabel = QtGui.QLabel(self.GroupItemFrame)
        self.ItemNameLabel.setTextFormat(QtCore.Qt.PlainText)
        self.ItemNameLabel.setObjectName("ItemNameLabel")
        self.hboxlayout1.addWidget(self.ItemNameLabel)

        self.ItemNameCombo = SearchingCombo(self.GroupItemFrame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ItemNameCombo.sizePolicy().hasHeightForWidth())
        self.ItemNameCombo.setSizePolicy(sizePolicy)
        self.ItemNameCombo.setEditable(True)
        self.ItemNameCombo.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.ItemNameCombo.setDuplicatesEnabled(True)
        self.ItemNameCombo.setObjectName("ItemNameCombo")
        self.hboxlayout1.addWidget(self.ItemNameCombo)

        self.Equipped = QtGui.QCheckBox(self.GroupItemFrame)
        self.Equipped.setObjectName("Equipped")
        self.hboxlayout1.addWidget(self.Equipped)

        self.ToggleItemView = QtGui.QPushButton(self.GroupItemFrame)
        self.ToggleItemView.setObjectName("ToggleItemView")
        self.hboxlayout1.addWidget(self.ToggleItemView)
        self.vboxlayout1.addLayout(self.hboxlayout1)

        self.stackedlayout = QtGui.QStackedLayout()
        self.stackedlayout.setMargin(0)
        self.stackedlayout.setSpacing(0)
        self.stackedlayout.setObjectName("stackedlayout")

        self.ItemSummaryFrame = QtGui.QWidget(self.GroupItemFrame)
        self.ItemSummaryFrame.setObjectName("ItemSummaryFrame")

        self.hboxlayout2 = QtGui.QHBoxLayout(self.ItemSummaryFrame)
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setSpacing(9)
        self.hboxlayout2.setObjectName("hboxlayout2")

        self.ItemInfoFrame = QtGui.QWidget(self.ItemSummaryFrame)
        self.ItemInfoFrame.setObjectName("ItemInfoFrame")

        self.vboxlayout2 = QtGui.QVBoxLayout(self.ItemInfoFrame)
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setSpacing(0)
        self.vboxlayout2.setObjectName("vboxlayout2")

        self.LabelItemInfo = QtGui.QLabel(self.ItemInfoFrame)
        self.LabelItemInfo.setObjectName("LabelItemInfo")
        self.vboxlayout2.addWidget(self.LabelItemInfo)

        self.ScrollItemInfo = ScrollArea(self.ItemInfoFrame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ScrollItemInfo.sizePolicy().hasHeightForWidth())
        self.ScrollItemInfo.setSizePolicy(sizePolicy)
        self.ScrollItemInfo.setFrameShape(QtGui.QFrame.NoFrame)
        self.ScrollItemInfo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ScrollItemInfo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ScrollItemInfo.setObjectName("ScrollItemInfo")

        self.ItemInfoGrid = QtGui.QWidget(self.ScrollItemInfo)
        self.ItemInfoGrid.setObjectName("ItemInfoGrid")

        self.gridlayout5 = QtGui.QGridLayout(self.ItemInfoGrid)
        self.gridlayout5.setMargin(0)
        self.gridlayout5.setSpacing(0)
        self.gridlayout5.setObjectName("gridlayout5")

        self.LabelItemRealm = QtGui.QLabel(self.ItemInfoGrid)
        self.LabelItemRealm.setTextFormat(QtCore.Qt.PlainText)
        self.LabelItemRealm.setObjectName("LabelItemRealm")
        self.gridlayout5.addWidget(self.LabelItemRealm,0,0,1,1)

        self.ItemRealm = SearchingCombo(self.ItemInfoGrid)
        self.ItemRealm.setObjectName("ItemRealm")
        self.gridlayout5.addWidget(self.ItemRealm,0,1,1,3)

        self.LabelItemType = QtGui.QLabel(self.ItemInfoGrid)
        self.LabelItemType.setTextFormat(QtCore.Qt.PlainText)
        self.LabelItemType.setObjectName("LabelItemType")
        self.gridlayout5.addWidget(self.LabelItemType,1,0,1,1)

        self.ItemType = SearchingCombo(self.ItemInfoGrid)
        self.ItemType.setObjectName("ItemType")
        self.gridlayout5.addWidget(self.ItemType,1,1,1,3)

        self.LabelItemSource = QtGui.QLabel(self.ItemInfoGrid)
        self.LabelItemSource.setTextFormat(QtCore.Qt.PlainText)
        self.LabelItemSource.setObjectName("LabelItemSource")
        self.gridlayout5.addWidget(self.LabelItemSource,2,0,1,1)

        self.ItemSource = SearchingCombo(self.ItemInfoGrid)
        self.ItemSource.setObjectName("ItemSource")
        self.gridlayout5.addWidget(self.ItemSource,2,1,1,3)

        self.LabelBonusEdit = QtGui.QLabel(self.ItemInfoGrid)
        self.LabelBonusEdit.setTextFormat(QtCore.Qt.PlainText)
        self.LabelBonusEdit.setObjectName("LabelBonusEdit")
        self.gridlayout5.addWidget(self.LabelBonusEdit,3,0,1,1)

        self.BonusEdit = QtGui.QLineEdit(self.ItemInfoGrid)
        self.BonusEdit.setObjectName("BonusEdit")
        self.gridlayout5.addWidget(self.BonusEdit,3,1,1,1)

        self.LabelAFDPSEdit = QtGui.QLabel(self.ItemInfoGrid)
        self.LabelAFDPSEdit.setTextFormat(QtCore.Qt.PlainText)
        self.LabelAFDPSEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelAFDPSEdit.setObjectName("LabelAFDPSEdit")
        self.gridlayout5.addWidget(self.LabelAFDPSEdit,3,2,1,1)

        self.AFDPSEdit = QtGui.QLineEdit(self.ItemInfoGrid)
        self.AFDPSEdit.setObjectName("AFDPSEdit")
        self.gridlayout5.addWidget(self.AFDPSEdit,3,3,1,1)

        self.LabelSpeedEdit = QtGui.QLabel(self.ItemInfoGrid)
        self.LabelSpeedEdit.setTextFormat(QtCore.Qt.PlainText)
        self.LabelSpeedEdit.setObjectName("LabelSpeedEdit")
        self.gridlayout5.addWidget(self.LabelSpeedEdit,4,0,1,1)

        self.SpeedEdit = QtGui.QLineEdit(self.ItemInfoGrid)
        self.SpeedEdit.setObjectName("SpeedEdit")
        self.gridlayout5.addWidget(self.SpeedEdit,4,1,1,1)

        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setMargin(0)
        self.hboxlayout3.setSpacing(0)
        self.hboxlayout3.setObjectName("hboxlayout3")

        spacerItem6 = QtGui.QSpacerItem(1,0,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem6)

        self.Offhand = QtGui.QCheckBox(self.ItemInfoGrid)
        self.Offhand.setObjectName("Offhand")
        self.hboxlayout3.addWidget(self.Offhand)
        self.gridlayout5.addLayout(self.hboxlayout3,4,2,1,2)

        self.LabelDamageType = QtGui.QLabel(self.ItemInfoGrid)
        self.LabelDamageType.setTextFormat(QtCore.Qt.PlainText)
        self.LabelDamageType.setObjectName("LabelDamageType")
        self.gridlayout5.addWidget(self.LabelDamageType,5,0,1,1)

        self.DamageType = SearchingCombo(self.ItemInfoGrid)
        self.DamageType.setObjectName("DamageType")
        self.gridlayout5.addWidget(self.DamageType,5,1,1,3)

        self.LabelItemRequirement = QtGui.QLabel(self.ItemInfoGrid)
        self.LabelItemRequirement.setTextFormat(QtCore.Qt.PlainText)
        self.LabelItemRequirement.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.LabelItemRequirement.setObjectName("LabelItemRequirement")
        self.gridlayout5.addWidget(self.LabelItemRequirement,6,0,1,4)

        self.ItemRequirement = QtGui.QLineEdit(self.ItemInfoGrid)
        self.ItemRequirement.setObjectName("ItemRequirement")
        self.gridlayout5.addWidget(self.ItemRequirement,7,0,1,4)

        spacerItem7 = QtGui.QSpacerItem(1,1,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.MinimumExpanding)
        self.gridlayout5.addItem(spacerItem7,8,0,1,4)

        self.LabelDBSource = QtGui.QLabel(self.ItemInfoGrid)
        self.LabelDBSource.setTextFormat(QtCore.Qt.PlainText)
        self.LabelDBSource.setObjectName("LabelDBSource")
        self.gridlayout5.addWidget(self.LabelDBSource,9,0,1,1)

        self.DBSource = QtGui.QLabel(self.ItemInfoGrid)
        self.DBSource.setTextFormat(QtCore.Qt.PlainText)
        self.DBSource.setObjectName("DBSource")
        self.gridlayout5.addWidget(self.DBSource,9,1,1,3)
        self.vboxlayout2.addWidget(self.ScrollItemInfo)
        self.hboxlayout2.addWidget(self.ItemInfoFrame)

        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setMargin(0)
        self.vboxlayout3.setSpacing(0)
        self.vboxlayout3.setObjectName("vboxlayout3")

        self.LabelClassRestrictionTable = QtGui.QLabel(self.ItemSummaryFrame)
        self.LabelClassRestrictionTable.setObjectName("LabelClassRestrictionTable")
        self.vboxlayout3.addWidget(self.LabelClassRestrictionTable)

        self.ClassRestrictionTable = QtGui.QListWidget(self.ItemSummaryFrame)
        self.ClassRestrictionTable.setObjectName("ClassRestrictionTable")
        self.vboxlayout3.addWidget(self.ClassRestrictionTable)
        self.hboxlayout2.addLayout(self.vboxlayout3)

        self.vboxlayout4 = QtGui.QVBoxLayout()
        self.vboxlayout4.setMargin(0)
        self.vboxlayout4.setSpacing(0)
        self.vboxlayout4.setObjectName("vboxlayout4")

        self.LabelItemNoteText = QtGui.QLabel(self.ItemSummaryFrame)
        self.LabelItemNoteText.setObjectName("LabelItemNoteText")
        self.vboxlayout4.addWidget(self.LabelItemNoteText)

        self.ItemNoteText = QtGui.QTextEdit(self.ItemSummaryFrame)
        self.ItemNoteText.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ItemNoteText.setTabChangesFocus(True)
        self.ItemNoteText.setAcceptRichText(False)
        self.ItemNoteText.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.ItemNoteText.setObjectName("ItemNoteText")
        self.vboxlayout4.addWidget(self.ItemNoteText)
        self.hboxlayout2.addLayout(self.vboxlayout4)

        self.vboxlayout5 = QtGui.QVBoxLayout()
        self.vboxlayout5.setMargin(0)
        self.vboxlayout5.setSpacing(0)
        self.vboxlayout5.setObjectName("vboxlayout5")

        self.LabelNoteText = QtGui.QLabel(self.ItemSummaryFrame)
        self.LabelNoteText.setObjectName("LabelNoteText")
        self.vboxlayout5.addWidget(self.LabelNoteText)

        self.NoteText = QtGui.QTextEdit(self.ItemSummaryFrame)
        self.NoteText.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.NoteText.setTabChangesFocus(True)
        self.NoteText.setAcceptRichText(False)
        self.NoteText.setTextInteractionFlags(QtCore.Qt.TextEditable)
        self.NoteText.setObjectName("NoteText")
        self.vboxlayout5.addWidget(self.NoteText)
        self.hboxlayout2.addLayout(self.vboxlayout5)
        self.stackedlayout.addWidget(self.ItemSummaryFrame)

        self.ItemSlotsFrame = QtGui.QWidget(self.GroupItemFrame)
        self.ItemSlotsFrame.setObjectName("ItemSlotsFrame")

        self.hboxlayout4 = QtGui.QHBoxLayout(self.ItemSlotsFrame)
        self.hboxlayout4.setMargin(0)
        self.hboxlayout4.setSpacing(9)
        self.hboxlayout4.setObjectName("hboxlayout4")

        self.vboxlayout6 = QtGui.QVBoxLayout()
        self.vboxlayout6.setMargin(0)
        self.vboxlayout6.setSpacing(0)
        self.vboxlayout6.setObjectName("vboxlayout6")

        self.ItemSlotsHeader = QtGui.QWidget(self.ItemSlotsFrame)
        self.ItemSlotsHeader.setObjectName("ItemSlotsHeader")

        self.gridlayout6 = QtGui.QGridLayout(self.ItemSlotsHeader)
        self.gridlayout6.setMargin(0)
        self.gridlayout6.setSpacing(0)
        self.gridlayout6.setObjectName("gridlayout6")

        spacerItem8 = QtGui.QSpacerItem(5,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem8,0,0,1,1)

        self.LabelGemType = QtGui.QLabel(self.ItemSlotsHeader)
        self.LabelGemType.setObjectName("LabelGemType")
        self.gridlayout6.addWidget(self.LabelGemType,0,1,1,1)

        self.LabelGemAmount = QtGui.QLabel(self.ItemSlotsHeader)
        self.LabelGemAmount.setObjectName("LabelGemAmount")
        self.gridlayout6.addWidget(self.LabelGemAmount,0,2,1,1)

        self.LabelGemEffect = QtGui.QLabel(self.ItemSlotsHeader)
        self.LabelGemEffect.setObjectName("LabelGemEffect")
        self.gridlayout6.addWidget(self.LabelGemEffect,0,3,1,1)

        self.LabelGemMakes = QtGui.QLabel(self.ItemSlotsHeader)
        self.LabelGemMakes.setObjectName("LabelGemMakes")
        self.gridlayout6.addWidget(self.LabelGemMakes,0,4,1,1)

        self.LabelRequirement = QtGui.QLabel(self.ItemSlotsHeader)
        self.LabelRequirement.setObjectName("LabelRequirement")
        self.gridlayout6.addWidget(self.LabelRequirement,0,4,1,3)

        self.LabelGemPoints = QtGui.QLabel(self.ItemSlotsHeader)
        self.LabelGemPoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelGemPoints.setObjectName("LabelGemPoints")
        self.gridlayout6.addWidget(self.LabelGemPoints,0,5,1,1)

        self.LabelGemCost = QtGui.QLabel(self.ItemSlotsHeader)
        self.LabelGemCost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelGemCost.setObjectName("LabelGemCost")
        self.gridlayout6.addWidget(self.LabelGemCost,0,6,1,1)

        spacerItem9 = QtGui.QSpacerItem(5,1,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem9,0,7,1,1)

        self.LabelGemName = QtGui.QLabel(self.ItemSlotsHeader)
        self.LabelGemName.setObjectName("LabelGemName")
        self.gridlayout6.addWidget(self.LabelGemName,0,8,1,1)
        self.vboxlayout6.addWidget(self.ItemSlotsHeader)

        self.ScrollSlots = ScrollArea(self.ItemSlotsFrame)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ScrollSlots.sizePolicy().hasHeightForWidth())
        self.ScrollSlots.setSizePolicy(sizePolicy)
        self.ScrollSlots.setFrameShape(QtGui.QFrame.NoFrame)
        self.ScrollSlots.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ScrollSlots.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ScrollSlots.setObjectName("ScrollSlots")

        self.ItemSlotsGrid = QtGui.QWidget(self.ScrollSlots)
        self.ItemSlotsGrid.setObjectName("ItemSlotsGrid")

        self.gridlayout7 = QtGui.QGridLayout(self.ItemSlotsGrid)
        self.gridlayout7.setMargin(0)
        self.gridlayout7.setSpacing(0)
        self.gridlayout7.setObjectName("gridlayout7")

        self.Gem_Label_1 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Gem_Label_1.setTextFormat(QtCore.Qt.PlainText)
        self.Gem_Label_1.setObjectName("Gem_Label_1")
        self.gridlayout7.addWidget(self.Gem_Label_1,0,0,1,1)

        self.Type_1 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_1.setObjectName("Type_1")
        self.gridlayout7.addWidget(self.Type_1,0,1,1,1)

        self.Amount_Edit_1 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_1.setObjectName("Amount_Edit_1")
        self.gridlayout7.addWidget(self.Amount_Edit_1,0,2,1,1)

        self.Amount_Drop_1 = SearchingCombo(self.ItemSlotsGrid)
        self.Amount_Drop_1.setObjectName("Amount_Drop_1")
        self.gridlayout7.addWidget(self.Amount_Drop_1,0,2,1,1)

        self.Effect_1 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_1.setEditable(True)
        self.Effect_1.setObjectName("Effect_1")
        self.gridlayout7.addWidget(self.Effect_1,0,3,1,1)

        self.Makes_1 = QtGui.QSpinBox(self.ItemSlotsGrid)
        self.Makes_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Makes_1.setObjectName("Makes_1")
        self.gridlayout7.addWidget(self.Makes_1,0,4,1,1)

        self.Requirement_1 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Requirement_1.setObjectName("Requirement_1")
        self.gridlayout7.addWidget(self.Requirement_1,0,4,1,3)

        self.Points_1 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Points_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Points_1.setObjectName("Points_1")
        self.gridlayout7.addWidget(self.Points_1,0,5,1,1)

        self.Cost_1 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Cost_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Cost_1.setObjectName("Cost_1")
        self.gridlayout7.addWidget(self.Cost_1,0,6,1,1)

        spacerItem10 = QtGui.QSpacerItem(5,1,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem10,0,7,12,1)

        self.Name_1 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Name_1.setObjectName("Name_1")
        self.gridlayout7.addWidget(self.Name_1,0,8,1,1)

        spacerItem11 = QtGui.QSpacerItem(5,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem11,0,8,4,1)

        self.Gem_Label_2 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Gem_Label_2.setTextFormat(QtCore.Qt.PlainText)
        self.Gem_Label_2.setObjectName("Gem_Label_2")
        self.gridlayout7.addWidget(self.Gem_Label_2,1,0,1,1)

        self.Type_2 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_2.setObjectName("Type_2")
        self.gridlayout7.addWidget(self.Type_2,1,1,1,1)

        self.Amount_Edit_2 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_2.setObjectName("Amount_Edit_2")
        self.gridlayout7.addWidget(self.Amount_Edit_2,1,2,1,1)

        self.Amount_Drop_2 = SearchingCombo(self.ItemSlotsGrid)
        self.Amount_Drop_2.setObjectName("Amount_Drop_2")
        self.gridlayout7.addWidget(self.Amount_Drop_2,1,2,1,1)

        self.Effect_2 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_2.setEditable(True)
        self.Effect_2.setObjectName("Effect_2")
        self.gridlayout7.addWidget(self.Effect_2,1,3,1,1)

        self.Makes_2 = QtGui.QSpinBox(self.ItemSlotsGrid)
        self.Makes_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Makes_2.setObjectName("Makes_2")
        self.gridlayout7.addWidget(self.Makes_2,1,4,1,1)

        self.Requirement_2 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Requirement_2.setObjectName("Requirement_2")
        self.gridlayout7.addWidget(self.Requirement_2,1,4,1,3)

        self.Points_2 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Points_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Points_2.setObjectName("Points_2")
        self.gridlayout7.addWidget(self.Points_2,1,5,1,1)

        self.Cost_2 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Cost_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Cost_2.setObjectName("Cost_2")
        self.gridlayout7.addWidget(self.Cost_2,1,6,1,1)

        self.Name_2 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Name_2.setObjectName("Name_2")
        self.gridlayout7.addWidget(self.Name_2,1,8,1,1)

        self.Gem_Label_3 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Gem_Label_3.setTextFormat(QtCore.Qt.PlainText)
        self.Gem_Label_3.setObjectName("Gem_Label_3")
        self.gridlayout7.addWidget(self.Gem_Label_3,2,0,1,1)

        self.Type_3 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_3.setObjectName("Type_3")
        self.gridlayout7.addWidget(self.Type_3,2,1,1,1)

        self.Amount_Edit_3 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_3.setObjectName("Amount_Edit_3")
        self.gridlayout7.addWidget(self.Amount_Edit_3,2,2,1,1)

        self.Amount_Drop_3 = SearchingCombo(self.ItemSlotsGrid)
        self.Amount_Drop_3.setObjectName("Amount_Drop_3")
        self.gridlayout7.addWidget(self.Amount_Drop_3,2,2,1,1)

        self.Effect_3 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_3.setEditable(True)
        self.Effect_3.setObjectName("Effect_3")
        self.gridlayout7.addWidget(self.Effect_3,2,3,1,1)

        self.Makes_3 = QtGui.QSpinBox(self.ItemSlotsGrid)
        self.Makes_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Makes_3.setObjectName("Makes_3")
        self.gridlayout7.addWidget(self.Makes_3,2,4,1,1)

        self.Requirement_3 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Requirement_3.setObjectName("Requirement_3")
        self.gridlayout7.addWidget(self.Requirement_3,2,4,1,3)

        self.Points_3 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Points_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Points_3.setObjectName("Points_3")
        self.gridlayout7.addWidget(self.Points_3,2,5,1,1)

        self.Cost_3 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Cost_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Cost_3.setObjectName("Cost_3")
        self.gridlayout7.addWidget(self.Cost_3,2,6,1,1)

        self.Name_3 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Name_3.setObjectName("Name_3")
        self.gridlayout7.addWidget(self.Name_3,2,8,1,1)

        self.Gem_Label_4 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Gem_Label_4.setTextFormat(QtCore.Qt.PlainText)
        self.Gem_Label_4.setObjectName("Gem_Label_4")
        self.gridlayout7.addWidget(self.Gem_Label_4,3,0,1,1)

        self.Type_4 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_4.setObjectName("Type_4")
        self.gridlayout7.addWidget(self.Type_4,3,1,1,1)

        self.Amount_Edit_4 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_4.setObjectName("Amount_Edit_4")
        self.gridlayout7.addWidget(self.Amount_Edit_4,3,2,1,1)

        self.Amount_Drop_4 = SearchingCombo(self.ItemSlotsGrid)
        self.Amount_Drop_4.setObjectName("Amount_Drop_4")
        self.gridlayout7.addWidget(self.Amount_Drop_4,3,2,1,1)

        self.Effect_4 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_4.setEditable(True)
        self.Effect_4.setObjectName("Effect_4")
        self.gridlayout7.addWidget(self.Effect_4,3,3,1,1)

        self.Makes_4 = QtGui.QSpinBox(self.ItemSlotsGrid)
        self.Makes_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Makes_4.setObjectName("Makes_4")
        self.gridlayout7.addWidget(self.Makes_4,3,4,1,1)

        self.Requirement_4 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Requirement_4.setObjectName("Requirement_4")
        self.gridlayout7.addWidget(self.Requirement_4,3,4,1,3)

        self.Points_4 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Points_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Points_4.setObjectName("Points_4")
        self.gridlayout7.addWidget(self.Points_4,3,5,1,1)

        self.Cost_4 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Cost_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Cost_4.setObjectName("Cost_4")
        self.gridlayout7.addWidget(self.Cost_4,3,6,1,1)

        self.Name_4 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Name_4.setObjectName("Name_4")
        self.gridlayout7.addWidget(self.Name_4,3,8,1,1)

        self.Gem_Label_5 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Gem_Label_5.setTextFormat(QtCore.Qt.PlainText)
        self.Gem_Label_5.setObjectName("Gem_Label_5")
        self.gridlayout7.addWidget(self.Gem_Label_5,4,0,1,1)

        self.Type_5 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_5.setObjectName("Type_5")
        self.gridlayout7.addWidget(self.Type_5,4,1,1,1)

        self.Amount_Edit_5 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_5.setObjectName("Amount_Edit_5")
        self.gridlayout7.addWidget(self.Amount_Edit_5,4,2,1,1)

        self.Amount_Drop_5 = SearchingCombo(self.ItemSlotsGrid)
        self.Amount_Drop_5.setObjectName("Amount_Drop_5")
        self.gridlayout7.addWidget(self.Amount_Drop_5,4,2,1,1)

        self.Effect_5 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_5.setEditable(True)
        self.Effect_5.setObjectName("Effect_5")
        self.gridlayout7.addWidget(self.Effect_5,4,3,1,1)

        self.Requirement_5 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Requirement_5.setObjectName("Requirement_5")
        self.gridlayout7.addWidget(self.Requirement_5,4,4,1,3)

        self.Name_5 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Name_5.setObjectName("Name_5")
        self.gridlayout7.addWidget(self.Name_5,4,8,1,1)

        spacerItem12 = QtGui.QSpacerItem(5,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem12,4,8,1,1)

        self.Gem_Label_6 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Gem_Label_6.setTextFormat(QtCore.Qt.PlainText)
        self.Gem_Label_6.setObjectName("Gem_Label_6")
        self.gridlayout7.addWidget(self.Gem_Label_6,5,0,1,1)

        self.Type_6 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_6.setObjectName("Type_6")
        self.gridlayout7.addWidget(self.Type_6,5,1,1,1)

        self.Amount_Edit_6 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_6.setObjectName("Amount_Edit_6")
        self.gridlayout7.addWidget(self.Amount_Edit_6,5,2,1,1)

        self.Amount_Drop_6 = SearchingCombo(self.ItemSlotsGrid)
        self.Amount_Drop_6.setObjectName("Amount_Drop_6")
        self.gridlayout7.addWidget(self.Amount_Drop_6,5,2,1,1)

        self.Effect_6 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_6.setEditable(True)
        self.Effect_6.setObjectName("Effect_6")
        self.gridlayout7.addWidget(self.Effect_6,5,3,1,1)

        self.Requirement_6 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Requirement_6.setObjectName("Requirement_6")
        self.gridlayout7.addWidget(self.Requirement_6,5,4,1,3)

        self.Name_6 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Name_6.setObjectName("Name_6")
        self.gridlayout7.addWidget(self.Name_6,5,8,1,1)

        spacerItem13 = QtGui.QSpacerItem(5,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem13,5,8,1,1)

        self.Gem_Label_7 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Gem_Label_7.setTextFormat(QtCore.Qt.PlainText)
        self.Gem_Label_7.setObjectName("Gem_Label_7")
        self.gridlayout7.addWidget(self.Gem_Label_7,6,0,1,1)

        self.Type_7 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_7.setObjectName("Type_7")
        self.gridlayout7.addWidget(self.Type_7,6,1,1,1)

        self.Amount_Edit_7 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_7.setObjectName("Amount_Edit_7")
        self.gridlayout7.addWidget(self.Amount_Edit_7,6,2,1,1)

        self.Effect_7 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_7.setEditable(True)
        self.Effect_7.setObjectName("Effect_7")
        self.gridlayout7.addWidget(self.Effect_7,6,3,1,1)

        self.Requirement_7 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Requirement_7.setObjectName("Requirement_7")
        self.gridlayout7.addWidget(self.Requirement_7,6,4,1,3)

        spacerItem14 = QtGui.QSpacerItem(5,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem14,6,8,1,1)

        self.Gem_Label_8 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Gem_Label_8.setTextFormat(QtCore.Qt.PlainText)
        self.Gem_Label_8.setObjectName("Gem_Label_8")
        self.gridlayout7.addWidget(self.Gem_Label_8,7,0,1,1)

        self.Type_8 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_8.setObjectName("Type_8")
        self.gridlayout7.addWidget(self.Type_8,7,1,1,1)

        self.Amount_Edit_8 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_8.setObjectName("Amount_Edit_8")
        self.gridlayout7.addWidget(self.Amount_Edit_8,7,2,1,1)

        self.Effect_8 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_8.setEditable(True)
        self.Effect_8.setObjectName("Effect_8")
        self.gridlayout7.addWidget(self.Effect_8,7,3,1,1)

        self.Requirement_8 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Requirement_8.setObjectName("Requirement_8")
        self.gridlayout7.addWidget(self.Requirement_8,7,4,1,3)

        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setMargin(0)
        self.hboxlayout5.setSpacing(0)
        self.hboxlayout5.setObjectName("hboxlayout5")

        self.ItemUtilityLabel = QtGui.QLabel(self.ItemSlotsGrid)
        self.ItemUtilityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ItemUtilityLabel.setObjectName("ItemUtilityLabel")
        self.hboxlayout5.addWidget(self.ItemUtilityLabel)

        self.ItemUtility = QtGui.QLabel(self.ItemSlotsGrid)
        self.ItemUtility.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ItemUtility.setObjectName("ItemUtility")
        self.hboxlayout5.addWidget(self.ItemUtility)

        spacerItem15 = QtGui.QSpacerItem(5,1,QtGui.QSizePolicy.MinimumExpanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem15)
        self.gridlayout7.addLayout(self.hboxlayout5,7,8,1,1)

        self.Gem_Label_9 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Gem_Label_9.setTextFormat(QtCore.Qt.PlainText)
        self.Gem_Label_9.setObjectName("Gem_Label_9")
        self.gridlayout7.addWidget(self.Gem_Label_9,8,0,1,1)

        self.Type_9 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_9.setObjectName("Type_9")
        self.gridlayout7.addWidget(self.Type_9,8,1,1,1)

        self.Amount_Edit_9 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_9.setObjectName("Amount_Edit_9")
        self.gridlayout7.addWidget(self.Amount_Edit_9,8,2,1,1)

        self.Effect_9 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_9.setEditable(True)
        self.Effect_9.setObjectName("Effect_9")
        self.gridlayout7.addWidget(self.Effect_9,8,3,1,1)

        self.Requirement_9 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Requirement_9.setObjectName("Requirement_9")
        self.gridlayout7.addWidget(self.Requirement_9,8,4,1,3)

        spacerItem16 = QtGui.QSpacerItem(5,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem16,8,8,1,4)

        self.Gem_Label_10 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Gem_Label_10.setTextFormat(QtCore.Qt.PlainText)
        self.Gem_Label_10.setObjectName("Gem_Label_10")
        self.gridlayout7.addWidget(self.Gem_Label_10,9,0,1,1)

        self.Type_10 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_10.setObjectName("Type_10")
        self.gridlayout7.addWidget(self.Type_10,9,1,1,1)

        self.Amount_Edit_10 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_10.setObjectName("Amount_Edit_10")
        self.gridlayout7.addWidget(self.Amount_Edit_10,9,2,1,1)

        self.Effect_10 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_10.setEditable(True)
        self.Effect_10.setObjectName("Effect_10")
        self.gridlayout7.addWidget(self.Effect_10,9,3,1,1)

        self.Requirement_10 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Requirement_10.setObjectName("Requirement_10")
        self.gridlayout7.addWidget(self.Requirement_10,9,4,1,3)

        self.Gem_Label_11 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Gem_Label_11.setTextFormat(QtCore.Qt.PlainText)
        self.Gem_Label_11.setObjectName("Gem_Label_11")
        self.gridlayout7.addWidget(self.Gem_Label_11,10,0,1,1)

        self.Type_11 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_11.setObjectName("Type_11")
        self.gridlayout7.addWidget(self.Type_11,10,1,1,1)

        self.Amount_Edit_11 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_11.setObjectName("Amount_Edit_11")
        self.gridlayout7.addWidget(self.Amount_Edit_11,10,2,1,1)

        self.Effect_11 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_11.setEditable(True)
        self.Effect_11.setObjectName("Effect_11")
        self.gridlayout7.addWidget(self.Effect_11,10,3,1,1)

        self.Requirement_11 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Requirement_11.setObjectName("Requirement_11")
        self.gridlayout7.addWidget(self.Requirement_11,10,4,1,3)

        self.Gem_Label_12 = QtGui.QLabel(self.ItemSlotsGrid)
        self.Gem_Label_12.setTextFormat(QtCore.Qt.PlainText)
        self.Gem_Label_12.setObjectName("Gem_Label_12")
        self.gridlayout7.addWidget(self.Gem_Label_12,11,0,1,1)

        self.Type_12 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_12.setObjectName("Type_12")
        self.gridlayout7.addWidget(self.Type_12,11,1,1,1)

        self.Amount_Edit_12 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_12.setObjectName("Amount_Edit_12")
        self.gridlayout7.addWidget(self.Amount_Edit_12,11,2,1,1)

        self.Effect_12 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_12.setEditable(True)
        self.Effect_12.setObjectName("Effect_12")
        self.gridlayout7.addWidget(self.Effect_12,11,3,1,1)

        self.Requirement_12 = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.Requirement_12.setObjectName("Requirement_12")
        self.gridlayout7.addWidget(self.Requirement_12,11,4,1,3)

        spacerItem17 = QtGui.QSpacerItem(5,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem17,5,0,1,7)

        spacerItem18 = QtGui.QSpacerItem(5,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem18,6,0,1,3)

        spacerItem19 = QtGui.QSpacerItem(5,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem19,6,3,1,4)

        spacerItem20 = QtGui.QSpacerItem(5,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem20,7,0,1,1)

        self.LabelItemCraftTime = QtGui.QLabel(self.ItemSlotsGrid)
        self.LabelItemCraftTime.setTextFormat(QtCore.Qt.PlainText)
        self.LabelItemCraftTime.setObjectName("LabelItemCraftTime")
        self.gridlayout7.addWidget(self.LabelItemCraftTime,7,1,1,1)

        self.ItemCraftTime = QtGui.QLineEdit(self.ItemSlotsGrid)
        self.ItemCraftTime.setObjectName("ItemCraftTime")
        self.gridlayout7.addWidget(self.ItemCraftTime,7,2,1,1)

        self.ItemImbueLabel = QtGui.QLabel(self.ItemSlotsGrid)
        self.ItemImbueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ItemImbueLabel.setObjectName("ItemImbueLabel")
        self.gridlayout7.addWidget(self.ItemImbueLabel,7,3,1,2)

        self.ItemImbue = QtGui.QLabel(self.ItemSlotsGrid)
        self.ItemImbue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ItemImbue.setObjectName("ItemImbue")
        self.gridlayout7.addWidget(self.ItemImbue,7,5,1,1)

        self.ItemImbueTotal = QtGui.QLabel(self.ItemSlotsGrid)
        self.ItemImbueTotal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ItemImbueTotal.setObjectName("ItemImbueTotal")
        self.gridlayout7.addWidget(self.ItemImbueTotal,7,6,1,1)

        spacerItem21 = QtGui.QSpacerItem(5,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem21,8,0,4,3)

        self.ItemOverchargeLabel = QtGui.QLabel(self.ItemSlotsGrid)
        self.ItemOverchargeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ItemOverchargeLabel.setObjectName("ItemOverchargeLabel")
        self.gridlayout7.addWidget(self.ItemOverchargeLabel,8,3,1,2)

        self.ItemOvercharge = QtGui.QLabel(self.ItemSlotsGrid)
        self.ItemOvercharge.setAlignment(QtCore.Qt.AlignCenter)
        self.ItemOvercharge.setObjectName("ItemOvercharge")
        self.gridlayout7.addWidget(self.ItemOvercharge,8,5,1,2)

        self.ItemCostLabel = QtGui.QLabel(self.ItemSlotsGrid)
        self.ItemCostLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ItemCostLabel.setObjectName("ItemCostLabel")
        self.gridlayout7.addWidget(self.ItemCostLabel,9,3,1,2)

        self.ItemCost = QtGui.QLabel(self.ItemSlotsGrid)
        self.ItemCost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ItemCost.setObjectName("ItemCost")
        self.gridlayout7.addWidget(self.ItemCost,9,5,1,2)

        self.ItemPriceLabel = QtGui.QLabel(self.ItemSlotsGrid)
        self.ItemPriceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ItemPriceLabel.setObjectName("ItemPriceLabel")
        self.gridlayout7.addWidget(self.ItemPriceLabel,10,3,1,2)

        self.ItemPrice = QtGui.QLabel(self.ItemSlotsGrid)
        self.ItemPrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ItemPrice.setObjectName("ItemPrice")
        self.gridlayout7.addWidget(self.ItemPrice,10,5,1,2)

        spacerItem22 = QtGui.QSpacerItem(5,5,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem22,11,0,1,7)

        spacerItem23 = QtGui.QSpacerItem(1,0,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.MinimumExpanding)
        self.gridlayout7.addItem(spacerItem23,12,0,1,9)
        self.vboxlayout6.addWidget(self.ScrollSlots)
        self.hboxlayout4.addLayout(self.vboxlayout6)
        self.stackedlayout.addWidget(self.ItemSlotsFrame)
        self.vboxlayout1.addLayout(self.stackedlayout)
        self.vboxlayout.addWidget(self.GroupItemFrame)
        self.gridlayout.addLayout(self.vboxlayout,1,0,1,4)
        B_SC.setCentralWidget(self.ScWinFrame)
        self.LabelCharName.setBuddy(self.CharName)
        self.LabelOutfitName.setBuddy(self.OutfitName)
        self.ItemLevelLabel.setBuddy(self.ItemLevel)
        self.ItemNameLabel.setBuddy(self.ItemNameCombo)

        self.retranslateUi(B_SC)
        QtCore.QMetaObject.connectSlotsByName(B_SC)
        B_SC.setTabOrder(self.CharName,self.Realm)
        B_SC.setTabOrder(self.Realm,self.CharClass)
        B_SC.setTabOrder(self.CharClass,self.CharRace)
        B_SC.setTabOrder(self.CharRace,self.CharLevel)
        B_SC.setTabOrder(self.CharLevel,self.RealmRank)
        B_SC.setTabOrder(self.RealmRank,self.CraftTime)
        B_SC.setTabOrder(self.CraftTime,self.ChampionLevel)
        B_SC.setTabOrder(self.ChampionLevel,self.OutfitName)
        B_SC.setTabOrder(self.OutfitName,self.PieceTab)
        B_SC.setTabOrder(self.PieceTab,self.ItemLevel)
        B_SC.setTabOrder(self.ItemLevel,self.ItemLevelButton)
        B_SC.setTabOrder(self.ItemLevelButton,self.QualEdit)
        B_SC.setTabOrder(self.QualEdit,self.QualDrop)
        B_SC.setTabOrder(self.QualDrop,self.ItemNameCombo)
        B_SC.setTabOrder(self.ItemNameCombo,self.Equipped)
        B_SC.setTabOrder(self.Equipped,self.ToggleItemView)
        B_SC.setTabOrder(self.ToggleItemView,self.ItemRealm)
        B_SC.setTabOrder(self.ItemRealm,self.ItemType)
        B_SC.setTabOrder(self.ItemType,self.ItemSource)
        B_SC.setTabOrder(self.ItemSource,self.BonusEdit)
        B_SC.setTabOrder(self.BonusEdit,self.AFDPSEdit)
        B_SC.setTabOrder(self.AFDPSEdit,self.SpeedEdit)
        B_SC.setTabOrder(self.SpeedEdit,self.Offhand)
        B_SC.setTabOrder(self.Offhand,self.DamageType)
        B_SC.setTabOrder(self.DamageType,self.ItemRequirement)
        B_SC.setTabOrder(self.ItemRequirement,self.ClassRestrictionTable)
        B_SC.setTabOrder(self.ClassRestrictionTable,self.ItemNoteText)
        B_SC.setTabOrder(self.ItemNoteText,self.NoteText)
        B_SC.setTabOrder(self.NoteText,self.Type_1)
        B_SC.setTabOrder(self.Type_1,self.Amount_Edit_1)
        B_SC.setTabOrder(self.Amount_Edit_1,self.Amount_Drop_1)
        B_SC.setTabOrder(self.Amount_Drop_1,self.Effect_1)
        B_SC.setTabOrder(self.Effect_1,self.Makes_1)
        B_SC.setTabOrder(self.Makes_1,self.Requirement_1)
        B_SC.setTabOrder(self.Requirement_1,self.Type_2)
        B_SC.setTabOrder(self.Type_2,self.Amount_Edit_2)
        B_SC.setTabOrder(self.Amount_Edit_2,self.Amount_Drop_2)
        B_SC.setTabOrder(self.Amount_Drop_2,self.Effect_2)
        B_SC.setTabOrder(self.Effect_2,self.Makes_2)
        B_SC.setTabOrder(self.Makes_2,self.Requirement_2)
        B_SC.setTabOrder(self.Requirement_2,self.Type_3)
        B_SC.setTabOrder(self.Type_3,self.Amount_Edit_3)
        B_SC.setTabOrder(self.Amount_Edit_3,self.Amount_Drop_3)
        B_SC.setTabOrder(self.Amount_Drop_3,self.Effect_3)
        B_SC.setTabOrder(self.Effect_3,self.Makes_3)
        B_SC.setTabOrder(self.Makes_3,self.Requirement_3)
        B_SC.setTabOrder(self.Requirement_3,self.Type_4)
        B_SC.setTabOrder(self.Type_4,self.Amount_Edit_4)
        B_SC.setTabOrder(self.Amount_Edit_4,self.Amount_Drop_4)
        B_SC.setTabOrder(self.Amount_Drop_4,self.Effect_4)
        B_SC.setTabOrder(self.Effect_4,self.Makes_4)
        B_SC.setTabOrder(self.Makes_4,self.Requirement_4)
        B_SC.setTabOrder(self.Requirement_4,self.Type_5)
        B_SC.setTabOrder(self.Type_5,self.Amount_Edit_5)
        B_SC.setTabOrder(self.Amount_Edit_5,self.Amount_Drop_5)
        B_SC.setTabOrder(self.Amount_Drop_5,self.Effect_5)
        B_SC.setTabOrder(self.Effect_5,self.Requirement_5)
        B_SC.setTabOrder(self.Requirement_5,self.Type_6)
        B_SC.setTabOrder(self.Type_6,self.Amount_Edit_6)
        B_SC.setTabOrder(self.Amount_Edit_6,self.Amount_Drop_6)
        B_SC.setTabOrder(self.Amount_Drop_6,self.Effect_6)
        B_SC.setTabOrder(self.Effect_6,self.Requirement_6)
        B_SC.setTabOrder(self.Requirement_6,self.Type_7)
        B_SC.setTabOrder(self.Type_7,self.Amount_Edit_7)
        B_SC.setTabOrder(self.Amount_Edit_7,self.Effect_7)
        B_SC.setTabOrder(self.Effect_7,self.Requirement_7)
        B_SC.setTabOrder(self.Requirement_7,self.Type_8)
        B_SC.setTabOrder(self.Type_8,self.Amount_Edit_8)
        B_SC.setTabOrder(self.Amount_Edit_8,self.Effect_8)
        B_SC.setTabOrder(self.Effect_8,self.Requirement_8)
        B_SC.setTabOrder(self.Requirement_8,self.Type_9)
        B_SC.setTabOrder(self.Type_9,self.Amount_Edit_9)
        B_SC.setTabOrder(self.Amount_Edit_9,self.Effect_9)
        B_SC.setTabOrder(self.Effect_9,self.Requirement_9)
        B_SC.setTabOrder(self.Requirement_9,self.Type_10)
        B_SC.setTabOrder(self.Type_10,self.Amount_Edit_10)
        B_SC.setTabOrder(self.Amount_Edit_10,self.Effect_10)
        B_SC.setTabOrder(self.Effect_10,self.Requirement_10)
        B_SC.setTabOrder(self.Requirement_10,self.Type_11)
        B_SC.setTabOrder(self.Type_11,self.Amount_Edit_11)
        B_SC.setTabOrder(self.Amount_Edit_11,self.Effect_11)
        B_SC.setTabOrder(self.Effect_11,self.Requirement_11)
        B_SC.setTabOrder(self.Requirement_11,self.Type_12)
        B_SC.setTabOrder(self.Type_12,self.Amount_Edit_12)
        B_SC.setTabOrder(self.Amount_Edit_12,self.Effect_12)
        B_SC.setTabOrder(self.Effect_12,self.Requirement_12)
        B_SC.setTabOrder(self.Requirement_12,self.ItemCraftTime)
        B_SC.setTabOrder(self.ItemCraftTime,self.SkillsList)

    def retranslateUi(self, B_SC):
        B_SC.setWindowTitle(QtGui.QApplication.translate("B_SC", "Spellcrafting Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelCharName.setText(QtGui.QApplication.translate("B_SC", "&Name: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelRealm.setText(QtGui.QApplication.translate("B_SC", "Realm: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelCharClass.setText(QtGui.QApplication.translate("B_SC", "Class: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelCharRace.setText(QtGui.QApplication.translate("B_SC", "Race: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelCharLevel.setText(QtGui.QApplication.translate("B_SC", "Level: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelRealmRank.setText(QtGui.QApplication.translate("B_SC", "RR: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelCraftTime.setText(QtGui.QApplication.translate("B_SC", "Time: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelChampionLevel.setText(QtGui.QApplication.translate("B_SC", "CL: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelOutfitName.setText(QtGui.QApplication.translate("B_SC", "&Outfit: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelTotalCost.setText(QtGui.QApplication.translate("B_SC", "Cost: ", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalCost.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelTotalPrice.setText(QtGui.QApplication.translate("B_SC", "Price: ", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalPrice.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.StrengthLabel.setText(QtGui.QApplication.translate("B_SC", "STR: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Strength.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.StrengthCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.ConstitutionLabel.setText(QtGui.QApplication.translate("B_SC", "CON: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Constitution.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.ConstitutionCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.DexterityLabel.setText(QtGui.QApplication.translate("B_SC", "DEX: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Dexterity.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.DexterityCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.QuicknessLabel.setText(QtGui.QApplication.translate("B_SC", "QUI: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Quickness.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.QuicknessCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.IntelligenceLabel.setText(QtGui.QApplication.translate("B_SC", "INT: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Intelligence.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.IntelligenceCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.PietyLabel.setText(QtGui.QApplication.translate("B_SC", "PIE: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Piety.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.PietyCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.CharismaLabel.setText(QtGui.QApplication.translate("B_SC", "CHA: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Charisma.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.CharismaCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.EmpathyLabel.setText(QtGui.QApplication.translate("B_SC", "EMP: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Empathy.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.EmpathyCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.AcuityLabel.setText(QtGui.QApplication.translate("B_SC", "ACU: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Acuity.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.AcuityCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.PowerLabel.setText(QtGui.QApplication.translate("B_SC", "Pow: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Power.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.PowerCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.PowerPoolLabel.setText(QtGui.QApplication.translate("B_SC", "PP%: ", None, QtGui.QApplication.UnicodeUTF8))
        self.PowerPool.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.PowerPoolCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.FatigueLabel.setText(QtGui.QApplication.translate("B_SC", "End: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Fatigue.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.FatigueCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.AFLabel.setText(QtGui.QApplication.translate("B_SC", "AF: ", None, QtGui.QApplication.UnicodeUTF8))
        self.AF.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.AFCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.HitsLabel.setText(QtGui.QApplication.translate("B_SC", "Hits: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Hits.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.HitsCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelTotalUtility.setText(QtGui.QApplication.translate("B_SC", "Utility: ", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalUtility.setText(QtGui.QApplication.translate("B_SC", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.BodyLabel.setText(QtGui.QApplication.translate("B_SC", "Body: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Body.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.BodyCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.ColdLabel.setText(QtGui.QApplication.translate("B_SC", "Cold: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Cold.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.ColdCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.HeatLabel.setText(QtGui.QApplication.translate("B_SC", "Heat: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Heat.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.HeatCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.EnergyLabel.setText(QtGui.QApplication.translate("B_SC", "Energy: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Energy.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.EnergyCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.MatterLabel.setText(QtGui.QApplication.translate("B_SC", "Matter: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Matter.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.MatterCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.SpiritLabel.setText(QtGui.QApplication.translate("B_SC", "Spirit: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Spirit.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.SpiritCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.CrushLabel.setText(QtGui.QApplication.translate("B_SC", "Crush: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Crush.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.CrushCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.ThrustLabel.setText(QtGui.QApplication.translate("B_SC", "Thrust: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Thrust.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.ThrustCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.SlashLabel.setText(QtGui.QApplication.translate("B_SC", "Slash: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Slash.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.SlashCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.EssenceLabel.setText(QtGui.QApplication.translate("B_SC", "Essence: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Essence.setText(QtGui.QApplication.translate("B_SC", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.EssenceCap.setText(QtGui.QApplication.translate("B_SC", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemLevelLabel.setText(QtGui.QApplication.translate("B_SC", "&Level: ", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemLevelButton.setText(QtGui.QApplication.translate("B_SC", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemQualityLabel.setText(QtGui.QApplication.translate("B_SC", "Quality: ", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemNameLabel.setText(QtGui.QApplication.translate("B_SC", "Item &Name: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Equipped.setText(QtGui.QApplication.translate("B_SC", "Equi&pped", None, QtGui.QApplication.UnicodeUTF8))
        self.ToggleItemView.setText(QtGui.QApplication.translate("B_SC", "Item Slots", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelItemInfo.setText(QtGui.QApplication.translate("B_SC", "Item Information:", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelItemRealm.setText(QtGui.QApplication.translate("B_SC", "Realm: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelItemType.setText(QtGui.QApplication.translate("B_SC", "Type: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelItemSource.setText(QtGui.QApplication.translate("B_SC", "Origin: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelBonusEdit.setText(QtGui.QApplication.translate("B_SC", "Bonus: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelAFDPSEdit.setText(QtGui.QApplication.translate("B_SC", "DPS: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelSpeedEdit.setText(QtGui.QApplication.translate("B_SC", "Speed: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Offhand.setText(QtGui.QApplication.translate("B_SC", "Offhand", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelDamageType.setText(QtGui.QApplication.translate("B_SC", "Damage: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelItemRequirement.setText(QtGui.QApplication.translate("B_SC", "Requirement: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelDBSource.setText(QtGui.QApplication.translate("B_SC", "Source: ", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelClassRestrictionTable.setText(QtGui.QApplication.translate("B_SC", "Class Restrictions:", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelItemNoteText.setText(QtGui.QApplication.translate("B_SC", "Item Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelNoteText.setText(QtGui.QApplication.translate("B_SC", "Template Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelGemType.setText(QtGui.QApplication.translate("B_SC", " Type", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelGemAmount.setText(QtGui.QApplication.translate("B_SC", " Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelGemEffect.setText(QtGui.QApplication.translate("B_SC", " Effect", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelGemMakes.setText(QtGui.QApplication.translate("B_SC", " Makes", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelRequirement.setText(QtGui.QApplication.translate("B_SC", " Requirement", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelGemPoints.setText(QtGui.QApplication.translate("B_SC", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelGemCost.setText(QtGui.QApplication.translate("B_SC", "Unit Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelGemName.setText(QtGui.QApplication.translate("B_SC", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.Gem_Label_1.setText(QtGui.QApplication.translate("B_SC", "Slot &1: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Makes_1.setSpecialValueText(QtGui.QApplication.translate("B_SC", " ", None, QtGui.QApplication.UnicodeUTF8))
        self.Points_1.setText(QtGui.QApplication.translate("B_SC", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.Cost_1.setText(QtGui.QApplication.translate("B_SC", "0c", None, QtGui.QApplication.UnicodeUTF8))
        self.Gem_Label_2.setText(QtGui.QApplication.translate("B_SC", "Slot &2: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Makes_2.setSpecialValueText(QtGui.QApplication.translate("B_SC", " ", None, QtGui.QApplication.UnicodeUTF8))
        self.Points_2.setText(QtGui.QApplication.translate("B_SC", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.Cost_2.setText(QtGui.QApplication.translate("B_SC", "0c", None, QtGui.QApplication.UnicodeUTF8))
        self.Gem_Label_3.setText(QtGui.QApplication.translate("B_SC", "Slot &3: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Makes_3.setSpecialValueText(QtGui.QApplication.translate("B_SC", " ", None, QtGui.QApplication.UnicodeUTF8))
        self.Points_3.setText(QtGui.QApplication.translate("B_SC", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.Cost_3.setText(QtGui.QApplication.translate("B_SC", "0c", None, QtGui.QApplication.UnicodeUTF8))
        self.Gem_Label_4.setText(QtGui.QApplication.translate("B_SC", "Slot &4: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Makes_4.setSpecialValueText(QtGui.QApplication.translate("B_SC", " ", None, QtGui.QApplication.UnicodeUTF8))
        self.Points_4.setText(QtGui.QApplication.translate("B_SC", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.Cost_4.setText(QtGui.QApplication.translate("B_SC", "0c", None, QtGui.QApplication.UnicodeUTF8))
        self.Gem_Label_5.setText(QtGui.QApplication.translate("B_SC", "Slot &5: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Gem_Label_6.setText(QtGui.QApplication.translate("B_SC", "Slot &6: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Gem_Label_7.setText(QtGui.QApplication.translate("B_SC", "Slot &7: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Gem_Label_8.setText(QtGui.QApplication.translate("B_SC", "Slot &8: ", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemUtilityLabel.setText(QtGui.QApplication.translate("B_SC", "Utility:   ", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemUtility.setText(QtGui.QApplication.translate("B_SC", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.Gem_Label_9.setText(QtGui.QApplication.translate("B_SC", "Slot &9: ", None, QtGui.QApplication.UnicodeUTF8))
        self.Gem_Label_10.setText(QtGui.QApplication.translate("B_SC", "Slot 1&0:", None, QtGui.QApplication.UnicodeUTF8))
        self.Gem_Label_11.setText(QtGui.QApplication.translate("B_SC", "Slot 11&- ", None, QtGui.QApplication.UnicodeUTF8))
        self.Gem_Label_12.setText(QtGui.QApplication.translate("B_SC", "Slot 12&=", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelItemCraftTime.setText(QtGui.QApplication.translate("B_SC", "Item SC Time (min): ", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemImbueLabel.setText(QtGui.QApplication.translate("B_SC", "Imbue Points: ", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemImbue.setText(QtGui.QApplication.translate("B_SC", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemImbueTotal.setText(QtGui.QApplication.translate("B_SC", " / 0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemOverchargeLabel.setText(QtGui.QApplication.translate("B_SC", "Overcharge: ", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemOvercharge.setText(QtGui.QApplication.translate("B_SC", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemCostLabel.setText(QtGui.QApplication.translate("B_SC", "Item Cost: ", None, QtGui.QApplication.UnicodeUTF8))
        self.ItemPriceLabel.setText(QtGui.QApplication.translate("B_SC", "Item Price: ", None, QtGui.QApplication.UnicodeUTF8))

from SearchingCombo import SearchingCombo
from MultiTabBar import MultiTabFrame, MultiTabBar
from GroupFrame import GroupFrame
from SkillsView import SkillsView
from ScrollArea import ScrollArea
