# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScWindow.ui'
#
# Created: Sat Jun 09 02:58:32 2007
#      by: PyQt4 UI code generator 4.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5.QtCore import QMetaObject, QRect, QSize, Qt
from PyQt5.QtWidgets import QAbstractItemView, QApplication, QCheckBox, QComboBox, QFrame, QGridLayout
from PyQt5.QtWidgets import QHBoxLayout, QListView, QListWidget, QLabel, QLineEdit, QPushButton, QSizePolicy
from PyQt5.QtWidgets import QSpacerItem, QSpinBox, QStackedLayout, QTextEdit, QVBoxLayout, QWidget
from SearchingCombo import SearchingCombo
from MultiTabBar import MultiTabFrame, MultiTabBar
from GroupFrame import GroupFrame
from SkillsView import SkillsView
from ScrollArea import ScrollArea


class UI_B_SCWindow(object):
    def setupUi(self, B_SCWindow):
        B_SCWindow.setObjectName("B_SCWindow")
        B_SCWindow.resize(QSize(QRect(0, 0, 761, 510).size()).expandedTo(B_SCWindow.minimumSizeHint()))

        self.ScWinFrame = QWidget(B_SCWindow)
        self.ScWinFrame.setObjectName("ScWinFrame")

        self.gridlayout = QGridLayout(self.ScWinFrame)
        self.gridlayout.setContentsMargins(3, 3, 3, 3)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName("gridlayout")

        self.GroupCharInfo = GroupFrame(self.ScWinFrame)
        self.GroupCharInfo.setFrameShape(QFrame.StyledPanel)
        self.GroupCharInfo.setLineWidth(1)
        self.GroupCharInfo.setObjectName("GroupCharInfo")

        self.gridlayout1 = QGridLayout(self.GroupCharInfo)
        self.gridlayout1.setContentsMargins(4, 4, 4, 4)
        self.gridlayout1.setSpacing(0)
        self.gridlayout1.setObjectName("gridlayout1")

        self.LabelCharName = QLabel(self.GroupCharInfo)
        self.LabelCharName.setTextFormat(Qt.PlainText)
        self.LabelCharName.setObjectName("LabelCharName")
        self.gridlayout1.addWidget(self.LabelCharName, 0, 0, 1, 1)

        self.CharName = QLineEdit(self.GroupCharInfo)
        self.CharName.setObjectName("CharName")
        self.gridlayout1.addWidget(self.CharName, 0, 1, 1, 3)

        self.LabelRealm = QLabel(self.GroupCharInfo)
        self.LabelRealm.setTextFormat(Qt.PlainText)
        self.LabelRealm.setObjectName("LabelRealm")
        self.gridlayout1.addWidget(self.LabelRealm, 1, 0, 1, 1)

        self.Realm = SearchingCombo(self.GroupCharInfo)
        self.Realm.setObjectName("Realm")
        self.gridlayout1.addWidget(self.Realm, 1, 1, 1, 3)

        self.LabelCharClass = QLabel(self.GroupCharInfo)
        self.LabelCharClass.setTextFormat(Qt.PlainText)
        self.LabelCharClass.setObjectName("LabelCharClass")
        self.gridlayout1.addWidget(self.LabelCharClass, 2, 0, 1, 1)

        self.CharClass = SearchingCombo(self.GroupCharInfo)
        self.CharClass.setObjectName("CharClass")
        self.gridlayout1.addWidget(self.CharClass, 2, 1, 1, 3)

        self.LabelCharRace = QLabel(self.GroupCharInfo)
        self.LabelCharRace.setTextFormat(Qt.PlainText)
        self.LabelCharRace.setObjectName("LabelCharRace")
        self.gridlayout1.addWidget(self.LabelCharRace, 3, 0, 1, 1)

        self.CharRace = SearchingCombo(self.GroupCharInfo)
        self.CharRace.setObjectName("CharRace")
        self.gridlayout1.addWidget(self.CharRace, 3, 1, 1, 3)

        self.LabelCharLevel = QLabel(self.GroupCharInfo)
        self.LabelCharLevel.setTextFormat(Qt.PlainText)
        self.LabelCharLevel.setObjectName("LabelCharLevel")
        self.gridlayout1.addWidget(self.LabelCharLevel, 4, 0, 1, 1)

        self.CharLevel = QLineEdit(self.GroupCharInfo)
        self.CharLevel.setObjectName("CharLevel")
        self.gridlayout1.addWidget(self.CharLevel, 4, 1, 1, 1)

        self.LabelRealmRank = QLabel(self.GroupCharInfo)
        self.LabelRealmRank.setTextFormat(Qt.PlainText)
        self.LabelRealmRank.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.LabelRealmRank.setObjectName("LabelRealmRank")
        self.gridlayout1.addWidget(self.LabelRealmRank, 4, 2, 1, 1)

        self.RealmRank = QLineEdit(self.GroupCharInfo)
        self.RealmRank.setObjectName("RealmRank")
        self.gridlayout1.addWidget(self.RealmRank, 4, 3, 1, 1)

        self.LabelCraftTime = QLabel(self.GroupCharInfo)
        self.LabelCraftTime.setTextFormat(Qt.PlainText)
        self.LabelCraftTime.setObjectName("LabelCraftTime")
        self.gridlayout1.addWidget(self.LabelCraftTime, 5, 0, 1, 1)

        self.CraftTime = QLineEdit(self.GroupCharInfo)
        self.CraftTime.setObjectName("CraftTime")
        self.gridlayout1.addWidget(self.CraftTime, 5, 1, 1, 1)

        self.LabelChampionLevel = QLabel(self.GroupCharInfo)
        self.LabelChampionLevel.setTextFormat(Qt.PlainText)
        self.LabelChampionLevel.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.LabelChampionLevel.setObjectName("LabelChampionLevel")
        self.gridlayout1.addWidget(self.LabelChampionLevel, 5, 2, 1, 1)

        self.ChampionLevel = QLineEdit(self.GroupCharInfo)
        self.ChampionLevel.setObjectName("ChampionLevel")
        self.gridlayout1.addWidget(self.ChampionLevel, 5, 3, 1, 1)

        self.LabelOutfitName = QLabel(self.GroupCharInfo)
        self.LabelOutfitName.setTextFormat(Qt.PlainText)
        self.LabelOutfitName.setObjectName("LabelOutfitName")
        self.gridlayout1.addWidget(self.LabelOutfitName, 6, 0, 1, 1)

        self.OutfitName = SearchingCombo(self.GroupCharInfo)
        self.OutfitName.setEditable(True)
        self.OutfitName.setInsertPolicy(QComboBox.NoInsert)
        self.OutfitName.setDuplicatesEnabled(True)
        self.OutfitName.setObjectName("OutfitName")
        self.gridlayout1.addWidget(self.OutfitName, 6, 1, 1, 3)

        spacerItem = QSpacerItem(1, 3, QSizePolicy.Minimum, QSizePolicy.Fixed)
        self.gridlayout1.addItem(spacerItem, 7, 0, 1, 4)

        self.LabelTotalCost = QLabel(self.GroupCharInfo)
        self.LabelTotalCost.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.LabelTotalCost.setObjectName("LabelTotalCost")
        self.gridlayout1.addWidget(self.LabelTotalCost, 8, 0, 1, 1)

        self.TotalCost = QLabel(self.GroupCharInfo)
        self.TotalCost.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.TotalCost.setObjectName("TotalCost")
        self.gridlayout1.addWidget(self.TotalCost, 8, 1, 1, 3)

        self.LabelTotalPrice = QLabel(self.GroupCharInfo)
        self.LabelTotalPrice.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.LabelTotalPrice.setObjectName("LabelTotalPrice")
        self.gridlayout1.addWidget(self.LabelTotalPrice, 9, 0, 1, 1)

        self.TotalPrice = QLabel(self.GroupCharInfo)
        self.TotalPrice.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.TotalPrice.setObjectName("TotalPrice")
        self.gridlayout1.addWidget(self.TotalPrice, 9, 1, 1, 3)

        spacerItem1 = QSpacerItem(1, 0, QSizePolicy.Minimum, QSizePolicy.MinimumExpanding)
        self.gridlayout1.addItem(spacerItem1, 10, 0, 1, 4)
        self.gridlayout.addWidget(self.GroupCharInfo, 0, 0, 1, 1)

        self.GroupStats = GroupFrame(self.ScWinFrame)
        self.GroupStats.setFrameShape(QFrame.StyledPanel)
        self.GroupStats.setLineWidth(1)
        self.GroupStats.setObjectName("GroupStats")

        self.gridlayout2 = QGridLayout(self.GroupStats)
        self.gridlayout2.setContentsMargins(4, 4, 4, 4)
        self.gridlayout2.setSpacing(0)
        self.gridlayout2.setObjectName("gridlayout2")

        self.StrengthLabel = QLabel(self.GroupStats)
        self.StrengthLabel.setObjectName("StrengthLabel")
        self.gridlayout2.addWidget(self.StrengthLabel, 0, 0, 1, 1)

        self.Strength = QLabel(self.GroupStats)
        self.Strength.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Strength.setObjectName("Strength")
        self.gridlayout2.addWidget(self.Strength, 0, 1, 1, 1)

        self.StrengthCap = QLabel(self.GroupStats)
        self.StrengthCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.StrengthCap.setObjectName("StrengthCap")
        self.gridlayout2.addWidget(self.StrengthCap, 0, 2, 1, 1)

        self.ConstitutionLabel = QLabel(self.GroupStats)
        self.ConstitutionLabel.setObjectName("ConstitutionLabel")
        self.gridlayout2.addWidget(self.ConstitutionLabel, 1, 0, 1, 1)

        self.Constitution = QLabel(self.GroupStats)
        self.Constitution.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Constitution.setObjectName("Constitution")
        self.gridlayout2.addWidget(self.Constitution, 1, 1, 1, 1)

        self.ConstitutionCap = QLabel(self.GroupStats)
        self.ConstitutionCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.ConstitutionCap.setObjectName("ConstitutionCap")
        self.gridlayout2.addWidget(self.ConstitutionCap, 1, 2, 1, 1)

        self.DexterityLabel = QLabel(self.GroupStats)
        self.DexterityLabel.setObjectName("DexterityLabel")
        self.gridlayout2.addWidget(self.DexterityLabel, 2, 0, 1, 1)

        self.Dexterity = QLabel(self.GroupStats)
        self.Dexterity.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Dexterity.setObjectName("Dexterity")
        self.gridlayout2.addWidget(self.Dexterity, 2, 1, 1, 1)

        self.DexterityCap = QLabel(self.GroupStats)
        self.DexterityCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.DexterityCap.setObjectName("DexterityCap")
        self.gridlayout2.addWidget(self.DexterityCap, 2, 2, 1, 1)

        self.QuicknessLabel = QLabel(self.GroupStats)
        self.QuicknessLabel.setObjectName("QuicknessLabel")
        self.gridlayout2.addWidget(self.QuicknessLabel, 3, 0, 1, 1)

        self.Quickness = QLabel(self.GroupStats)
        self.Quickness.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Quickness.setObjectName("Quickness")
        self.gridlayout2.addWidget(self.Quickness, 3, 1, 1, 1)

        self.QuicknessCap = QLabel(self.GroupStats)
        self.QuicknessCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.QuicknessCap.setObjectName("QuicknessCap")
        self.gridlayout2.addWidget(self.QuicknessCap, 3, 2, 1, 1)

        self.IntelligenceLabel = QLabel(self.GroupStats)
        self.IntelligenceLabel.setObjectName("IntelligenceLabel")
        self.gridlayout2.addWidget(self.IntelligenceLabel, 4, 0, 1, 1)

        self.Intelligence = QLabel(self.GroupStats)
        self.Intelligence.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Intelligence.setObjectName("Intelligence")
        self.gridlayout2.addWidget(self.Intelligence, 4, 1, 1, 1)

        self.IntelligenceCap = QLabel(self.GroupStats)
        self.IntelligenceCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.IntelligenceCap.setObjectName("IntelligenceCap")
        self.gridlayout2.addWidget(self.IntelligenceCap, 4, 2, 1, 1)

        self.PietyLabel = QLabel(self.GroupStats)
        self.PietyLabel.setObjectName("PietyLabel")
        self.gridlayout2.addWidget(self.PietyLabel, 5, 0, 1, 1)

        self.Piety = QLabel(self.GroupStats)
        self.Piety.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Piety.setObjectName("Piety")
        self.gridlayout2.addWidget(self.Piety, 5, 1, 1, 1)

        self.PietyCap = QLabel(self.GroupStats)
        self.PietyCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.PietyCap.setObjectName("PietyCap")
        self.gridlayout2.addWidget(self.PietyCap, 5, 2, 1, 1)

        self.CharismaLabel = QLabel(self.GroupStats)
        self.CharismaLabel.setObjectName("CharismaLabel")
        self.gridlayout2.addWidget(self.CharismaLabel, 6, 0, 1, 1)

        self.Charisma = QLabel(self.GroupStats)
        self.Charisma.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Charisma.setObjectName("Charisma")
        self.gridlayout2.addWidget(self.Charisma, 6, 1, 1, 1)

        self.CharismaCap = QLabel(self.GroupStats)
        self.CharismaCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.CharismaCap.setObjectName("CharismaCap")
        self.gridlayout2.addWidget(self.CharismaCap, 6, 2, 1, 1)

        self.EmpathyLabel = QLabel(self.GroupStats)
        self.EmpathyLabel.setObjectName("EmpathyLabel")
        self.gridlayout2.addWidget(self.EmpathyLabel, 7, 0, 1, 1)

        self.Empathy = QLabel(self.GroupStats)
        self.Empathy.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Empathy.setObjectName("Empathy")
        self.gridlayout2.addWidget(self.Empathy, 7, 1, 1, 1)

        self.EmpathyCap = QLabel(self.GroupStats)
        self.EmpathyCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.EmpathyCap.setObjectName("EmpathyCap")
        self.gridlayout2.addWidget(self.EmpathyCap, 7, 2, 1, 1)

        self.AcuityLabel = QLabel(self.GroupStats)
        self.AcuityLabel.setObjectName("AcuityLabel")
        self.gridlayout2.addWidget(self.AcuityLabel, 8, 0, 1, 1)

        self.Acuity = QLabel(self.GroupStats)
        self.Acuity.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Acuity.setObjectName("Acuity")
        self.gridlayout2.addWidget(self.Acuity, 8, 1, 1, 1)

        self.AcuityCap = QLabel(self.GroupStats)
        self.AcuityCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.AcuityCap.setObjectName("AcuityCap")
        self.gridlayout2.addWidget(self.AcuityCap, 8, 2, 1, 1)

        self.PowerLabel = QLabel(self.GroupStats)
        self.PowerLabel.setObjectName("PowerLabel")
        self.gridlayout2.addWidget(self.PowerLabel, 9, 0, 1, 1)

        self.Power = QLabel(self.GroupStats)
        self.Power.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Power.setObjectName("Power")
        self.gridlayout2.addWidget(self.Power, 9, 1, 1, 1)

        self.PowerCap = QLabel(self.GroupStats)
        self.PowerCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.PowerCap.setObjectName("PowerCap")
        self.gridlayout2.addWidget(self.PowerCap, 9, 2, 1, 1)

        self.PowerPoolLabel = QLabel(self.GroupStats)
        self.PowerPoolLabel.setObjectName("PowerPoolLabel")
        self.gridlayout2.addWidget(self.PowerPoolLabel, 10, 0, 1, 1)

        self.PowerPool = QLabel(self.GroupStats)
        self.PowerPool.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.PowerPool.setObjectName("PowerPool")
        self.gridlayout2.addWidget(self.PowerPool, 10, 1, 1, 1)

        self.PowerPoolCap = QLabel(self.GroupStats)
        self.PowerPoolCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.PowerPoolCap.setObjectName("PowerPoolCap")
        self.gridlayout2.addWidget(self.PowerPoolCap, 10, 2, 1, 1)

        self.FatigueLabel = QLabel(self.GroupStats)
        self.FatigueLabel.setObjectName("FatigueLabel")
        self.gridlayout2.addWidget(self.FatigueLabel, 11, 0, 1, 1)

        self.Fatigue = QLabel(self.GroupStats)
        self.Fatigue.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Fatigue.setObjectName("Fatigue")
        self.gridlayout2.addWidget(self.Fatigue, 11, 1, 1, 1)

        self.FatigueCap = QLabel(self.GroupStats)
        self.FatigueCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.FatigueCap.setObjectName("FatigueCap")
        self.gridlayout2.addWidget(self.FatigueCap, 11, 2, 1, 1)

        self.AFLabel = QLabel(self.GroupStats)
        self.AFLabel.setObjectName("AFLabel")
        self.gridlayout2.addWidget(self.AFLabel, 12, 0, 1, 1)

        self.AF = QLabel(self.GroupStats)
        self.AF.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.AF.setObjectName("AF")
        self.gridlayout2.addWidget(self.AF, 12, 1, 1, 1)

        self.AFCap = QLabel(self.GroupStats)
        self.AFCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.AFCap.setObjectName("AFCap")
        self.gridlayout2.addWidget(self.AFCap, 12, 2, 1, 1)

        self.HitsLabel = QLabel(self.GroupStats)
        self.HitsLabel.setObjectName("HitsLabel")
        self.gridlayout2.addWidget(self.HitsLabel, 13, 0, 1, 1)

        self.Hits = QLabel(self.GroupStats)
        self.Hits.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Hits.setObjectName("Hits")
        self.gridlayout2.addWidget(self.Hits, 13, 1, 1, 1)

        self.HitsCap = QLabel(self.GroupStats)
        self.HitsCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.HitsCap.setObjectName("HitsCap")
        self.gridlayout2.addWidget(self.HitsCap, 13, 2, 1, 1)

        self.hboxlayout = QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(5)
        self.hboxlayout.setObjectName("hboxlayout")

        self.LabelTotalUtility = QLabel(self.GroupStats)
        self.LabelTotalUtility.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.LabelTotalUtility.setObjectName("LabelTotalUtility")
        self.hboxlayout.addWidget(self.LabelTotalUtility)

        self.TotalUtility = QLabel(self.GroupStats)
        self.TotalUtility.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.TotalUtility.setObjectName("TotalUtility")
        self.hboxlayout.addWidget(self.TotalUtility)
        self.gridlayout2.addLayout(self.hboxlayout, 14, 0, 1, 3)

        spacerItem2 = QSpacerItem(1, 0, QSizePolicy.Minimum, QSizePolicy.MinimumExpanding)
        self.gridlayout2.addItem(spacerItem2, 15, 0, 1, 3)
        self.gridlayout.addWidget(self.GroupStats, 0, 1, 1, 1)

        self.GroupResists = GroupFrame(self.ScWinFrame)
        self.GroupResists.setFrameShape(QFrame.StyledPanel)
        self.GroupResists.setLineWidth(1)
        self.GroupResists.setObjectName("GroupResists")

        self.gridlayout3 = QGridLayout(self.GroupResists)
        self.gridlayout3.setContentsMargins(4, 4, 4, 4)
        self.gridlayout3.setSpacing(0)
        self.gridlayout3.setObjectName("gridlayout3")

        self.BodyLabel = QLabel(self.GroupResists)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridlayout3.addWidget(self.BodyLabel, 0, 0, 1, 1)

        self.Body = QLabel(self.GroupResists)
        self.Body.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Body.setObjectName("Body")
        self.gridlayout3.addWidget(self.Body, 0, 1, 1, 1)

        self.BodyCap = QLabel(self.GroupResists)
        self.BodyCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.BodyCap.setObjectName("BodyCap")
        self.gridlayout3.addWidget(self.BodyCap, 0, 2, 1, 1)

        self.ColdLabel = QLabel(self.GroupResists)
        self.ColdLabel.setObjectName("ColdLabel")
        self.gridlayout3.addWidget(self.ColdLabel, 1, 0, 1, 1)

        self.Cold = QLabel(self.GroupResists)
        self.Cold.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Cold.setObjectName("Cold")
        self.gridlayout3.addWidget(self.Cold, 1, 1, 1, 1)

        self.ColdCap = QLabel(self.GroupResists)
        self.ColdCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.ColdCap.setObjectName("ColdCap")
        self.gridlayout3.addWidget(self.ColdCap, 1, 2, 1, 1)

        self.HeatLabel = QLabel(self.GroupResists)
        self.HeatLabel.setObjectName("HeatLabel")
        self.gridlayout3.addWidget(self.HeatLabel, 2, 0, 1, 1)

        self.Heat = QLabel(self.GroupResists)
        self.Heat.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Heat.setObjectName("Heat")
        self.gridlayout3.addWidget(self.Heat, 2, 1, 1, 1)

        self.HeatCap = QLabel(self.GroupResists)
        self.HeatCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.HeatCap.setObjectName("HeatCap")
        self.gridlayout3.addWidget(self.HeatCap, 2, 2, 1, 1)

        self.EnergyLabel = QLabel(self.GroupResists)
        self.EnergyLabel.setObjectName("EnergyLabel")
        self.gridlayout3.addWidget(self.EnergyLabel, 3, 0, 1, 1)

        self.Energy = QLabel(self.GroupResists)
        self.Energy.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Energy.setObjectName("Energy")
        self.gridlayout3.addWidget(self.Energy, 3, 1, 1, 1)

        self.EnergyCap = QLabel(self.GroupResists)
        self.EnergyCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.EnergyCap.setObjectName("EnergyCap")
        self.gridlayout3.addWidget(self.EnergyCap, 3, 2, 1, 1)

        self.MatterLabel = QLabel(self.GroupResists)
        self.MatterLabel.setObjectName("MatterLabel")
        self.gridlayout3.addWidget(self.MatterLabel, 4, 0, 1, 1)

        self.Matter = QLabel(self.GroupResists)
        self.Matter.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Matter.setObjectName("Matter")
        self.gridlayout3.addWidget(self.Matter, 4, 1, 1, 1)

        self.MatterCap = QLabel(self.GroupResists)
        self.MatterCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.MatterCap.setObjectName("MatterCap")
        self.gridlayout3.addWidget(self.MatterCap, 4, 2, 1, 1)

        self.SpiritLabel = QLabel(self.GroupResists)
        self.SpiritLabel.setObjectName("SpiritLabel")
        self.gridlayout3.addWidget(self.SpiritLabel, 5, 0, 1, 1)

        self.Spirit = QLabel(self.GroupResists)
        self.Spirit.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Spirit.setObjectName("Spirit")
        self.gridlayout3.addWidget(self.Spirit, 5, 1, 1, 1)

        self.SpiritCap = QLabel(self.GroupResists)
        self.SpiritCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.SpiritCap.setObjectName("SpiritCap")
        self.gridlayout3.addWidget(self.SpiritCap, 5, 2, 1, 1)

        self.CrushLabel = QLabel(self.GroupResists)
        self.CrushLabel.setObjectName("CrushLabel")
        self.gridlayout3.addWidget(self.CrushLabel, 6, 0, 1, 1)

        self.Crush = QLabel(self.GroupResists)
        self.Crush.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Crush.setObjectName("Crush")
        self.gridlayout3.addWidget(self.Crush, 6, 1, 1, 1)

        self.CrushCap = QLabel(self.GroupResists)
        self.CrushCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.CrushCap.setObjectName("CrushCap")
        self.gridlayout3.addWidget(self.CrushCap, 6, 2, 1, 1)

        self.ThrustLabel = QLabel(self.GroupResists)
        self.ThrustLabel.setObjectName("ThrustLabel")
        self.gridlayout3.addWidget(self.ThrustLabel, 7, 0, 1, 1)

        self.Thrust = QLabel(self.GroupResists)
        self.Thrust.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Thrust.setObjectName("Thrust")
        self.gridlayout3.addWidget(self.Thrust, 7, 1, 1, 1)

        self.ThrustCap = QLabel(self.GroupResists)
        self.ThrustCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.ThrustCap.setObjectName("ThrustCap")
        self.gridlayout3.addWidget(self.ThrustCap, 7, 2, 1, 1)

        self.SlashLabel = QLabel(self.GroupResists)
        self.SlashLabel.setObjectName("SlashLabel")
        self.gridlayout3.addWidget(self.SlashLabel, 8, 0, 1, 1)

        self.Slash = QLabel(self.GroupResists)
        self.Slash.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Slash.setObjectName("Slash")
        self.gridlayout3.addWidget(self.Slash, 8, 1, 1, 1)

        self.SlashCap = QLabel(self.GroupResists)
        self.SlashCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.SlashCap.setObjectName("SlashCap")
        self.gridlayout3.addWidget(self.SlashCap, 8, 2, 1, 1)

        self.EssenceLabel = QLabel(self.GroupResists)
        self.EssenceLabel.setObjectName("EssenceLabel")
        self.gridlayout3.addWidget(self.EssenceLabel, 9, 0, 1, 1)

        self.Essence = QLabel(self.GroupResists)
        self.Essence.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Essence.setObjectName("Essence")
        self.gridlayout3.addWidget(self.Essence, 9, 1, 1, 1)

        self.EssenceCap = QLabel(self.GroupResists)
        self.EssenceCap.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.EssenceCap.setObjectName("EssenceCap")
        self.gridlayout3.addWidget(self.EssenceCap, 9, 2, 1, 1)

        spacerItem3 = QSpacerItem(1, 1, QSizePolicy.Minimum, QSizePolicy.MinimumExpanding)
        self.gridlayout3.addItem(spacerItem3, 10, 0, 1, 3)
        self.gridlayout.addWidget(self.GroupResists, 0, 2, 1, 1)

        self.GroupSkillsList = GroupFrame(self.ScWinFrame)
        self.GroupSkillsList.setFrameShape(QFrame.StyledPanel)
        self.GroupSkillsList.setLineWidth(1)
        self.GroupSkillsList.setObjectName("GroupSkillsList")

        self.gridlayout4 = QGridLayout(self.GroupSkillsList)
        self.gridlayout4.setContentsMargins(4, 4, 4, 4)
        self.gridlayout4.setSpacing(0)
        self.gridlayout4.setObjectName("gridlayout4")

        self.SkillsList = SkillsView(self.GroupSkillsList)

        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SkillsList.sizePolicy().hasHeightForWidth())
        self.SkillsList.setSizePolicy(sizePolicy)
        self.SkillsList.setFocusPolicy(Qt.StrongFocus)
        self.SkillsList.setFrameShape(QFrame.NoFrame)
        self.SkillsList.setFrameShadow(QFrame.Plain)
        self.SkillsList.setLineWidth(0)
        self.SkillsList.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.SkillsList.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.SkillsList.setAutoScroll(True)
        self.SkillsList.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.SkillsList.setWrapping(True)
        self.SkillsList.setResizeMode(QListView.Adjust)
        self.SkillsList.setObjectName("SkillsList")
        self.gridlayout4.addWidget(self.SkillsList, 0, 0, 1, 1)
        self.gridlayout.addWidget(self.GroupSkillsList, 0, 3, 1, 1)

        self.vboxlayout = QVBoxLayout()
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName("vboxlayout")

        self.PieceTab = MultiTabBar(self.ScWinFrame)
        self.PieceTab.setFocusPolicy(Qt.StrongFocus)
        self.PieceTab.setObjectName("PieceTab")
        self.vboxlayout.addWidget(self.PieceTab)

        spacerItem4 = QSpacerItem(1, 1, QSizePolicy.Minimum, QSizePolicy.Fixed)
        self.vboxlayout.addItem(spacerItem4)

        self.GroupItemFrame = MultiTabFrame(self.ScWinFrame)

        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GroupItemFrame.sizePolicy().hasHeightForWidth())
        self.GroupItemFrame.setSizePolicy(sizePolicy)
        self.GroupItemFrame.setObjectName("GroupItemFrame")

        self.vboxlayout1 = QVBoxLayout(self.GroupItemFrame)
        self.vboxlayout1.setContentsMargins(6, 6, 6, 6)
        self.vboxlayout1.setSpacing(0)
        self.vboxlayout1.setObjectName("vboxlayout1")

        spacerItem5 = QSpacerItem(1, 2, QSizePolicy.Minimum, QSizePolicy.Fixed)
        self.vboxlayout1.addItem(spacerItem5)

        self.hboxlayout1 = QHBoxLayout()
        self.hboxlayout1.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout1.setSpacing(0)
        self.hboxlayout1.setObjectName("hboxlayout1")

        self.ItemLevelLabel = QLabel(self.GroupItemFrame)
        self.ItemLevelLabel.setTextFormat(Qt.PlainText)
        self.ItemLevelLabel.setObjectName("ItemLevelLabel")
        self.hboxlayout1.addWidget(self.ItemLevelLabel)

        self.ItemLevel = QLineEdit(self.GroupItemFrame)
        self.ItemLevel.setObjectName("ItemLevel")
        self.hboxlayout1.addWidget(self.ItemLevel)

        self.ItemLevelButton = QPushButton(self.GroupItemFrame)
        self.ItemLevelButton.setMaximumSize(QSize(21, 21))
        self.ItemLevelButton.setObjectName("ItemLevelButton")
        self.hboxlayout1.addWidget(self.ItemLevelButton)

        self.ItemQualityLabel = QLabel(self.GroupItemFrame)
        self.ItemQualityLabel.setTextFormat(Qt.PlainText)
        self.ItemQualityLabel.setObjectName("ItemQualityLabel")
        self.hboxlayout1.addWidget(self.ItemQualityLabel)

        self.QualDrop = SearchingCombo(self.GroupItemFrame)
        self.QualDrop.setObjectName("QualDrop")
        self.hboxlayout1.addWidget(self.QualDrop)

        self.QualEdit = QLineEdit(self.GroupItemFrame)
        self.QualEdit.setObjectName("QualEdit")
        self.hboxlayout1.addWidget(self.QualEdit)

        self.ItemNameLabel = QLabel(self.GroupItemFrame)
        self.ItemNameLabel.setTextFormat(Qt.PlainText)
        self.ItemNameLabel.setObjectName("ItemNameLabel")
        self.hboxlayout1.addWidget(self.ItemNameLabel)

        self.ItemNameCombo = SearchingCombo(self.GroupItemFrame)

        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ItemNameCombo.sizePolicy().hasHeightForWidth())
        self.ItemNameCombo.setSizePolicy(sizePolicy)
        self.ItemNameCombo.setEditable(True)
        self.ItemNameCombo.setInsertPolicy(QComboBox.NoInsert)
        self.ItemNameCombo.setDuplicatesEnabled(True)
        self.ItemNameCombo.setObjectName("ItemNameCombo")
        self.hboxlayout1.addWidget(self.ItemNameCombo)

        self.Equipped = QCheckBox(self.GroupItemFrame)
        self.Equipped.setObjectName("Equipped")
        self.hboxlayout1.addWidget(self.Equipped)

        self.ToggleItemView = QPushButton(self.GroupItemFrame)
        self.ToggleItemView.setObjectName("ToggleItemView")
        self.hboxlayout1.addWidget(self.ToggleItemView)
        self.vboxlayout1.addLayout(self.hboxlayout1)

        self.stackedlayout = QStackedLayout()
        self.stackedlayout.setContentsMargins(0, 0, 0, 0)
        self.stackedlayout.setSpacing(0)
        self.stackedlayout.setObjectName("stackedlayout")

        self.ItemSummaryFrame = QWidget(self.GroupItemFrame)
        self.ItemSummaryFrame.setObjectName("ItemSummaryFrame")

        self.hboxlayout2 = QHBoxLayout(self.ItemSummaryFrame)
        self.hboxlayout2.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout2.setSpacing(9)
        self.hboxlayout2.setObjectName("hboxlayout2")

        self.ItemInfoFrame = QWidget(self.ItemSummaryFrame)
        self.ItemInfoFrame.setObjectName("ItemInfoFrame")

        self.vboxlayout2 = QVBoxLayout(self.ItemInfoFrame)
        self.vboxlayout2.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout2.setSpacing(0)
        self.vboxlayout2.setObjectName("vboxlayout2")

        self.LabelItemInfo = QLabel(self.ItemInfoFrame)
        self.LabelItemInfo.setObjectName("LabelItemInfo")
        self.vboxlayout2.addWidget(self.LabelItemInfo)

        self.ScrollItemInfo = ScrollArea(self.ItemInfoFrame)

        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ScrollItemInfo.sizePolicy().hasHeightForWidth())
        self.ScrollItemInfo.setSizePolicy(sizePolicy)
        self.ScrollItemInfo.setFrameShape(QFrame.NoFrame)
        self.ScrollItemInfo.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.ScrollItemInfo.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ScrollItemInfo.setObjectName("ScrollItemInfo")

        self.ItemInfoGrid = QWidget(self.ScrollItemInfo)
        self.ItemInfoGrid.setObjectName("ItemInfoGrid")

        self.gridlayout5 = QGridLayout(self.ItemInfoGrid)
        self.gridlayout5.setContentsMargins(0, 0, 0, 0)
        self.gridlayout5.setSpacing(0)
        self.gridlayout5.setObjectName("gridlayout5")

        self.LabelItemRealm = QLabel(self.ItemInfoGrid)
        self.LabelItemRealm.setTextFormat(Qt.PlainText)
        self.LabelItemRealm.setObjectName("LabelItemRealm")
        self.gridlayout5.addWidget(self.LabelItemRealm, 0, 0, 1, 1)

        self.ItemRealm = SearchingCombo(self.ItemInfoGrid)
        self.ItemRealm.setObjectName("ItemRealm")
        self.gridlayout5.addWidget(self.ItemRealm, 0, 1, 1, 3)

        self.LabelItemType = QLabel(self.ItemInfoGrid)
        self.LabelItemType.setTextFormat(Qt.PlainText)
        self.LabelItemType.setObjectName("LabelItemType")
        self.gridlayout5.addWidget(self.LabelItemType, 1, 0, 1, 1)

        self.ItemType = SearchingCombo(self.ItemInfoGrid)
        self.ItemType.setObjectName("ItemType")
        self.gridlayout5.addWidget(self.ItemType, 1, 1, 1, 3)

        self.LabelItemSource = QLabel(self.ItemInfoGrid)
        self.LabelItemSource.setTextFormat(Qt.PlainText)
        self.LabelItemSource.setObjectName("LabelItemSource")
        self.gridlayout5.addWidget(self.LabelItemSource, 2, 0, 1, 1)

        self.ItemSource = SearchingCombo(self.ItemInfoGrid)
        self.ItemSource.setObjectName("ItemSource")
        self.gridlayout5.addWidget(self.ItemSource, 2, 1, 1, 3)

        self.LabelBonusEdit = QLabel(self.ItemInfoGrid)
        self.LabelBonusEdit.setTextFormat(Qt.PlainText)
        self.LabelBonusEdit.setObjectName("LabelBonusEdit")
        self.gridlayout5.addWidget(self.LabelBonusEdit, 3, 0, 1, 1)

        self.BonusEdit = QLineEdit(self.ItemInfoGrid)
        self.BonusEdit.setObjectName("BonusEdit")
        self.gridlayout5.addWidget(self.BonusEdit, 3, 1, 1, 1)

        self.LabelAFDPSEdit = QLabel(self.ItemInfoGrid)
        self.LabelAFDPSEdit.setTextFormat(Qt.PlainText)
        self.LabelAFDPSEdit.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.LabelAFDPSEdit.setObjectName("LabelAFDPSEdit")
        self.gridlayout5.addWidget(self.LabelAFDPSEdit, 3, 2, 1, 1)

        self.AFDPSEdit = QLineEdit(self.ItemInfoGrid)
        self.AFDPSEdit.setObjectName("AFDPSEdit")
        self.gridlayout5.addWidget(self.AFDPSEdit, 3, 3, 1, 1)

        self.LabelSpeedEdit = QLabel(self.ItemInfoGrid)
        self.LabelSpeedEdit.setTextFormat(Qt.PlainText)
        self.LabelSpeedEdit.setObjectName("LabelSpeedEdit")
        self.gridlayout5.addWidget(self.LabelSpeedEdit, 4, 0, 1, 1)

        self.SpeedEdit = QLineEdit(self.ItemInfoGrid)
        self.SpeedEdit.setObjectName("SpeedEdit")
        self.gridlayout5.addWidget(self.SpeedEdit, 4, 1, 1, 1)

        self.hboxlayout3 = QHBoxLayout()
        self.hboxlayout3.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout3.setSpacing(0)
        self.hboxlayout3.setObjectName("hboxlayout3")

        spacerItem6 = QSpacerItem(1, 0, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem6)

        self.Offhand = QCheckBox(self.ItemInfoGrid)
        self.Offhand.setObjectName("Offhand")
        self.hboxlayout3.addWidget(self.Offhand)
        self.gridlayout5.addLayout(self.hboxlayout3, 4, 2, 1, 2)

        self.LabelDamageType = QLabel(self.ItemInfoGrid)
        self.LabelDamageType.setTextFormat(Qt.PlainText)
        self.LabelDamageType.setObjectName("LabelDamageType")
        self.gridlayout5.addWidget(self.LabelDamageType, 5, 0, 1, 1)

        self.DamageType = SearchingCombo(self.ItemInfoGrid)
        self.DamageType.setObjectName("DamageType")
        self.gridlayout5.addWidget(self.DamageType, 5, 1, 1, 3)

        self.LabelItemRequirement = QLabel(self.ItemInfoGrid)
        self.LabelItemRequirement.setTextFormat(Qt.PlainText)
        self.LabelItemRequirement.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignBottom)
        self.LabelItemRequirement.setObjectName("LabelItemRequirement")
        self.gridlayout5.addWidget(self.LabelItemRequirement, 6, 0, 1, 4)

        self.ItemRequirement = QLineEdit(self.ItemInfoGrid)
        self.ItemRequirement.setObjectName("ItemRequirement")
        self.gridlayout5.addWidget(self.ItemRequirement, 7, 0, 1, 4)

        spacerItem7 = QSpacerItem(1, 1, QSizePolicy.Minimum, QSizePolicy.MinimumExpanding)
        self.gridlayout5.addItem(spacerItem7, 8, 0, 1, 4)

        self.LabelDBSource = QLabel(self.ItemInfoGrid)
        self.LabelDBSource.setTextFormat(Qt.PlainText)
        self.LabelDBSource.setObjectName("LabelDBSource")
        self.gridlayout5.addWidget(self.LabelDBSource, 9, 0, 1, 1)

        self.DBSource = QLabel(self.ItemInfoGrid)
        self.DBSource.setTextFormat(Qt.PlainText)
        self.DBSource.setObjectName("DBSource")
        self.gridlayout5.addWidget(self.DBSource, 9, 1, 1, 3)
        self.vboxlayout2.addWidget(self.ScrollItemInfo)
        self.hboxlayout2.addWidget(self.ItemInfoFrame)

        self.vboxlayout3 = QVBoxLayout()
        self.vboxlayout3.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout3.setSpacing(0)
        self.vboxlayout3.setObjectName("vboxlayout3")

        self.LabelClassRestrictionTable = QLabel(self.ItemSummaryFrame)
        self.LabelClassRestrictionTable.setObjectName("LabelClassRestrictionTable")
        self.vboxlayout3.addWidget(self.LabelClassRestrictionTable)

        self.ClassRestrictionTable = QListWidget(self.ItemSummaryFrame)
        self.ClassRestrictionTable.setObjectName("ClassRestrictionTable")
        self.vboxlayout3.addWidget(self.ClassRestrictionTable)
        self.hboxlayout2.addLayout(self.vboxlayout3)

        self.vboxlayout4 = QVBoxLayout()
        self.vboxlayout4.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout4.setSpacing(0)
        self.vboxlayout4.setObjectName("vboxlayout4")

        self.LabelItemNoteText = QLabel(self.ItemSummaryFrame)
        self.LabelItemNoteText.setObjectName("LabelItemNoteText")
        self.vboxlayout4.addWidget(self.LabelItemNoteText)

        self.ItemNoteText = QTextEdit(self.ItemSummaryFrame)
        self.ItemNoteText.setFocusPolicy(Qt.StrongFocus)
        self.ItemNoteText.setTabChangesFocus(True)
        self.ItemNoteText.setAcceptRichText(False)
        self.ItemNoteText.setTextInteractionFlags(Qt.TextEditable)
        self.ItemNoteText.setObjectName("ItemNoteText")
        self.vboxlayout4.addWidget(self.ItemNoteText)
        self.hboxlayout2.addLayout(self.vboxlayout4)

        self.vboxlayout5 = QVBoxLayout()
        self.vboxlayout5.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout5.setSpacing(0)
        self.vboxlayout5.setObjectName("vboxlayout5")

        self.LabelNoteText = QLabel(self.ItemSummaryFrame)
        self.LabelNoteText.setObjectName("LabelNoteText")
        self.vboxlayout5.addWidget(self.LabelNoteText)

        self.NoteText = QTextEdit(self.ItemSummaryFrame)
        self.NoteText.setFocusPolicy(Qt.StrongFocus)
        self.NoteText.setTabChangesFocus(True)
        self.NoteText.setAcceptRichText(False)
        self.NoteText.setTextInteractionFlags(Qt.TextEditable)
        self.NoteText.setObjectName("NoteText")
        self.vboxlayout5.addWidget(self.NoteText)
        self.hboxlayout2.addLayout(self.vboxlayout5)
        self.stackedlayout.addWidget(self.ItemSummaryFrame)

        self.ItemSlotsFrame = QWidget(self.GroupItemFrame)
        self.ItemSlotsFrame.setObjectName("ItemSlotsFrame")

        self.hboxlayout4 = QHBoxLayout(self.ItemSlotsFrame)
        self.hboxlayout4.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout4.setSpacing(9)
        self.hboxlayout4.setObjectName("hboxlayout4")

        self.vboxlayout6 = QVBoxLayout()
        self.vboxlayout6.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout6.setSpacing(0)
        self.vboxlayout6.setObjectName("vboxlayout6")

        self.ItemSlotsHeader = QWidget(self.ItemSlotsFrame)
        self.ItemSlotsHeader.setObjectName("ItemSlotsHeader")

        self.gridlayout6 = QGridLayout(self.ItemSlotsHeader)
        self.gridlayout6.setContentsMargins(0, 0, 0, 0)
        self.gridlayout6.setSpacing(0)
        self.gridlayout6.setObjectName("gridlayout6")

        spacerItem8 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem8, 0, 0, 1, 1)

        self.LabelGemType = QLabel(self.ItemSlotsHeader)
        self.LabelGemType.setObjectName("LabelGemType")
        self.gridlayout6.addWidget(self.LabelGemType, 0, 1, 1, 1)

        self.LabelGemAmount = QLabel(self.ItemSlotsHeader)
        self.LabelGemAmount.setObjectName("LabelGemAmount")
        self.gridlayout6.addWidget(self.LabelGemAmount, 0, 2, 1, 1)

        self.LabelGemEffect = QLabel(self.ItemSlotsHeader)
        self.LabelGemEffect.setObjectName("LabelGemEffect")
        self.gridlayout6.addWidget(self.LabelGemEffect, 0, 3, 1, 1)

        self.LabelGemMakes = QLabel(self.ItemSlotsHeader)
        self.LabelGemMakes.setObjectName("LabelGemMakes")
        self.gridlayout6.addWidget(self.LabelGemMakes, 0, 4, 1, 1)

        self.LabelRequirement = QLabel(self.ItemSlotsHeader)
        self.LabelRequirement.setObjectName("LabelRequirement")
        self.gridlayout6.addWidget(self.LabelRequirement, 0, 4, 1, 3)

        self.LabelGemPoints = QLabel(self.ItemSlotsHeader)
        self.LabelGemPoints.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.LabelGemPoints.setObjectName("LabelGemPoints")
        self.gridlayout6.addWidget(self.LabelGemPoints, 0, 5, 1, 1)

        self.LabelGemCost = QLabel(self.ItemSlotsHeader)
        self.LabelGemCost.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.LabelGemCost.setObjectName("LabelGemCost")
        self.gridlayout6.addWidget(self.LabelGemCost, 0, 6, 1, 1)

        spacerItem9 = QSpacerItem(5, 1, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem9, 0, 7, 1, 1)

        self.LabelGemName = QLabel(self.ItemSlotsHeader)
        self.LabelGemName.setObjectName("LabelGemName")
        self.gridlayout6.addWidget(self.LabelGemName, 0, 8, 1, 1)
        self.vboxlayout6.addWidget(self.ItemSlotsHeader)

        self.ScrollSlots = ScrollArea(self.ItemSlotsFrame)

        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ScrollSlots.sizePolicy().hasHeightForWidth())
        self.ScrollSlots.setSizePolicy(sizePolicy)
        self.ScrollSlots.setFrameShape(QFrame.NoFrame)
        self.ScrollSlots.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.ScrollSlots.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ScrollSlots.setObjectName("ScrollSlots")

        self.ItemSlotsGrid = QWidget(self.ScrollSlots)
        self.ItemSlotsGrid.setObjectName("ItemSlotsGrid")

        self.gridlayout7 = QGridLayout(self.ItemSlotsGrid)
        self.gridlayout7.setContentsMargins(0, 0, 0, 0)
        self.gridlayout7.setSpacing(0)
        self.gridlayout7.setObjectName("gridlayout7")

        self.Gem_Label_1 = QLabel(self.ItemSlotsGrid)
        self.Gem_Label_1.setTextFormat(Qt.PlainText)
        self.Gem_Label_1.setObjectName("Gem_Label_1")
        self.gridlayout7.addWidget(self.Gem_Label_1, 0, 0, 1, 1)

        self.Type_1 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_1.setObjectName("Type_1")
        self.gridlayout7.addWidget(self.Type_1, 0, 1, 1, 1)

        self.Amount_Edit_1 = QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_1.setObjectName("Amount_Edit_1")
        self.gridlayout7.addWidget(self.Amount_Edit_1, 0, 2, 1, 1)

        self.Amount_Drop_1 = SearchingCombo(self.ItemSlotsGrid)
        self.Amount_Drop_1.setObjectName("Amount_Drop_1")
        self.gridlayout7.addWidget(self.Amount_Drop_1, 0, 2, 1, 1)

        self.Effect_1 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_1.setEditable(True)
        self.Effect_1.setObjectName("Effect_1")
        self.gridlayout7.addWidget(self.Effect_1, 0, 3, 1, 1)

        self.Makes_1 = QSpinBox(self.ItemSlotsGrid)
        self.Makes_1.setFocusPolicy(Qt.StrongFocus)
        self.Makes_1.setObjectName("Makes_1")
        self.gridlayout7.addWidget(self.Makes_1, 0, 4, 1, 1)

        self.Requirement_1 = QLineEdit(self.ItemSlotsGrid)
        self.Requirement_1.setObjectName("Requirement_1")
        self.gridlayout7.addWidget(self.Requirement_1, 0, 4, 1, 3)

        self.Points_1 = QLabel(self.ItemSlotsGrid)
        self.Points_1.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Points_1.setObjectName("Points_1")
        self.gridlayout7.addWidget(self.Points_1, 0, 5, 1, 1)

        self.Cost_1 = QLabel(self.ItemSlotsGrid)
        self.Cost_1.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Cost_1.setObjectName("Cost_1")
        self.gridlayout7.addWidget(self.Cost_1, 0, 6, 1, 1)

        spacerItem10 = QSpacerItem(5, 1, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem10, 0, 7, 12, 1)

        self.Name_1 = QLabel(self.ItemSlotsGrid)
        self.Name_1.setObjectName("Name_1")
        self.gridlayout7.addWidget(self.Name_1, 0, 8, 1, 1)

        spacerItem11 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem11, 0, 8, 4, 1)

        self.Gem_Label_2 = QLabel(self.ItemSlotsGrid)
        self.Gem_Label_2.setTextFormat(Qt.PlainText)
        self.Gem_Label_2.setObjectName("Gem_Label_2")
        self.gridlayout7.addWidget(self.Gem_Label_2, 1, 0, 1, 1)

        self.Type_2 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_2.setObjectName("Type_2")
        self.gridlayout7.addWidget(self.Type_2, 1, 1, 1, 1)

        self.Amount_Edit_2 = QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_2.setObjectName("Amount_Edit_2")
        self.gridlayout7.addWidget(self.Amount_Edit_2, 1, 2, 1, 1)

        self.Amount_Drop_2 = SearchingCombo(self.ItemSlotsGrid)
        self.Amount_Drop_2.setObjectName("Amount_Drop_2")
        self.gridlayout7.addWidget(self.Amount_Drop_2, 1, 2, 1, 1)

        self.Effect_2 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_2.setEditable(True)
        self.Effect_2.setObjectName("Effect_2")
        self.gridlayout7.addWidget(self.Effect_2, 1, 3, 1, 1)

        self.Makes_2 = QSpinBox(self.ItemSlotsGrid)
        self.Makes_2.setFocusPolicy(Qt.StrongFocus)
        self.Makes_2.setObjectName("Makes_2")
        self.gridlayout7.addWidget(self.Makes_2, 1, 4, 1, 1)

        self.Requirement_2 = QLineEdit(self.ItemSlotsGrid)
        self.Requirement_2.setObjectName("Requirement_2")
        self.gridlayout7.addWidget(self.Requirement_2, 1, 4, 1, 3)

        self.Points_2 = QLabel(self.ItemSlotsGrid)
        self.Points_2.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Points_2.setObjectName("Points_2")
        self.gridlayout7.addWidget(self.Points_2, 1, 5, 1, 1)

        self.Cost_2 = QLabel(self.ItemSlotsGrid)
        self.Cost_2.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Cost_2.setObjectName("Cost_2")
        self.gridlayout7.addWidget(self.Cost_2, 1, 6, 1, 1)

        self.Name_2 = QLabel(self.ItemSlotsGrid)
        self.Name_2.setObjectName("Name_2")
        self.gridlayout7.addWidget(self.Name_2, 1, 8, 1, 1)

        self.Gem_Label_3 = QLabel(self.ItemSlotsGrid)
        self.Gem_Label_3.setTextFormat(Qt.PlainText)
        self.Gem_Label_3.setObjectName("Gem_Label_3")
        self.gridlayout7.addWidget(self.Gem_Label_3, 2, 0, 1, 1)

        self.Type_3 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_3.setObjectName("Type_3")
        self.gridlayout7.addWidget(self.Type_3, 2, 1, 1, 1)

        self.Amount_Edit_3 = QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_3.setObjectName("Amount_Edit_3")
        self.gridlayout7.addWidget(self.Amount_Edit_3, 2, 2, 1, 1)

        self.Amount_Drop_3 = SearchingCombo(self.ItemSlotsGrid)
        self.Amount_Drop_3.setObjectName("Amount_Drop_3")
        self.gridlayout7.addWidget(self.Amount_Drop_3, 2, 2, 1, 1)

        self.Effect_3 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_3.setEditable(True)
        self.Effect_3.setObjectName("Effect_3")
        self.gridlayout7.addWidget(self.Effect_3, 2, 3, 1, 1)

        self.Makes_3 = QSpinBox(self.ItemSlotsGrid)
        self.Makes_3.setFocusPolicy(Qt.StrongFocus)
        self.Makes_3.setObjectName("Makes_3")
        self.gridlayout7.addWidget(self.Makes_3, 2, 4, 1, 1)

        self.Requirement_3 = QLineEdit(self.ItemSlotsGrid)
        self.Requirement_3.setObjectName("Requirement_3")
        self.gridlayout7.addWidget(self.Requirement_3, 2, 4, 1, 3)

        self.Points_3 = QLabel(self.ItemSlotsGrid)
        self.Points_3.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Points_3.setObjectName("Points_3")
        self.gridlayout7.addWidget(self.Points_3, 2, 5, 1, 1)

        self.Cost_3 = QLabel(self.ItemSlotsGrid)
        self.Cost_3.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Cost_3.setObjectName("Cost_3")
        self.gridlayout7.addWidget(self.Cost_3, 2, 6, 1, 1)

        self.Name_3 = QLabel(self.ItemSlotsGrid)
        self.Name_3.setObjectName("Name_3")
        self.gridlayout7.addWidget(self.Name_3, 2, 8, 1, 1)

        self.Gem_Label_4 = QLabel(self.ItemSlotsGrid)
        self.Gem_Label_4.setTextFormat(Qt.PlainText)
        self.Gem_Label_4.setObjectName("Gem_Label_4")
        self.gridlayout7.addWidget(self.Gem_Label_4, 3, 0, 1, 1)

        self.Type_4 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_4.setObjectName("Type_4")
        self.gridlayout7.addWidget(self.Type_4, 3, 1, 1, 1)

        self.Amount_Edit_4 = QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_4.setObjectName("Amount_Edit_4")
        self.gridlayout7.addWidget(self.Amount_Edit_4, 3, 2, 1, 1)

        self.Amount_Drop_4 = SearchingCombo(self.ItemSlotsGrid)
        self.Amount_Drop_4.setObjectName("Amount_Drop_4")
        self.gridlayout7.addWidget(self.Amount_Drop_4, 3, 2, 1, 1)

        self.Effect_4 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_4.setEditable(True)
        self.Effect_4.setObjectName("Effect_4")
        self.gridlayout7.addWidget(self.Effect_4, 3, 3, 1, 1)

        self.Makes_4 = QSpinBox(self.ItemSlotsGrid)
        self.Makes_4.setFocusPolicy(Qt.StrongFocus)
        self.Makes_4.setObjectName("Makes_4")
        self.gridlayout7.addWidget(self.Makes_4, 3, 4, 1, 1)

        self.Requirement_4 = QLineEdit(self.ItemSlotsGrid)
        self.Requirement_4.setObjectName("Requirement_4")
        self.gridlayout7.addWidget(self.Requirement_4, 3, 4, 1, 3)

        self.Points_4 = QLabel(self.ItemSlotsGrid)
        self.Points_4.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Points_4.setObjectName("Points_4")
        self.gridlayout7.addWidget(self.Points_4, 3, 5, 1, 1)

        self.Cost_4 = QLabel(self.ItemSlotsGrid)
        self.Cost_4.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.Cost_4.setObjectName("Cost_4")
        self.gridlayout7.addWidget(self.Cost_4, 3, 6, 1, 1)

        self.Name_4 = QLabel(self.ItemSlotsGrid)
        self.Name_4.setObjectName("Name_4")
        self.gridlayout7.addWidget(self.Name_4, 3, 8, 1, 1)

        self.Gem_Label_5 = QLabel(self.ItemSlotsGrid)
        self.Gem_Label_5.setTextFormat(Qt.PlainText)
        self.Gem_Label_5.setObjectName("Gem_Label_5")
        self.gridlayout7.addWidget(self.Gem_Label_5, 4, 0, 1, 1)

        self.Type_5 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_5.setObjectName("Type_5")
        self.gridlayout7.addWidget(self.Type_5, 4, 1, 1, 1)

        self.Amount_Edit_5 = QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_5.setObjectName("Amount_Edit_5")
        self.gridlayout7.addWidget(self.Amount_Edit_5, 4, 2, 1, 1)

        self.Amount_Drop_5 = SearchingCombo(self.ItemSlotsGrid)
        self.Amount_Drop_5.setObjectName("Amount_Drop_5")
        self.gridlayout7.addWidget(self.Amount_Drop_5, 4, 2, 1, 1)

        self.Effect_5 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_5.setEditable(True)
        self.Effect_5.setObjectName("Effect_5")
        self.gridlayout7.addWidget(self.Effect_5, 4, 3, 1, 1)

        self.Requirement_5 = QLineEdit(self.ItemSlotsGrid)
        self.Requirement_5.setObjectName("Requirement_5")
        self.gridlayout7.addWidget(self.Requirement_5, 4, 4, 1, 3)

        self.Name_5 = QLabel(self.ItemSlotsGrid)
        self.Name_5.setObjectName("Name_5")
        self.gridlayout7.addWidget(self.Name_5, 4, 8, 1, 1)

        spacerItem12 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem12, 4, 8, 1, 1)

        self.Gem_Label_6 = QLabel(self.ItemSlotsGrid)
        self.Gem_Label_6.setTextFormat(Qt.PlainText)
        self.Gem_Label_6.setObjectName("Gem_Label_6")
        self.gridlayout7.addWidget(self.Gem_Label_6, 5, 0, 1, 1)

        self.Type_6 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_6.setObjectName("Type_6")
        self.gridlayout7.addWidget(self.Type_6, 5, 1, 1, 1)

        self.Amount_Edit_6 = QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_6.setObjectName("Amount_Edit_6")
        self.gridlayout7.addWidget(self.Amount_Edit_6, 5, 2, 1, 1)

        self.Amount_Drop_6 = SearchingCombo(self.ItemSlotsGrid)
        self.Amount_Drop_6.setObjectName("Amount_Drop_6")
        self.gridlayout7.addWidget(self.Amount_Drop_6, 5, 2, 1, 1)

        self.Effect_6 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_6.setEditable(True)
        self.Effect_6.setObjectName("Effect_6")
        self.gridlayout7.addWidget(self.Effect_6, 5, 3, 1, 1)

        self.Requirement_6 = QLineEdit(self.ItemSlotsGrid)
        self.Requirement_6.setObjectName("Requirement_6")
        self.gridlayout7.addWidget(self.Requirement_6, 5, 4, 1, 3)

        self.Name_6 = QLabel(self.ItemSlotsGrid)
        self.Name_6.setObjectName("Name_6")
        self.gridlayout7.addWidget(self.Name_6, 5, 8, 1, 1)

        spacerItem13 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem13, 5, 8, 1, 1)

        self.Gem_Label_7 = QLabel(self.ItemSlotsGrid)
        self.Gem_Label_7.setTextFormat(Qt.PlainText)
        self.Gem_Label_7.setObjectName("Gem_Label_7")
        self.gridlayout7.addWidget(self.Gem_Label_7, 6, 0, 1, 1)

        self.Type_7 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_7.setObjectName("Type_7")
        self.gridlayout7.addWidget(self.Type_7, 6, 1, 1, 1)

        self.Amount_Edit_7 = QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_7.setObjectName("Amount_Edit_7")
        self.gridlayout7.addWidget(self.Amount_Edit_7, 6, 2, 1, 1)

        self.Effect_7 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_7.setEditable(True)
        self.Effect_7.setObjectName("Effect_7")
        self.gridlayout7.addWidget(self.Effect_7, 6, 3, 1, 1)

        self.Requirement_7 = QLineEdit(self.ItemSlotsGrid)
        self.Requirement_7.setObjectName("Requirement_7")
        self.gridlayout7.addWidget(self.Requirement_7, 6, 4, 1, 3)

        spacerItem14 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem14, 6, 8, 1, 1)

        self.Gem_Label_8 = QLabel(self.ItemSlotsGrid)
        self.Gem_Label_8.setTextFormat(Qt.PlainText)
        self.Gem_Label_8.setObjectName("Gem_Label_8")
        self.gridlayout7.addWidget(self.Gem_Label_8, 7, 0, 1, 1)

        self.Type_8 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_8.setObjectName("Type_8")
        self.gridlayout7.addWidget(self.Type_8, 7, 1, 1, 1)

        self.Amount_Edit_8 = QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_8.setObjectName("Amount_Edit_8")
        self.gridlayout7.addWidget(self.Amount_Edit_8, 7, 2, 1, 1)

        self.Effect_8 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_8.setEditable(True)
        self.Effect_8.setObjectName("Effect_8")
        self.gridlayout7.addWidget(self.Effect_8, 7, 3, 1, 1)

        self.Requirement_8 = QLineEdit(self.ItemSlotsGrid)
        self.Requirement_8.setObjectName("Requirement_8")
        self.gridlayout7.addWidget(self.Requirement_8, 7, 4, 1, 3)

        self.hboxlayout5 = QHBoxLayout()
        self.hboxlayout5.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout5.setSpacing(0)
        self.hboxlayout5.setObjectName("hboxlayout5")

        self.ItemUtilityLabel = QLabel(self.ItemSlotsGrid)
        self.ItemUtilityLabel.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.ItemUtilityLabel.setObjectName("ItemUtilityLabel")
        self.hboxlayout5.addWidget(self.ItemUtilityLabel)

        self.ItemUtility = QLabel(self.ItemSlotsGrid)
        self.ItemUtility.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.ItemUtility.setObjectName("ItemUtility")
        self.hboxlayout5.addWidget(self.ItemUtility)

        spacerItem15 = QSpacerItem(5, 1, QSizePolicy.MinimumExpanding, QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem15)
        self.gridlayout7.addLayout(self.hboxlayout5, 7, 8, 1, 1)

        self.Gem_Label_9 = QLabel(self.ItemSlotsGrid)
        self.Gem_Label_9.setTextFormat(Qt.PlainText)
        self.Gem_Label_9.setObjectName("Gem_Label_9")
        self.gridlayout7.addWidget(self.Gem_Label_9, 8, 0, 1, 1)

        self.Type_9 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_9.setObjectName("Type_9")
        self.gridlayout7.addWidget(self.Type_9, 8, 1, 1, 1)

        self.Amount_Edit_9 = QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_9.setObjectName("Amount_Edit_9")
        self.gridlayout7.addWidget(self.Amount_Edit_9, 8, 2, 1, 1)

        self.Effect_9 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_9.setEditable(True)
        self.Effect_9.setObjectName("Effect_9")
        self.gridlayout7.addWidget(self.Effect_9, 8, 3, 1, 1)

        self.Requirement_9 = QLineEdit(self.ItemSlotsGrid)
        self.Requirement_9.setObjectName("Requirement_9")
        self.gridlayout7.addWidget(self.Requirement_9, 8, 4, 1, 3)

        spacerItem16 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem16, 8, 8, 1, 4)

        self.Gem_Label_10 = QLabel(self.ItemSlotsGrid)
        self.Gem_Label_10.setTextFormat(Qt.PlainText)
        self.Gem_Label_10.setObjectName("Gem_Label_10")
        self.gridlayout7.addWidget(self.Gem_Label_10, 9, 0, 1, 1)

        self.Type_10 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_10.setObjectName("Type_10")
        self.gridlayout7.addWidget(self.Type_10, 9, 1, 1, 1)

        self.Amount_Edit_10 = QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_10.setObjectName("Amount_Edit_10")
        self.gridlayout7.addWidget(self.Amount_Edit_10, 9, 2, 1, 1)

        self.Effect_10 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_10.setEditable(True)
        self.Effect_10.setObjectName("Effect_10")
        self.gridlayout7.addWidget(self.Effect_10, 9, 3, 1, 1)

        self.Requirement_10 = QLineEdit(self.ItemSlotsGrid)
        self.Requirement_10.setObjectName("Requirement_10")
        self.gridlayout7.addWidget(self.Requirement_10, 9, 4, 1, 3)

        self.Gem_Label_11 = QLabel(self.ItemSlotsGrid)
        self.Gem_Label_11.setTextFormat(Qt.PlainText)
        self.Gem_Label_11.setObjectName("Gem_Label_11")
        self.gridlayout7.addWidget(self.Gem_Label_11, 10, 0, 1, 1)

        self.Type_11 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_11.setObjectName("Type_11")
        self.gridlayout7.addWidget(self.Type_11, 10, 1, 1, 1)

        self.Amount_Edit_11 = QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_11.setObjectName("Amount_Edit_11")
        self.gridlayout7.addWidget(self.Amount_Edit_11, 10, 2, 1, 1)

        self.Effect_11 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_11.setEditable(True)
        self.Effect_11.setObjectName("Effect_11")
        self.gridlayout7.addWidget(self.Effect_11, 10, 3, 1, 1)

        self.Requirement_11 = QLineEdit(self.ItemSlotsGrid)
        self.Requirement_11.setObjectName("Requirement_11")
        self.gridlayout7.addWidget(self.Requirement_11, 10, 4, 1, 3)

        self.Gem_Label_12 = QLabel(self.ItemSlotsGrid)
        self.Gem_Label_12.setTextFormat(Qt.PlainText)
        self.Gem_Label_12.setObjectName("Gem_Label_12")
        self.gridlayout7.addWidget(self.Gem_Label_12, 11, 0, 1, 1)

        self.Type_12 = SearchingCombo(self.ItemSlotsGrid)
        self.Type_12.setObjectName("Type_12")
        self.gridlayout7.addWidget(self.Type_12, 11, 1, 1, 1)

        self.Amount_Edit_12 = QLineEdit(self.ItemSlotsGrid)
        self.Amount_Edit_12.setObjectName("Amount_Edit_12")
        self.gridlayout7.addWidget(self.Amount_Edit_12, 11, 2, 1, 1)

        self.Effect_12 = SearchingCombo(self.ItemSlotsGrid)
        self.Effect_12.setEditable(True)
        self.Effect_12.setObjectName("Effect_12")
        self.gridlayout7.addWidget(self.Effect_12, 11, 3, 1, 1)

        self.Requirement_12 = QLineEdit(self.ItemSlotsGrid)
        self.Requirement_12.setObjectName("Requirement_12")
        self.gridlayout7.addWidget(self.Requirement_12, 11, 4, 1, 3)

        spacerItem17 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem17, 5, 0, 1, 7)

        spacerItem18 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem18, 6, 0, 1, 3)

        spacerItem19 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem19, 6, 3, 1, 4)

        spacerItem20 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem20, 7, 0, 1, 1)

        self.LabelItemCraftTime = QLabel(self.ItemSlotsGrid)
        self.LabelItemCraftTime.setTextFormat(Qt.PlainText)
        self.LabelItemCraftTime.setObjectName("LabelItemCraftTime")
        self.gridlayout7.addWidget(self.LabelItemCraftTime, 7, 1, 1, 1)

        self.ItemCraftTime = QLineEdit(self.ItemSlotsGrid)
        self.ItemCraftTime.setObjectName("ItemCraftTime")
        self.gridlayout7.addWidget(self.ItemCraftTime, 7, 2, 1, 1)

        self.ItemImbueLabel = QLabel(self.ItemSlotsGrid)
        self.ItemImbueLabel.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.ItemImbueLabel.setObjectName("ItemImbueLabel")
        self.gridlayout7.addWidget(self.ItemImbueLabel, 7, 3, 1, 2)

        self.ItemImbue = QLabel(self.ItemSlotsGrid)
        self.ItemImbue.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.ItemImbue.setObjectName("ItemImbue")
        self.gridlayout7.addWidget(self.ItemImbue, 7, 5, 1, 1)

        self.ItemImbueTotal = QLabel(self.ItemSlotsGrid)
        self.ItemImbueTotal.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.ItemImbueTotal.setObjectName("ItemImbueTotal")
        self.gridlayout7.addWidget(self.ItemImbueTotal, 7, 6, 1, 1)

        spacerItem21 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem21, 8, 0, 4, 3)

        self.ItemOverchargeLabel = QLabel(self.ItemSlotsGrid)
        self.ItemOverchargeLabel.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.ItemOverchargeLabel.setObjectName("ItemOverchargeLabel")
        self.gridlayout7.addWidget(self.ItemOverchargeLabel, 8, 3, 1, 2)

        self.ItemOvercharge = QLabel(self.ItemSlotsGrid)
        self.ItemOvercharge.setAlignment(Qt.AlignCenter)
        self.ItemOvercharge.setObjectName("ItemOvercharge")
        self.gridlayout7.addWidget(self.ItemOvercharge, 8, 5, 1, 2)

        self.ItemCostLabel = QLabel(self.ItemSlotsGrid)
        self.ItemCostLabel.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.ItemCostLabel.setObjectName("ItemCostLabel")
        self.gridlayout7.addWidget(self.ItemCostLabel, 9, 3, 1, 2)

        self.ItemCost = QLabel(self.ItemSlotsGrid)
        self.ItemCost.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.ItemCost.setObjectName("ItemCost")
        self.gridlayout7.addWidget(self.ItemCost, 9, 5, 1, 2)

        self.ItemPriceLabel = QLabel(self.ItemSlotsGrid)
        self.ItemPriceLabel.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.ItemPriceLabel.setObjectName("ItemPriceLabel")
        self.gridlayout7.addWidget(self.ItemPriceLabel, 10, 3, 1, 2)

        self.ItemPrice = QLabel(self.ItemSlotsGrid)
        self.ItemPrice.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.ItemPrice.setObjectName("ItemPrice")
        self.gridlayout7.addWidget(self.ItemPrice, 10, 5, 1, 2)

        spacerItem22 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem22, 11, 0, 1, 7)

        spacerItem23 = QSpacerItem(1, 0, QSizePolicy.Minimum, QSizePolicy.MinimumExpanding)
        self.gridlayout7.addItem(spacerItem23, 12, 0, 1, 9)
        self.vboxlayout6.addWidget(self.ScrollSlots)
        self.hboxlayout4.addLayout(self.vboxlayout6)
        self.stackedlayout.addWidget(self.ItemSlotsFrame)
        self.vboxlayout1.addLayout(self.stackedlayout)
        self.vboxlayout.addWidget(self.GroupItemFrame)
        self.gridlayout.addLayout(self.vboxlayout, 1, 0, 1, 4)
        B_SCWindow.setCentralWidget(self.ScWinFrame)
        self.LabelCharName.setBuddy(self.CharName)
        self.LabelOutfitName.setBuddy(self.OutfitName)
        self.ItemLevelLabel.setBuddy(self.ItemLevel)
        self.ItemNameLabel.setBuddy(self.ItemNameCombo)

        self.retranslateUi(B_SCWindow)
        QMetaObject.connectSlotsByName(B_SCWindow)
        B_SCWindow.setTabOrder(self.CharName, self.Realm)
        B_SCWindow.setTabOrder(self.Realm, self.CharClass)
        B_SCWindow.setTabOrder(self.CharClass, self.CharRace)
        B_SCWindow.setTabOrder(self.CharRace, self.CharLevel)
        B_SCWindow.setTabOrder(self.CharLevel, self.RealmRank)
        B_SCWindow.setTabOrder(self.RealmRank, self.CraftTime)
        B_SCWindow.setTabOrder(self.CraftTime, self.ChampionLevel)
        B_SCWindow.setTabOrder(self.ChampionLevel, self.OutfitName)
        B_SCWindow.setTabOrder(self.OutfitName, self.PieceTab)
        B_SCWindow.setTabOrder(self.PieceTab, self.ItemLevel)
        B_SCWindow.setTabOrder(self.ItemLevel, self.ItemLevelButton)
        B_SCWindow.setTabOrder(self.ItemLevelButton, self.QualEdit)
        B_SCWindow.setTabOrder(self.QualEdit, self.QualDrop)
        B_SCWindow.setTabOrder(self.QualDrop, self.ItemNameCombo)
        B_SCWindow.setTabOrder(self.ItemNameCombo, self.Equipped)
        B_SCWindow.setTabOrder(self.Equipped, self.ToggleItemView)
        B_SCWindow.setTabOrder(self.ToggleItemView, self.ItemRealm)
        B_SCWindow.setTabOrder(self.ItemRealm, self.ItemType)
        B_SCWindow.setTabOrder(self.ItemType, self.ItemSource)
        B_SCWindow.setTabOrder(self.ItemSource, self.BonusEdit)
        B_SCWindow.setTabOrder(self.BonusEdit, self.AFDPSEdit)
        B_SCWindow.setTabOrder(self.AFDPSEdit, self.SpeedEdit)
        B_SCWindow.setTabOrder(self.SpeedEdit, self.Offhand)
        B_SCWindow.setTabOrder(self.Offhand, self.DamageType)
        B_SCWindow.setTabOrder(self.DamageType, self.ItemRequirement)
        B_SCWindow.setTabOrder(self.ItemRequirement, self.ClassRestrictionTable)
        B_SCWindow.setTabOrder(self.ClassRestrictionTable, self.ItemNoteText)
        B_SCWindow.setTabOrder(self.ItemNoteText, self.NoteText)
        B_SCWindow.setTabOrder(self.NoteText, self.Type_1)
        B_SCWindow.setTabOrder(self.Type_1, self.Amount_Edit_1)
        B_SCWindow.setTabOrder(self.Amount_Edit_1, self.Amount_Drop_1)
        B_SCWindow.setTabOrder(self.Amount_Drop_1, self.Effect_1)
        B_SCWindow.setTabOrder(self.Effect_1, self.Makes_1)
        B_SCWindow.setTabOrder(self.Makes_1, self.Requirement_1)
        B_SCWindow.setTabOrder(self.Requirement_1, self.Type_2)
        B_SCWindow.setTabOrder(self.Type_2, self.Amount_Edit_2)
        B_SCWindow.setTabOrder(self.Amount_Edit_2, self.Amount_Drop_2)
        B_SCWindow.setTabOrder(self.Amount_Drop_2, self.Effect_2)
        B_SCWindow.setTabOrder(self.Effect_2, self.Makes_2)
        B_SCWindow.setTabOrder(self.Makes_2, self.Requirement_2)
        B_SCWindow.setTabOrder(self.Requirement_2, self.Type_3)
        B_SCWindow.setTabOrder(self.Type_3, self.Amount_Edit_3)
        B_SCWindow.setTabOrder(self.Amount_Edit_3, self.Amount_Drop_3)
        B_SCWindow.setTabOrder(self.Amount_Drop_3, self.Effect_3)
        B_SCWindow.setTabOrder(self.Effect_3, self.Makes_3)
        B_SCWindow.setTabOrder(self.Makes_3, self.Requirement_3)
        B_SCWindow.setTabOrder(self.Requirement_3, self.Type_4)
        B_SCWindow.setTabOrder(self.Type_4, self.Amount_Edit_4)
        B_SCWindow.setTabOrder(self.Amount_Edit_4, self.Amount_Drop_4)
        B_SCWindow.setTabOrder(self.Amount_Drop_4, self.Effect_4)
        B_SCWindow.setTabOrder(self.Effect_4, self.Makes_4)
        B_SCWindow.setTabOrder(self.Makes_4, self.Requirement_4)
        B_SCWindow.setTabOrder(self.Requirement_4, self.Type_5)
        B_SCWindow.setTabOrder(self.Type_5, self.Amount_Edit_5)
        B_SCWindow.setTabOrder(self.Amount_Edit_5, self.Amount_Drop_5)
        B_SCWindow.setTabOrder(self.Amount_Drop_5, self.Effect_5)
        B_SCWindow.setTabOrder(self.Effect_5, self.Requirement_5)
        B_SCWindow.setTabOrder(self.Requirement_5, self.Type_6)
        B_SCWindow.setTabOrder(self.Type_6, self.Amount_Edit_6)
        B_SCWindow.setTabOrder(self.Amount_Edit_6, self.Amount_Drop_6)
        B_SCWindow.setTabOrder(self.Amount_Drop_6, self.Effect_6)
        B_SCWindow.setTabOrder(self.Effect_6, self.Requirement_6)
        B_SCWindow.setTabOrder(self.Requirement_6, self.Type_7)
        B_SCWindow.setTabOrder(self.Type_7, self.Amount_Edit_7)
        B_SCWindow.setTabOrder(self.Amount_Edit_7, self.Effect_7)
        B_SCWindow.setTabOrder(self.Effect_7, self.Requirement_7)
        B_SCWindow.setTabOrder(self.Requirement_7, self.Type_8)
        B_SCWindow.setTabOrder(self.Type_8, self.Amount_Edit_8)
        B_SCWindow.setTabOrder(self.Amount_Edit_8, self.Effect_8)
        B_SCWindow.setTabOrder(self.Effect_8, self.Requirement_8)
        B_SCWindow.setTabOrder(self.Requirement_8, self.Type_9)
        B_SCWindow.setTabOrder(self.Type_9, self.Amount_Edit_9)
        B_SCWindow.setTabOrder(self.Amount_Edit_9, self.Effect_9)
        B_SCWindow.setTabOrder(self.Effect_9, self.Requirement_9)
        B_SCWindow.setTabOrder(self.Requirement_9, self.Type_10)
        B_SCWindow.setTabOrder(self.Type_10, self.Amount_Edit_10)
        B_SCWindow.setTabOrder(self.Amount_Edit_10, self.Effect_10)
        B_SCWindow.setTabOrder(self.Effect_10, self.Requirement_10)
        B_SCWindow.setTabOrder(self.Requirement_10, self.Type_11)
        B_SCWindow.setTabOrder(self.Type_11, self.Amount_Edit_11)
        B_SCWindow.setTabOrder(self.Amount_Edit_11, self.Effect_11)
        B_SCWindow.setTabOrder(self.Effect_11, self.Requirement_11)
        B_SCWindow.setTabOrder(self.Requirement_11, self.Type_12)
        B_SCWindow.setTabOrder(self.Type_12, self.Amount_Edit_12)
        B_SCWindow.setTabOrder(self.Amount_Edit_12, self.Effect_12)
        B_SCWindow.setTabOrder(self.Effect_12, self.Requirement_12)
        B_SCWindow.setTabOrder(self.Requirement_12, self.ItemCraftTime)
        B_SCWindow.setTabOrder(self.ItemCraftTime, self.SkillsList)

    def retranslateUi(self, B_SCWindow):
        B_SCWindow.setWindowTitle(QApplication.translate("B_SCWindow", "Spellcrafting Calculator", None))
        self.LabelCharName.setText(QApplication.translate("B_SCWindow", "&Name: ", None))
        self.LabelRealm.setText(QApplication.translate("B_SCWindow", "Realm: ", None))
        self.LabelCharClass.setText(QApplication.translate("B_SCWindow", "Class: ", None))
        self.LabelCharRace.setText(QApplication.translate("B_SCWindow", "Race: ", None))
        self.LabelCharLevel.setText(QApplication.translate("B_SCWindow", "Level: ", None))
        self.LabelRealmRank.setText(QApplication.translate("B_SCWindow", "RR: ", None))
        self.LabelCraftTime.setText(QApplication.translate("B_SCWindow", "Time: ", None))
        self.LabelChampionLevel.setText(QApplication.translate("B_SCWindow", "CL: ", None))
        self.LabelOutfitName.setText(QApplication.translate("B_SCWindow", "&Outfit: ", None))
        self.LabelTotalCost.setText(QApplication.translate("B_SCWindow", "Cost: ", None))
        self.TotalCost.setText(QApplication.translate("B_SCWindow", "0", None))
        self.LabelTotalPrice.setText(QApplication.translate("B_SCWindow", "Price: ", None))
        self.TotalPrice.setText(QApplication.translate("B_SCWindow", "0", None))
        self.StrengthLabel.setText(QApplication.translate("B_SCWindow", "STR: ", None))
        self.Strength.setText(QApplication.translate("B_SCWindow", "0", None))
        self.StrengthCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.ConstitutionLabel.setText(QApplication.translate("B_SCWindow", "CON: ", None))
        self.Constitution.setText(QApplication.translate("B_SCWindow", "0", None))
        self.ConstitutionCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.DexterityLabel.setText(QApplication.translate("B_SCWindow", "DEX: ", None))
        self.Dexterity.setText(QApplication.translate("B_SCWindow", "0", None))
        self.DexterityCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.QuicknessLabel.setText(QApplication.translate("B_SCWindow", "QUI: ", None))
        self.Quickness.setText(QApplication.translate("B_SCWindow", "0", None))
        self.QuicknessCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.IntelligenceLabel.setText(QApplication.translate("B_SCWindow", "INT: ", None))
        self.Intelligence.setText(QApplication.translate("B_SCWindow", "0", None))
        self.IntelligenceCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.PietyLabel.setText(QApplication.translate("B_SCWindow", "PIE: ", None))
        self.Piety.setText(QApplication.translate("B_SCWindow", "0", None))
        self.PietyCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.CharismaLabel.setText(QApplication.translate("B_SCWindow", "CHA: ", None))
        self.Charisma.setText(QApplication.translate("B_SCWindow", "0", None))
        self.CharismaCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.EmpathyLabel.setText(QApplication.translate("B_SCWindow", "EMP: ", None))
        self.Empathy.setText(QApplication.translate("B_SCWindow", "0", None))
        self.EmpathyCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.AcuityLabel.setText(QApplication.translate("B_SCWindow", "ACU: ", None))
        self.Acuity.setText(QApplication.translate("B_SCWindow", "0", None))
        self.AcuityCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.PowerLabel.setText(QApplication.translate("B_SCWindow", "Pow: ", None))
        self.Power.setText(QApplication.translate("B_SCWindow", "0", None))
        self.PowerCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.PowerPoolLabel.setText(QApplication.translate("B_SCWindow", "PP%: ", None))
        self.PowerPool.setText(QApplication.translate("B_SCWindow", "0", None))
        self.PowerPoolCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.FatigueLabel.setText(QApplication.translate("B_SCWindow", "End: ", None))
        self.Fatigue.setText(QApplication.translate("B_SCWindow", "0", None))
        self.FatigueCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.AFLabel.setText(QApplication.translate("B_SCWindow", "AF: ", None))
        self.AF.setText(QApplication.translate("B_SCWindow", "0", None))
        self.AFCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.HitsLabel.setText(QApplication.translate("B_SCWindow", "Hits: ", None))
        self.Hits.setText(QApplication.translate("B_SCWindow", "0", None))
        self.HitsCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.LabelTotalUtility.setText(QApplication.translate("B_SCWindow", "Utility: ", None))
        self.TotalUtility.setText(QApplication.translate("B_SCWindow", "0.0", None))
        self.BodyLabel.setText(QApplication.translate("B_SCWindow", "Body: ", None))
        self.Body.setText(QApplication.translate("B_SCWindow", "0", None))
        self.BodyCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.ColdLabel.setText(QApplication.translate("B_SCWindow", "Cold: ", None))
        self.Cold.setText(QApplication.translate("B_SCWindow", "0", None))
        self.ColdCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.HeatLabel.setText(QApplication.translate("B_SCWindow", "Heat: ", None))
        self.Heat.setText(QApplication.translate("B_SCWindow", "0", None))
        self.HeatCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.EnergyLabel.setText(QApplication.translate("B_SCWindow", "Energy: ", None))
        self.Energy.setText(QApplication.translate("B_SCWindow", "0", None))
        self.EnergyCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.MatterLabel.setText(QApplication.translate("B_SCWindow", "Matter: ", None))
        self.Matter.setText(QApplication.translate("B_SCWindow", "0", None))
        self.MatterCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.SpiritLabel.setText(QApplication.translate("B_SCWindow", "Spirit: ", None))
        self.Spirit.setText(QApplication.translate("B_SCWindow", "0", None))
        self.SpiritCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.CrushLabel.setText(QApplication.translate("B_SCWindow", "Crush: ", None))
        self.Crush.setText(QApplication.translate("B_SCWindow", "0", None))
        self.CrushCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.ThrustLabel.setText(QApplication.translate("B_SCWindow", "Thrust: ", None))
        self.Thrust.setText(QApplication.translate("B_SCWindow", "0", None))
        self.ThrustCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.SlashLabel.setText(QApplication.translate("B_SCWindow", "Slash: ", None))
        self.Slash.setText(QApplication.translate("B_SCWindow", "0", None))
        self.SlashCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.EssenceLabel.setText(QApplication.translate("B_SCWindow", "Essence: ", None))
        self.Essence.setText(QApplication.translate("B_SCWindow", "0", None))
        self.EssenceCap.setText(QApplication.translate("B_SCWindow", "-", None))
        self.ItemLevelLabel.setText(QApplication.translate("B_SCWindow", "&Level: ", None))
        self.ItemLevelButton.setText(QApplication.translate("B_SCWindow", "...", None))
        self.ItemQualityLabel.setText(QApplication.translate("B_SCWindow", "Quality: ", None))
        self.ItemNameLabel.setText(QApplication.translate("B_SCWindow", "Item &Name: ", None))
        self.Equipped.setText(QApplication.translate("B_SCWindow", "Equi&pped", None))
        self.ToggleItemView.setText(QApplication.translate("B_SCWindow", "Item Slots", None))
        self.LabelItemInfo.setText(QApplication.translate("B_SCWindow", "Item Information:", None))
        self.LabelItemRealm.setText(QApplication.translate("B_SCWindow", "Realm: ", None))
        self.LabelItemType.setText(QApplication.translate("B_SCWindow", "Type: ", None))
        self.LabelItemSource.setText(QApplication.translate("B_SCWindow", "Origin: ", None))
        self.LabelBonusEdit.setText(QApplication.translate("B_SCWindow", "Bonus: ", None))
        self.LabelAFDPSEdit.setText(QApplication.translate("B_SCWindow", "DPS: ", None))
        self.LabelSpeedEdit.setText(QApplication.translate("B_SCWindow", "Speed: ", None))
        self.Offhand.setText(QApplication.translate("B_SCWindow", "Offhand", None))
        self.LabelDamageType.setText(QApplication.translate("B_SCWindow", "Damage: ", None))
        self.LabelItemRequirement.setText(QApplication.translate("B_SCWindow", "Requirement: ", None))
        self.LabelDBSource.setText(QApplication.translate("B_SCWindow", "Source: ", None))
        self.LabelClassRestrictionTable.setText(QApplication.translate("B_SCWindow", "Class Restrictions:", None))
        self.LabelItemNoteText.setText(QApplication.translate("B_SCWindow", "Item Notes:", None))
        self.LabelNoteText.setText(QApplication.translate("B_SCWindow", "Template Notes:", None))
        self.LabelGemType.setText(QApplication.translate("B_SCWindow", " Type", None))
        self.LabelGemAmount.setText(QApplication.translate("B_SCWindow", " Amount", None))
        self.LabelGemEffect.setText(QApplication.translate("B_SCWindow", " Effect", None))
        self.LabelGemMakes.setText(QApplication.translate("B_SCWindow", " Makes", None))
        self.LabelRequirement.setText(QApplication.translate("B_SCWindow", " Requirement", None))
        self.LabelGemPoints.setText(QApplication.translate("B_SCWindow", "Points", None))
        self.LabelGemCost.setText(QApplication.translate("B_SCWindow", "Unit Cost", None))
        self.LabelGemName.setText(QApplication.translate("B_SCWindow", "Name", None))
        self.Gem_Label_1.setText(QApplication.translate("B_SCWindow", "Slot &1: ", None))
        self.Makes_1.setSpecialValueText(QApplication.translate("B_SCWindow", " ", None))
        self.Points_1.setText(QApplication.translate("B_SCWindow", "0.0", None))
        self.Cost_1.setText(QApplication.translate("B_SCWindow", "0c", None))
        self.Gem_Label_2.setText(QApplication.translate("B_SCWindow", "Slot &2: ", None))
        self.Makes_2.setSpecialValueText(QApplication.translate("B_SCWindow", " ", None))
        self.Points_2.setText(QApplication.translate("B_SCWindow", "0.0", None))
        self.Cost_2.setText(QApplication.translate("B_SCWindow", "0c", None))
        self.Gem_Label_3.setText(QApplication.translate("B_SCWindow", "Slot &3: ", None))
        self.Makes_3.setSpecialValueText(QApplication.translate("B_SCWindow", " ", None))
        self.Points_3.setText(QApplication.translate("B_SCWindow", "0.0", None))
        self.Cost_3.setText(QApplication.translate("B_SCWindow", "0c", None))
        self.Gem_Label_4.setText(QApplication.translate("B_SCWindow", "Slot &4: ", None))
        self.Makes_4.setSpecialValueText(QApplication.translate("B_SCWindow", " ", None))
        self.Points_4.setText(QApplication.translate("B_SCWindow", "0.0", None))
        self.Cost_4.setText(QApplication.translate("B_SCWindow", "0c", None))
        self.Gem_Label_5.setText(QApplication.translate("B_SCWindow", "Slot &5: ", None))
        self.Gem_Label_6.setText(QApplication.translate("B_SCWindow", "Slot &6: ", None))
        self.Gem_Label_7.setText(QApplication.translate("B_SCWindow", "Slot &7: ", None))
        self.Gem_Label_8.setText(QApplication.translate("B_SCWindow", "Slot &8: ", None))
        self.ItemUtilityLabel.setText(QApplication.translate("B_SCWindow", "Utility:   ", None))
        self.ItemUtility.setText(QApplication.translate("B_SCWindow", "0.0", None))
        self.Gem_Label_9.setText(QApplication.translate("B_SCWindow", "Slot &9: ", None))
        self.Gem_Label_10.setText(QApplication.translate("B_SCWindow", "Slot 1&0:", None))
        self.Gem_Label_11.setText(QApplication.translate("B_SCWindow", "Slot 11&- ", None))
        self.Gem_Label_12.setText(QApplication.translate("B_SCWindow", "Slot 12&=", None))
        self.LabelItemCraftTime.setText(QApplication.translate("B_SCWindow", "Item SC Time (min): ", None))
        self.ItemImbueLabel.setText(QApplication.translate("B_SCWindow", "Imbue Points: ", None))
        self.ItemImbue.setText(QApplication.translate("B_SCWindow", "0.0", None))
        self.ItemImbueTotal.setText(QApplication.translate("B_SCWindow", " / 0.0", None))
        self.ItemOverchargeLabel.setText(QApplication.translate("B_SCWindow", "Overcharge: ", None))
        self.ItemOvercharge.setText(QApplication.translate("B_SCWindow", "None", None))
        self.ItemCostLabel.setText(QApplication.translate("B_SCWindow", "Item Cost: ", None))
        self.ItemPriceLabel.setText(QApplication.translate("B_SCWindow", "Item Price: ", None))

